### ISSUE TITLE
Have an issue with AppCenterReactNativeCrashesListener.java on android

### ISSUE THREAD

**Issue by juliaitbaeva** [microsoft/appcenter-sdk-react-native#1006]
### **Description**

Please describe the issue you are facing using the SDK.
I observe issue with android build after I've updated react-native from 0.64 to 0.68.
When I run android emulator from Android Studio 
build crashed with error : /project/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/reactnative/crashes/AppCenterReactNativeCrashesListener.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

### **Repro Steps**
Please list the steps used to reproduce your issue.

1. Run emulator from Android Studio

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 4.4.4
2. Which OS version did you experience the issue on?
    - e.g. Android 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Nexus 6 API 30 emulator
4. What third party libraries are you using?
    - example react-native 0.68
    - gradle https\://services.gradle.org/distributions/gradle-7.5-all.zip in gradle-wrapper.properties, classpath('com.android.tools.build:gradle:7.4.2') in build.gradle.
    -  buildToolsVersion = "30.0.3"
        firebaseMessagingVersion = "21.1.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        supportLibVersion = "30.0.0"
        kotlinVersion = '1.6.21'
5. Run the following command and paste the output below: `react-native info`

Place output here
System:
    OS: macOS 13.4
    CPU: (8) x64 Apple M1
    Memory: 21.43 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/wprojects/temp/voya-cust/node_modules/.bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 34.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9971841
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.7 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.1 => 7.0.1 
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by AnatolyPristensky** [comment]
Hello @juliaitbaeva, could you please describe your issue more detailed? More detailed repro steps for example.

**Comment by AnatolyPristensky** [comment]
We haven't heard from you for a while, so I'm closing this issue. Please feel free to reopen it in case of new information.

**Comment by DanielWoldehana** [comment]
I am getting the same Error when I upgraded "react-native": "0.73.1", can anyone help with this? Thank you
