### ISSUE TITLE
Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:5.0.0

### ISSUE THREAD

**Issue by PiyushGaurav** [microsoft/appcenter-sdk-react-native#1010]
Hi,

I'm getting this error while launching the react native app from android device however it works fine with iOS device.

Error: Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:5.0.0

Device : Pixel 4a
App Center SDK version : v5.0.0

**Comment by PiyushGaurav** [comment]
Downgrading App Center SDK to v4.4.5 fixed my issue.

**Comment by AnatolyPristensky** [comment]
Hello @PiyushGaurav,
closing as duplicate of https://github.com/microsoft/appcenter-sdk-react-native/issues/1011
