### ISSUE TITLE
gradlew ENOENT when build apk

### ISSUE THREAD

**Issue by robertyulisman** [microsoft/appcenter-sdk-react-native#1017]
![app-center-error](https://github.com/microsoft/appcenter-sdk-react-native/assets/55675899/5ebdc6d1-cd32-414d-9571-9d35833ce57a)

### **Description**

always getting Error Gradle when building for Android

### **Details**

1. "appcenter": "5.0.0",
2. "appcenter-analytics": "5.0.0",
3. "appcenter-crashes": "5.0.0",
4. "react": "18.2.0",
5. "react-native": "0.72.4",
6. "react-native-code-push": "^8.0.2",

**Comment by DmitriyKirakosyan** [comment]
Hi @robertyulisman , this is not an App Center React Native SDK issue. Please reach out to our [support team](https://learn.microsoft.com/en-us/appcenter/help) and they will help you to resolve it.

**Comment by robertyulisman** [comment]
> Hi @robertyulisman , this is not an App Center React Native SDK issue. Please reach out to our [support team](https://learn.microsoft.com/en-us/appcenter/help) and they will help you to resolve it.

hi, after contact support team, i have success build my apk, the problem is, in my file there is package.lock while i am using yarn.lock, so after deleting package.lock file, i have success build my apk
