### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by jaydeep-myblueprint** [microsoft/appcenter-sdk-react-native#1024]
### **Description**

Getting **502 Bad Gateway** error suddenly after solving pod checksum error

![Screenshot 2024-01-10 at 11 57 50 AM](https://github.com/microsoft/appcenter-sdk-react-native/assets/139258105/8718b346-d109-4ff6-ac7c-203960b81c39)

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Solved pod checksum issue of react-native 0.72.6 using [this](https://github.com/boostorg/boost/issues/843#issuecomment-1872995591)
2. Push new builds in staging, and getting 502 Bad Gateway error

### **Details**

1. Which version of the App Center SDK are you using?
    **- 4.4.5**

2. Which OS version did you experience the issue on?
    **- iOS 11 onwards**

3. Run the following command and paste the output below: `react-native info`

      **System:
        OS: macOS 14.2.1
        CPU: (8) arm64 Apple M1
        Memory: 277.45 MB / 16.00 GB
        Shell:
          version: "5.9"
          path: /bin/zsh
      Binaries:
        Node:
          version: 18.17.0
          path: /opt/homebrew/opt/node@18/bin/node
        Yarn:
          version: 1.22.19
          path: /opt/homebrew/bin/yarn
        npm:
          version: 9.6.7
          path: /opt/homebrew/opt/node@18/bin/npm
        Watchman:
          version: 2023.07.10.00
          path: /opt/homebrew/bin/watchman
      Managers:
        CocoaPods:
          version: 1.14.3
          path: /usr/local/bin/pod
      SDKs:
        iOS SDK:
          Platforms:
            - DriverKit 23.2
            - iOS 17.2
            - macOS 14.2
            - tvOS 17.2
            - watchOS 10.2
        Android SDK: Not Found
      IDEs:
        Android Studio: 2023.1 AI-231.9392.1.2311.11076708
        Xcode:
          version: 15.1/15C65
          path: /usr/bin/xcodebuild
      Languages:
        Java:
          version: 11.0.19
          path: /usr/bin/javac
        Ruby:
          version: 2.6.10
          path: /usr/bin/ruby
      npmPackages:
        "@react-native-community/cli": Not Found
        react:
          installed: 18.2.0
          wanted: 18.2.0
        react-native:
          installed: 0.72.6
          wanted: 0.72.6
        react-native-macos: Not Found
      npmGlobalPackages:
        "*react-native*": Not Found
      Android:
        hermesEnabled: true
        newArchEnabled: false
      iOS:
        hermesEnabled: true
        newArchEnabled: false**

4. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
 **- 1.14.3**

**Comment by jaydeep-myblueprint** [comment]
**Sometimes get this one randomly** 

![Screenshot 2024-01-10 at 2 34 34 PM](https://github.com/microsoft/appcenter-sdk-react-native/assets/139258105/03d58ce4-091f-445a-9680-425d1fcdaa9a)

**Comment by velimir-jankovic** [comment]
@jaydeep-myblueprint can you please contact our support and provide your url to your application so we can check on our side?
https://learn.microsoft.com/en-us/appcenter/help
