### ISSUE TITLE
no known class method for selector 'setDataResidencyRegion:'

### ISSUE THREAD

**Issue by notjulian** [microsoft/appcenter-sdk-react-native#1027]
Hi,
after upgrade to version 5.0.1
If I try to compile ios version I get an error ... android version works

thanks

### **Description**

```
❌  /Users/..../node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:20: no known class method for selector 'setDataResidencyRegion:'

    [MSACAppCenter setDataResidencyRegion:dataResidencyRegion];
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install version 5.0.1

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 1.5.0
2. Which OS version did you experience the issue on?
    - ios 17
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone 15
4. What third party libraries are you using?
    -
5. Run the following command and paste the output below: `react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 38.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/juliandev/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11076708
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.21 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.12 => 0.71.12 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

`1.14.3`

**Comment by ceyanesb** [comment]
Same for me

**Comment by notjulian** [comment]
> Same for me. From which version did you upgrade the package? @notjulian

from 5.0.0 to 5.0.1

now I'm back on 5.0.0

**Comment by AnatolyPristensky** [comment]
Hello @notjulian, thank you for the information. We are working on it.

**Comment by DmitriyKirakosyan** [comment]
Please perform these commands and let me know if works:

```bash
pod cache clean --all
pod repo update
pod install
```

Also try to remove the `Podfile.lock`, if these commands don't help.

**Comment by stefan-schweiger** [comment]
@DmitriyKirakosyan was running into the same issue and seems to work for me with cleaning the cache and updating the repo.

**Comment by notjulian** [comment]
> Please perform these commands and let me know if works:
> 
> ```shell
> pod cache clean --all
> pod repo update
> pod install
> ```
> 
> Also try to remove the `Podfile.lock`, if these commands don't help.

`react-native-clean-project` did the job

sorry to bother you ... it's ok now
