### ISSUE TITLE
React-native IOS build issue. "Error installing hermes-engine"

### ISSUE THREAD

**Issue by yuriydrobniy** [microsoft/appcenter-sdk-react-native#1029]
### **Description**

React-native IOS build issue.

### **Repro Steps**

Appcenter -> IOS -> Build now.

Messages: 

```
...
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.71.10)

[!] Error installing hermes-engine
...

/usr/local/lib/ruby/gems/3.0.0/bin/pod install --repo-update
```

```
##[error]The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/pod' failed with exit code 1
```

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 4.4.3
2. Which OS version did you experience the issue on?
    - iOS
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator, iPhone X physical device
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

```
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 88.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.31.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/XX/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.1 AI-231.9392.1.2311.11255304
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.9 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.10 => 0.71.10 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.14.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by DmitriyKirakosyan** [comment]
@yuriydrobniy , thank you for reaching out! This issue seems to be a duplicate or having the same root cause as https://github.com/microsoft/appcenter-sdk-react-native/issues/1028.


Please reach out to our support team, as it was suggested in #1028.
This repository is for the AppCenter ReactNative SDK issues.
