### ISSUE TITLE
Cannot read property 'trackEvent' of undefined

### ISSUE THREAD

**Issue by ASVBPREAUBV** [Microsoft/AppCenter-SDK-React-Native#145]
Dependencies installed:
` 
    "mobile-center":`` "^0.10.0",
    "mobile-center-analytics": "^0.10.0",
    "mobile-center-crashes": "^0.10.0"
`

Installation description i used:
https://docs.microsoft.com/en-us/mobile-center/sdk/getting-started/react-native

Implementation in Code:

`
import Analytics from 'mobile-center-analytics';
Analytics.trackEvent('Video clicked', { Category: 'Music', FileName: 'favorite.avi' });
`

Typescript compiles. App loads. Snippet above gets called before redux provider or routing.
<img width="368" alt="screen shot 2017-10-30 at 09 03 50" src="https://user-images.githubusercontent.com/4126256/32160766-7703ba26-bd53-11e7-947a-34bb38dd3c24.png">

**Comment by bmourat** [comment]
Hi @ASVBPREAUBV 

Could you provide more info this issue: what platform are you testing on, the output of the "react-native info" command and your setup js code.

Best,
Murat

**Comment by ASVBPREAUBV** [comment]
Im testing on mac. A boilerplate react-native app from create-react-native-app. typescript compiled into another folder to serve the JS. We use a whole lot of dependencies, they all work fine. What is the command react-native info? i have never seen it.

**Comment by bmourat** [comment]
Does this happen both on android and ios? "react-native info" just outputs versions of all important tools. Here is my output:
Environment:
  OS:  macOS High Sierra 10.13
  Node:  8.7.0
  Yarn:  Not Found
  npm:  4.6.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.0.1 Build version 9A1004
  Android Studio:  3.0 AI-171.4408382

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: 0.49.5 => 0.49.5

**Comment by ASVBPREAUBV** [comment]
that command does not show up
<img width="662" alt="screen shot 2017-10-31 at 14 30 59" src="https://user-images.githubusercontent.com/4126256/32226213-3356820e-be48-11e7-8b4e-fcee18e4cb75.png">

**Comment by bmourat** [comment]
MobileCenter relies on the native modules, which means it supports apps created with "react-native init" command. If you created your app with "create-react-native-app" command you need to eject first. See this [article](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md). Please note that this process is irreversible.

Best,
Murat

**Comment by dhei** [comment]
Hey @ASVBPREAUBV,

As @bmourat mentioned above, mobile center SDK relies on native iOS/Android modules; therefore, apps created with "create-react-native-app" (CRNA) or Expo are not supported. As a workaround, you'll need to eject your "create-react-native-app" which is irreversible. In case you're using pure-JS Expo, you will need [Expo SDK](https://docs.expo.io/versions/latest/introduction/faq.html#how-do-i-add-custom-native-code-to-my-expo-project).

Btw - `react-native info` CLI is available with react-native@0.48 or later, so you don't see that because you're on older version of react-native.

**Comment by guperrot** [comment]
#129 is already used to track root cause.

**Comment by alexlevy0** [comment]
Same issue here with RN@54.1

**Comment by guperrot** [comment]
@alexlevy0 does that comment apply to you? https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/145#issuecomment-340832885

**Comment by alexlevy0** [comment]
@guperrot I'm not using create-react-native-app or Expo neither.

I solved the problem by completely reinstalling the SDK and modules. New it's works fine thx 👍

**Comment by guperrot** [comment]
Glad you could figure out the issue, sorry for the inconvenience.
