### ISSUE TITLE
iOS JS Warning: Sending '...' with no listeners

### ISSUE THREAD

**Issue by jjring** [Microsoft/AppCenter-SDK-React-Native#168]
I keep getting the following warnings when trying to send crash reports, however the crash reports still get sent properly. During setup with "react-native link", I selected "Automatically" for when to send crash reports. We are not using any of these listeners in our project. Since the documentation says "All callbacks are optional.", it seems like these warnings should not be shown.

The two errors I get are:
Sending 'MobileCenterErrorReportOnBeforeSending' with no listeners registered.
![screen shot 2017-11-20 at 1 22 32 pm](https://user-images.githubusercontent.com/6107648/33035302-9d2bd61a-cdf8-11e7-836b-5ff4b9dbbad6.png)

Sending 'MobileCenterErrorReportOnSendingSucceeded' with no listeners registered.
![screen shot 2017-11-20 at 1 22 09 pm](https://user-images.githubusercontent.com/6107648/33035301-9d1c4902-cdf8-11e7-8036-3e70f84c0df2.png)

**Comment by dhei** [comment]
@jjring, thank you for reporting this bug, this bug will be fixed in the next release.

**Comment by jjring** [comment]
Thanks for the quick turnaround!

**Comment by dhei** [comment]
I reverted #169 due to some issue found with Push listener not get called. Let me re-open this issue to track this bug.

**Comment by dhei** [comment]
Fixed in #192. Will be shipped in next release.

**Comment by lukewlms** [comment]
In case anyone else is also trying to Google these messages, here's the full text I get:

> Sending 'AppCenterErrorReportOnBeforeSending' with no listeners registered

> Sending 'AppCenterErrorReportOnSendingSucceeded' with no listeners registered.
