### ISSUE TITLE
Add typescript declaration files

### ISSUE THREAD

**Issue by KSanthanam** [microsoft/appcenter-sdk-react-native#172]
The Appcenter modules for react-native are missing the declaration (d.ts) files. Can you please add them.

**Comment by lucamorelli** [comment]
seems I have same problem with the cordova plugin

**Comment by guperrot** [comment]
Hi the cordova plugin is managed in another repository: https://github.com/Microsoft/AppCenter-SDK-Cordova, please create cordova issues there.

**Comment by guperrot** [comment]
Typescript files are available on RN SDK, we forgot to close this one.
