### ISSUE TITLE
Native linking fails on iOS

### ISSUE THREAD

**Issue by stefanoeb** [Microsoft/AppCenter-SDK-React-Native#189]
Hey there, I followed the install instructions on the AppCenter, `react-native link` command fails with:
```
[!] Unable to find a specification for `AppCenterReactNativeShared (~> 1.0.1)`
```
- I was asked & provided the android secret
- I was asked & provided the ios secret
- `react-native@0.50.4`

Any ideas on what could be happening?
Thank you

**Comment by dhei** [comment]
@stefanoeb Can you try `pod repo update` and then run `react-native link` again? It's probably your local cocoapod spec repo is not up-to-date.

**Comment by stefanoeb** [comment]
Exactly, my cocoapods repo was > 7 months old.
This worked, thank you @dhei !

**Comment by dhei** [comment]
@stefanoeb Glad it worked for you. You might also want to check out our [React Native SDK troubleshooting](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#cocoapods-unable-to-find-a-specification-for-appcenterreactnativeshared-during-react-native-link) doc for some common issues in react native. Let us know if you have more questions or feedback.
