### ISSUE TITLE
iOS Secret never requested.

### ISSUE THREAD

**Issue by michaelmerrill** [Microsoft/AppCenter-SDK-React-Native#198]
AppCenter never requests the iOS Secret, only Android. I tried running:

`react-native link`

and 

```
react-native link appcenter
react-native link appcenter-analytics
react-native link appcenter-crashes
```

however, only the Android Secret is requested. RNPM returns: 

```
App Secret for Android written to android/app/src/main/assets/appcenter-config.json
rnpm-install info Linking appcenter android dependency
rnpm-install info Android module appcenter has been successfully linked
rnpm-install info Linking appcenter ios dependency
rnpm-install info iOS module appcenter has been successfully linked
```

**Comment by dhei** [comment]
@michaelmerrill Where is your ios project located? Is it located at "/ios" subdirectory? Do you see a `Podfile` in your ios project? Can you share your `Podfile` content?

**Comment by michaelmerrill** [comment]
It's in the root directory which has an ios/ and android/ directory. I have an ios/Podfile which it looks like this: 

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Songspot' do
  use_frameworks!

  
  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'

end
```

**Comment by michaelmerrill** [comment]
I just set up a new RN project and it worked fine. It's something about my project. I'll debug and report back when I find out what the issue is.

**Comment by dhei** [comment]
@michaelmerrill What is your npm and react-native version? Do you have an existing `/ios/{yourapp}/AppCenter-Config.plist`? If so, maybe you can delete the plist file and run `react-native link` again.

It should be something unique to your project setup that breaks appcenter linker script. Let me know what you find out, thanks!

**Comment by michaelmerrill** [comment]
Ahh, so my AppDelegate is a swift file. AppCenter is looking for a .m file.

```
const appDelegatePaths = glob.sync('**/AppDelegate.m', {
    ignore: 'node_modules/**',
});
```

Is there a reason AppCenter would only wants obj-c AppDelegates? Also, the catch statement for that might be better as a console statement rather than debug so users can see that the AppDelegatePath is undefined if not found.

**Comment by dhei** [comment]
@michaelmerrill We will (1) improve our linker script to work with Swift application (2) improve error message to inform users about the error. Thanks for reporting this to us!

**Comment by guperrot** [comment]
Duplicates #73, you can track that issue instead.
