### ISSUE TITLE
Analytics.trackEvent doesn't allow message with no props

### ISSUE THREAD

**Issue by raymondchooi** [Microsoft/AppCenter-SDK-React-Native#201]
### Expected behaviour

`Analytics.trackEvent("Log in successful.");` should run without errors

### Actual behaviour

Error: 
`undefined is not an object (evaluating 'Object.keys(props)') `
in Analytics.js:26:16

### Steps to reproduce

- Add analytics following https://docs.microsoft.com/en-us/appcenter/sdk/analytics/react-native
- Track an event with just a message, e.g.
`Analytics.trackEvent("Log in successful.");`

### Possible solution

Add default props to equal null and add early break in Analytics.js:20:
```
function sanitizeProperties(props = null) {
    if(props === null) {
        return {};
    }
....
```

**Comment by dhei** [comment]
@raymondchooi thanks for reporting.👍  
We will fix this in our next release.
