### ISSUE TITLE
Custom properties on crashes

### ISSUE THREAD

**Issue by yaronlevi** [microsoft/appcenter-sdk-react-native#214]
In Sentry client's library we could do the following:
`Sentry.setUserContext({userID:123});`

Calling this once in our top root component would cause all the related exceptions to show up with userID:123 in the dashboard. We can also filter by userID in the dashboard. Also, we can set some extra props, basically a simple JSON.

Is this currently possible with the AppCenter's crash API?
If not, will it be available? (Any rough estimation?)

Also, we are interested in calling setUserContext() from both JS and Native side. 

Thanks in advance for any help on the issue (-:

**Comment by guperrot** [comment]
Hi, this feature is in the roadmap but we don't have any ETA yet.

**Comment by DmitriyKirakosyan** [comment]
Hi @yaronlevi , we already have such api, please see [Identify Users](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#identify-users).
I'm closing this issue but feel free to reopen if you have additional questions.
