### ISSUE TITLE
Can't install for iOS on react-native

### ISSUE THREAD

**Issue by veb** [Microsoft/AppCenter-SDK-React-Native#218]
My issue seems to be that after I run `react-native link`, iOS doesn't show up for me to enter my secret key.

```
➜  automatereact git:(master) ✗ react-native link
Scanning 660 folders for symlinks in /Users/mike/Projects/automatereact/node_modules (7ms)
Configuring AppCenter
? What is the Android App Secret? 
App Secret for Android written to android/app/src/main/assets/appcenter-config.json
➜  automatereact git:(master) ✗
```

I couldn't figure it out. So I created a `podfile` that had:
```
# Uncomment the next line to define a global platform for your project
#platform :ios, '11.0'
project '/Users/mike/Projects/automatereact/ios/AutomateReact.xcodeproj'

target 'AutomateReact' do
  use_frameworks!

  
  pod 'AppCenter'
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'

end
```

I installed that OK, then I ran `react-native link` again and it still isn't picking up iOS. 

If I start a new React-Native project, and follow the instructions on the Microsoft site, sure enough iOS stuff comes up:

```
➜  TestProject react-native link
Scanning folders for symlinks in /Users/mike/Projects/TestProject/node_modules (16ms)
Configuring AppCenter
? What is the Android App Secret? 
App Secret for Android written to android/app/src/main/assets/appcenter-config.json
rnpm-install info Linking appcenter android dependency 
rnpm-install info Android module appcenter has been successfully linked 
rnpm-install info Linking appcenter ios dependency 
rnpm-install info iOS module appcenter has been successfully linked 
? What is the iOS App Secret? 
```

What could I have done wrong, and why can't I get it working automatically like that on my original project?

**Comment by ngandhy** [comment]
try downgrading your react-native to 0.49 . Then try installing appcenter, then try upgrading back to 0.52... that worked for me.

**Comment by dhei** [comment]
@veb Sorry for the delay of response. Do you still experience this issue? If yes, I have a few questions: (1) is your ios project under "{project-root}/ios" path, or a customer path like "{project-root}/custom-ios"? (2) is it the first time you link app center or you have linked before? (3) what is your RN version and appcenter SDK version?

Thanks.

**Comment by veb** [comment]
Hi @dhei,

I ended up moving away from AppCenter after running into this issue. 

```
"react-native": "0.46.0",
    "appcenter": "^1.1.0",
    "appcenter-analytics": "^1.1.0",
    "appcenter-crashes": "^1.1.0",
```

My iOS path was on the normal path, not a custom one.

**Comment by TroubleMakerBen** [comment]
Hey @veb,
sorry to hear that. We'd love if you have another look at App Center again. Please don't hesitate to get in touch here or through Intercom (blue button on the bottom right corner in the App Center portal. We promise to respond quicker.

Best,
Benjamin
