### ISSUE TITLE
Error building new empty project wit ReactNative for iOS

### ISSUE THREAD

**Issue by berzinsk** [Microsoft/AppCenter-SDK-React-Native#219]
Hi.

I wan't to check out how does the AppCenter works with React Native.
I have created new project with react-native init `AppCenterTest`

Setup all the required provisioning profiles/certificates.

When I try to build the project via App Center it shows:

```
ld: library not found for -lPods-AppCenterTest
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have setup the project with cocoapods
I can run the project locally with `react-native run-ios` and it works fine. 
I can see the basic analytics stuff like number of sessions which means that everything is connected properly.
But the build fails via App Center.

Am I doing something wrong?

P.S. I am able to manually export the .ipa file from xcode

**Comment by dhei** [comment]
@berzinsk Can you open a support ticket via intercom (the blue button on the right corner of any page on appcenter.ms portal)? Please provide the App Center Build logs. We use this repo to track react native SDK specific issue.
