### ISSUE TITLE
Support Linking Custom Project Locations

### ISSUE THREAD

**Issue by RyanThomas73** [microsoft/appcenter-sdk-react-native#220]
Related: https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/137

**Issue:**
The pre/post scripts that are run as part of the `react-native link` command use hard coded paths and fail to find the project locations if they are different than the default `android/` and `ios/` located in the project root.

This prevents successful linking. In addition to this problem, the android scripts use `debug(..)` to log the error message so it is not apparent that a problem occurred and the documentation does not provide any details on how to link Android manually.

**Expected Behavior:**
The pre/post link scripts should use the same logic that react-native cli does in determining the project location. 
See: https://github.com/facebook/react-native/blob/master/local-cli/core/index.js

Additionally the android version of the scripts should display the errors above debug level so it is clear to the user that the link process was not actually completed successfully, and documentation for manual linking should be provided for users when they are unable to use the `react-native link` command.

**Comment by iamhitarth** [comment]
> the documentation does not provide any details on how to link Android manually.

Is there a way to link Android manually at the moment?

**Comment by ajwhite** [comment]
Always, if it's not detailed on the project README, then you can always follow the script by hand.

Any linkable project that has automated steps involve will [define the configuration and script files in the package file](https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/98579b4ae5681ec3da881a3fc5ac825d6ed0db10/appcenter/package.json#L23-L31).

That can be found [here](https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/0f1ccf8e446cdb3214dcca47ef59c96386913a24/appcenter-link-scripts/src/android/index.js).

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
