### ISSUE TITLE
Nothing being sent from iOS devices

### ISSUE THREAD

**Issue by ekimlinger** [Microsoft/AppCenter-SDK-React-Native#223]
### Versions:
From package.json:
    "react-native": "0.51.0",
    "appcenter": "^1.0.1",
    "appcenter-analytics": "^1.0.1",
    "appcenter-crashes": "^1.0.1",
    "appcenter-push": "^1.0.1"

### Issue:
Since Dec 12, our app has been unable to send out analytics and crash information, and we are unable to figure out why. I know that there was a new version of the sdk released that day (v1.1.0), however after several attempts to rip out all appcenter modules and reinstall the newest version, there is no apparent change. 

The issue is only apparent on iOS devices, android works fine. I know it's not an issue with the online appcenter app itself because I connected a brand new project to the same appcenter hub, and it didn't work. Same goes for connecting our app to a new appcenter app.

There is no apparent http or https traffic coming from our app when attempting to send analytics at all, however it does not error when attempting to do so. 

I have attempted everything from unlinking the project via `react-native unlink appcenter` | `appcenter-analytics` ...etc, and relinking with no luck. I have tried the manual installation of the SDK from https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#4-troubleshooting with no success. Same goes for reinstalling pods using `pod clean` and `pod install`

Any help would be much appreciated!

**Comment by guperrot** [comment]
Hi, we would need the logs printed by the SDK on the Console to be able to troubleshoot this issue.

Please follow these steps:

- Check that `AppDelegate.m` contains the App Center that we inject when you run `react-native link`, you should see the headers and this kind of code:

   ```
  NSURL *jsCodeLocation;

  [AppCenterReactNativePush register];  // Initialize AppCenter push

  [AppCenterReactNativeCrashes register];  // Initialize AppCenter crashes

  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:true];  // Initialize AppCenter analytics

  [AppCenterReactNative register];  // Initialize AppCenter 
   ```
   
   Or slightly different code based on the prompt answers.
 
- Check you have an ios workspace correctly referencing our Cocoa pods dependencies.
- Check the workspace correctly references the `AppCenter-Config.plist` file and that this file contains the right app secret.

If integration looks fine, add client side verbose logging to the code so we can troubleshoot:

- Open `AppDelegate.m` and add `@import AppCenter;` at the top with other include statements.
- Add `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before the first AppCenter call that was made (like before `NSURL *jsCodeLocation;`).
- Run your app in debug with these changes.
- Do not use `react-native log-ios` it's broken https://github.com/facebook/react-native/issues/9441
- To get logs, use the built-in `Console` application, select the simulator or plugged usb iphone/ipad that you are testing on, and add as a filter `AppCenter` and extract all the logs.
- Alternatively, run the app from `XCode` so that logs are shown in application output.
- Copy the `AppCenter` logs to a gist and link it here.

**Comment by ekimlinger** [comment]
Hi, thank you for the quick response. 

The `AppDelegate.m` file under our target that looks like:
```
#import "AppDelegate.h"
#import <Appcenter/MSAppCenter.h>
#import <AppCenterReactNativePush/AppCenterReactNativePush.h>
#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
#import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNative/AppCenterReactNative.h>

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  [MSAppCenter setLogLevel: MSLogLevelVerbose]; // Log for Appcenter

  [AppCenterReactNativePush register];  // Initialize AppCenter push

  [AppCenterReactNativeCrashes register];  // Initialize AppCenter crashes

  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:false];  // Initialize AppCenter analytics

  [AppCenterReactNative register];  // Initialize AppCenter
```

I'm assuming that you meant to write `#import <Appcenter/MSAppcenter.h>` instead of `@import AppCenter;` because that doesn't compile. 

Our xcconfig file looks like so, which I think means that they are being properly referenced. (Other pods seem to be working just fine):
```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/AppCenter/AppCenter-SDK-Apple/iOS" "${PODS_ROOT}/AppCenterReactNativeShared/AppCenterReactNativeShared" "${PODS_ROOT}/../../node_modules/@mapbox/react-native-mapbox-gl/ios"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AppCenter" "${PODS_ROOT}/Headers/Public/AppCenterReactNativeShared" "${PODS_ROOT}/Headers/Public/CodePush" "${PODS_ROOT}/Headers/Public/React" "${PODS_ROOT}/Headers/Public/appcenter" "${PODS_ROOT}/Headers/Public/appcenter-analytics" "${PODS_ROOT}/Headers/Public/appcenter-crashes" "${PODS_ROOT}/Headers/Public/appcenter-push" "${PODS_ROOT}/Headers/Public/react-native-mapbox-gl" "${PODS_ROOT}/Headers/Public/yoga"
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
LIBRARY_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/CodePush" "$PODS_CONFIGURATION_BUILD_DIR/React" "$PODS_CONFIGURATION_BUILD_DIR/react-native-mapbox-gl" "$PODS_CONFIGURATION_BUILD_DIR/yoga"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AppCenter" -isystem "${PODS_ROOT}/Headers/Public/AppCenterReactNativeShared" -isystem "${PODS_ROOT}/Headers/Public/CodePush" -isystem "${PODS_ROOT}/Headers/Public/React" -isystem "${PODS_ROOT}/Headers/Public/appcenter" -isystem "${PODS_ROOT}/Headers/Public/appcenter-analytics" -isystem "${PODS_ROOT}/Headers/Public/appcenter-crashes" -isystem "${PODS_ROOT}/Headers/Public/appcenter-push" -isystem "${PODS_ROOT}/Headers/Public/react-native-mapbox-gl" -isystem "${PODS_ROOT}/Headers/Public/yoga"
OTHER_LDFLAGS = $(inherited) -ObjC -l"React" -l"c++" -l"react-native-mapbox-gl" -l"sqlite3" -l"stdc++" -l"yoga" -l"z" -framework "AppCenter" -framework "AppCenterAnalytics" -framework "AppCenterCrashes" -framework "AppCenterPush" -framework "AppCenterReactNativeShared" -framework "CoreTelephony" -framework "Foundation" -framework "JavaScriptCore" -framework "Mapbox" -framework "SystemConfiguration" -framework "UIKit" -weak_framework "UserNotifications"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```


The only real output from the console that I'm getting looks like so: 
```
index.ios.bundle:14849 Module AppCenterReactNativePush requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.


index.ios.bundle:14849 Module AppCenterReactNativeCrashes requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

**Comment by ekimlinger** [comment]
Found it. It seems that when merging in another branch one of our developers had removed the reference to the `AppCenter-Config.plist` file from our `project.pbxproj` configuration. 
Thank you for the help @guperrot !

**Comment by guperrot** [comment]
You're welcome, thanks for using App Center @ekimlinger.
