### ISSUE TITLE
What does the FCM acronymn stand for?

### ISSUE THREAD

**Issue by nsarafa** [Microsoft/AppCenter-SDK-React-Native#224]
The documentation states `We use APNs for iOS apps and FCM for Android` in reference to push notifications. Does this mean `Firebase Cloud Messenger`?

**Comment by dhei** [comment]
@nsarafa FCM stands for Firebase Cloud Messenger. 

Note that starting from [v1.1.0 release](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.1.0), the Firebase SDK dependency is actually optional (as stated from release notes):

> [Android] The Firebase SDK dependency is now optional. If Firebase SDK is not available at runtime, the push registers and geerate notifications using only App Center SDK. The Firebase application and servers are still used whether the Firebase SDK is installed into the application or not. The SDK is still compatible with Firebase packages. But if you don't use Firebase besides App Center, you can now remove these packages and refer to the updated getting started instructions to migrate the set up. Migrating the push set up in the application remains optional.
