### ISSUE TITLE
Not using CocoaPods but trying to install pods in build

### ISSUE THREAD

**Issue by jlemm45** [Microsoft/AppCenter-SDK-React-Native#227]
I have no Podfile included in my project or a Pods folder but yet it still tries to run a pod install in the build steps and fails.

![screen shot 2018-01-24 at 3 02 16 pm](https://user-images.githubusercontent.com/4922365/35356950-98d7cf22-0117-11e8-97f5-1a32a35581f1.png)

**Comment by dhei** [comment]
Hi @jlemm45,

Can you create an intercom ticket (the blue button on appcenter.ms portal) so that we can get back to you? We use this repo to track React Native SDK specific issues and intercom for other services.
