### ISSUE TITLE
Minimum supported React Native version

### ISSUE THREAD

**Issue by ajwhite** [Microsoft/AppCenter-SDK-React-Native#228]
Is there a minimum supported version of React Native that will be set with this new SDK?

I see [0.48.3](https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter/package.json#L43) in the package file. Is this chosen particularly for compatibility reasons, or did it just happen to be the latest version when the project originated?

**Comment by guperrot** [comment]
The minimum version is documented in https://docs.microsoft.com/en-us/appcenter/sdk/ and is version 0.34.

**Comment by ajwhite** [comment]
Thank you
