### ISSUE TITLE
fatal error: 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by jdnichollsc** [Microsoft/AppCenter-SDK-React-Native#229]
Hi guys,

I'm getting the following issue after execute `react-native link react-native-code-push && react-native run-ios`:
```
/Users/jdnichollsc/myApp/node_modules/react-native-code-push/ios/CodePush/CodePush.h:6:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import "React/RCTEventEmitter.h"   // Required when used as a Pod in a Swift project
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


** BUILD FAILED **

The following build commands failed:
        CompileC /Users/jdnichollsc/myApp/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CodePush.build/Objects-normal/x86_64/CodePushDownloadHandler.o /Users/jdnichollsc/myApp/node_modules/react-native-code-push/ios/CodePush/CodePushDownloadHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```
**Info:**
react-native-cli: 2.0.1
react-native: 0.52.1

What do you think? Thanks in advance!

**Comment by guperrot** [comment]
Hi, this repository is the for the App Center React Native SDK only and Code Push developers will not see this ticket.

Please either create the issue on https://github.com/Microsoft/code-push or better, create the issue using the blue chat button to get a better response time.

**Comment by jdnichollsc** [comment]
Ohh perfect, thanks for the clarification @guperrot! 👍
