### ISSUE TITLE
Crash attachments not working in Android

### ISSUE THREAD

**Issue by henninghall** [Microsoft/AppCenter-SDK-React-Native#245]
Crashes are showing up like they should in Appcenter Crash section for both Android and iOS version but the crash attachment is missing in the android version. 

My code:

```
Crashes.setListener({

    getErrorAttachments(report) {
        const textAttachment = ErrorAttachmentLog.attachmentWithText('Hello text attachment!', 'hello.txt');
        return [textAttachment];
    }

});
```

Appcenter crash page for Android keeps saying: 
```
With App Center SDK you can attach custom data to your reports so that you can better understand the context of when your app crashed.
Follow SDK instructions to learn how to pass variables or attach files to your report.
```

- I have tried both the code above and the async version.
- Using version 1.2.0 
- I have not tried to attach a binary instead.

Any ideas of why the android attachment isn't being sent or displayed?

**Comment by TroubleMakerBen** [comment]
Hi Henning,

thx for getting in touch.

I'm able to repro the issue. While we work on fixing this, can you try 
```
const foobar = [ErrorAttachmentLog.attachmentWithText(`Hello my love, no asyc, use const foobar, array at end!`, 'hello.txt')];
return foobar;
```
this fixes it for me.

Best,
Benjamin

**Comment by TroubleMakerBen** [comment]
Update: I'll update our docs to reflect this change.

**Comment by henninghall** [comment]
@TroubleMakerBen Thanks for looking into it! I tried your suggestion but I didn't get it to work. Please let me know if there is anything else I can do.

**Comment by guperrot** [comment]
@henninghall is the listener actually called for you? you need this in **strings.xml**: `<string name="appCenterCrashes_whenToSendCrashes" moduleConfig="true">ASK_JAVASCRIPT</string>`

If the value is instead `ALWAYS_SEND`, then it will not work, that's based on the prompt we document.

Can you double check that strings file? You can change the value directly there if needed.

**Comment by henninghall** [comment]
@guperrot There we got it! Changed the value to `ALWAYS SEND` and it worked. It's possible that the issue came from the fact that i run `react-native-link` twice, first with the automated settings and later with the `enable in javascript`. I haven't verified this though. Since the crash attachment worked on iOS I assumed that the second linking worked. I should have checked the string value. Thanks a lot for looking into this!

**Comment by guperrot** [comment]
The Android prompt is not displayed on running `react-native link` a second time, this is a design issue in react native itself, but we just re-implemented the prompt without the built in model so that we can fix another bug and prompt every time.

**Comment by hoaphuong1311** [comment]
I have a issue attach file sqlite send to report crash app center on android
It's work on android device android 5  but not work on device android 7 
 
               ErrorAttachmentLog textLog = ErrorAttachmentLog.attachmentWithText(stringBuilder.toString(), "LogInfo.txt");
                ErrorAttachmentLog databaseLog = ErrorAttachmentLog.attachmentWithBinary(convertDataBaseToBinary(), "Ezyhaul.db", "application/octet-stream");
                return Arrays.asList(textLog, databaseLog);

Help me fix it

**Comment by jwallra** [comment]
Hi @hoaphuong1311, we'll address your question in the (other issue)[https://github.com/Microsoft/AppCenter-SDK-Android/issues/755] you've opened.  Your issue seems unrelated to this thread, so we'll address it in the new one.
