### ISSUE TITLE
iOS build always fails on Appcenter

### ISSUE THREAD

**Issue by rohan-jansen** [Microsoft/AppCenter-SDK-React-Native#249]
Hi there,

After adding the build configuration, and trying to build the project, it always fails to finish the process?

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/********ermobileapp-hakpaikemjfecsdwdtmbsitwmhji/Build/Intermediates.noindex/ArchiveIntermediates/********ermobileapp\ 2\ 2/IntermediateBuildFilesPath/RNVectorIcons.build/Release-iphoneos/RNVectorIcons.build/Objects-normal/armv7/RNVectorIconsManager.o RNVectorIconsManager/RNVectorIconsManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by dhei** [comment]
Hi @rohan-jansen, is this Xcode build failure local or on appcenter.ms? 

We use GitHub Issues only to track bugs, so can you please send us the complete build logs via our official support channel intercom (the blue button on the right corner on the appcenter.ms portal)?

**Comment by guperrot** [comment]
Hi, yes this support channel is only for the analytics/crashes/push SDKs for React Native. Build team is monitoring only intercom which can be accessed from any page of https://appcenter.ms via the blue chat button.

**Comment by guperrot** [comment]
Hey! 

We haven't heard from you in a while, so I am going to go ahead and close this conversation. Should you still have any questions, please don't hesitate to contact us again. 

Thanks for using App Center!

**Comment by TroubleMakerBen** [comment]
Hey @Msspl-PrashenjeetRoy,

Can you get in touch through our support system (blue button at the bottom right corner on the App Center portal), please?
This doesn't sound like an SDK issue to me + we might need more logs for this.

**Comment by Msspl-PrashenjeetRoy** [comment]
Yes i havr contacted them nd provided them with logs info.

**Comment by TroubleMakerBen** [comment]
@Msspl-PrashenjeetRoy thank you.

**Comment by krystiansliwa** [comment]
Hi, I also have that problem. On my Mac I can build archive but when I upload it to AppCenter archiving fails. It affects only iOS for Android it just works. 
I also use custom build types

**Comment by alberss** [comment]
Same as @krystiansliwa :(

**Comment by krystiansliwa** [comment]
@alberss For me now it works with the newest version of AppCenter. But I need to disable Bitcode for iOS

**Comment by alberss** [comment]
Unfortunately, it doesn't fix my build on AppCenter. I'll look for a solution. @krystiansliwa thanks!

**Comment by dhei** [comment]
Hey @alberss, can you get in touch through our support system (blue button at the bottom right corner on the App Center portal) with logs? This repo is only tracking app center SDK issues.

**Comment by alberss** [comment]
Sure @dhei !

**Comment by Sunnysh123** [comment]
can anyone Please help me with this build fail, working fine in locally but build is failing :(

 clang: error: no such file or directory: '/Users/vsts/Library/Developer/Xcode/DerivedData/fniwjcpzpcffvgffusvezdykuppc/Build/Products/Release-iphoneos/libBVLinearGradient.a'
2018-05-03T22:01:48.1560960Z ** BUILD FAILED **
2018-05-03T22:01:48.1587490Z The following build commands failed:
2018-05-03T22:01:48.1756820Z ##[error]Error: /usr/bin/xcodebuild failed with return code: 65
2018-05-03T22:01:48.1853300Z ##[section]Finishing: Build iOS (Test)


Thanks in Advance

**Comment by elamalani** [comment]
@Sunnysh123 Can you open a support ticket with us by clicking on the blue icon on the lower right corner of App Center portal?

**Comment by guperrot** [comment]
We use this repository only for tracking issues about using the AppCenter SDK for React Native.

For any App Center build issues that are not caused by integrating the SDK, please create a support ticket using the blue chat button on the App Center portal.

If you have a build issue caused by the SDK, please create a new ticket either on App Center portal or on this repository but as a new ticket using the template.
