### ISSUE TITLE
Unable to get device token

### ISSUE THREAD

**Issue by giladno** [microsoft/appcenter-sdk-react-native#263]
There is no matching listener for didRegisterForRemoteNotificationsWithDeviceToken. There is no option to access the current device token.

**Comment by guperrot** [comment]
There is no getter in the SDK to do that but in the meantime you can you can probably access the token manually by implementing that app delegate callback.

We use method swizzling on iOS so people don't have to implement AppDelegate themselves, but to intercept the push token you can folow https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#disable-automatic-forwarding-of-application-delegates-methods-to-app-center-services to disable method swizzling, implement app delegate yourself and make sure you call our SDK in each method like documented in that page.

**Comment by peterp** [comment]
@guperrot In my case I want to associate the token against a user in my app, so that I can send them a push notification directly.

**Comment by guperrot** [comment]
@peterp with App Center you can use [App Center REST API](https://docs.microsoft.com/en-us/appcenter/push/pushapi#send-notifications-to-device-ids) to push using AppCenter install identifier instead.

**Comment by DmitriyKirakosyan** [comment]
App Center Push [has been removed](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400) since version 4.0.0, so I'm closing this issue.
