### ISSUE TITLE
Android issue tapping notification received with app in background

### ISSUE THREAD

**Issue by nachofregeiro** [Microsoft/AppCenter-SDK-React-Native#267]
On Android when receiving a push notification with the app in background and leaving the device locked for 5-10 minutes, when you come back and tap on the notification the listener does not process the notification in the onPushNotificationReceived. If you tap it as soon as you get the notification it does work.

Environment:
  OS: Windows 10
  Node: 9.4.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

**Comment by dhei** [comment]
Hi @nachofregeiro, thanks for reporting. What's the android OS version and appcenter sdk version?

**Comment by dhei** [comment]
@nachofregeiro I was having a hard time to repro this issue. I send a push notification and leave the app in background for 10 minutes. When I tap the notification from system notification center, it looks like `onPushNotificationReceived` is called and executed as expected. Am I missing something or there's something special in your app?

**Comment by nachofregeiro** [comment]
I tried on Android 7.1.1 and 6.0.1. appcenter-push v1.4.0

**Comment by dhei** [comment]
@nachofregeiro I tried again, appcenter-push v1.4.0 works fine when "app in background and leaving the device locked for 5-10 minutes" on Android 8 (emulator) and Android 6.0.1 (real device). I verified it works when the app was running in background or killed in the background. 

Do you mean that after 5-10 minutes, tapping the notification from system notification center doesn't do anything but still launches your app? Can you provide more information of the behavior?

Also, do you consistently observe this issue? If so, can you provide a repro?

**Comment by guperrot** [comment]
Hey! 

We haven't heard from you in a while, so I am going to go ahead and close this conversation. Should you still have any questions, please don't hesitate to contact us again. 

Thanks for using App Center!
