### ISSUE TITLE
Manually linked appcenter not packing properly

### ISSUE THREAD

**Issue by zzorba** [Microsoft/AppCenter-SDK-React-Native#273]
I followed the instructions to link the appcenter library manually, despite the strong warnings at https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-manually.  We are not currently using CocoaPods, and would rather not start at this point in time.

At first it seemed like the project was working properly (we were able to deploy a build to AppCenter), but when we added the appcenter-crashes module our package would no longer archive (either in appcenter or in xcode).

I'm getting this error: 
`.../nativeapp/node_modules/appcenter-crashes/ios/AppCenterReactNativeCrashes/AppCenterReactNativeCrashesUtils.m:3:9: Module 'AppCenterCrashes' not found`

Which seems to correspond to this line of code:
`@import AppCenterCrashes.MSErrorReport;`

The problem (as far as I can make out), seems to be that the npm controlled `node_modules/appcenter-crashes/ios/AppCenterReactNativeCrashes.xcodeproj` has its framework search path set only to look for frameworks in the `$(SRCROOT)/../../../ios/Pods` folder.  Which would be great if I was using CocoaPods.  And while I could edit this, the changes wouldn't be committed since this lives in node_modules.

Is there some workaround for this that I've missed, or is CocoaPods effectively required at this point?

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.2.0
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.54.2 => 0.54.2

**Comment by zzorba** [comment]
And of course, as soon as I posted this I came up with a possible solution:

If instead of calling the folder with 3rd party dependencies 'Vendor' I name it 'Pods' it is able to archive/build.  But that doesn't seem like a great solution?

**Comment by achocron** [comment]
Sorry about the delay!

It seems to me that fixing this is just a matter of adding the `Vendor` folder to framework search paths (while leaving `Pods` as is) in the `xcodeproj` files that we use. I'll investigate this a bit more and get back to you.

**Comment by guperrot** [comment]
We will include a fix to search for Vendor folder in the next release, but in the meantime, you can rename Vendor folder as Pods like you already found out.

**Comment by zzorba** [comment]
Thanks!

**Comment by krystiansliwa** [comment]
When do you plan to release version with that fix?

**Comment by guperrot** [comment]
A release is coming soon @krystiansliwa @zzorba  However if you already integrated the SDK then the linking process will likely not reevaluate every link steps (react-native is skipping steps the second time, it's not our SDK) so the search path will most likely still be missing after the SDK update in your app. You can already fix your project now by adding the framework search path `"$(SRCROOT)/../../../ios/Vendor/**"` in your XCode project.

**Comment by krystiansliwa** [comment]
Hi, sorry for spamming but what is the status of release? Linking problem is currently blocker for me. I need to decide if I will use AppCenterSDK or Crashlytics this week. 
I saw also that there is new version of AppCenter Apple SDK, new release will use that one?

**Comment by dhei** [comment]
@zzorba @krystiansliwa App Center React Native v1.5.0 is released with fix of this issue. I am going to close this issue for now, but feel free to re-open it if the issue still exists.
