### ISSUE TITLE
Error: The logging tag can be at most 23 characters, was 27

### ISSUE THREAD

**Issue by apolishch** [Microsoft/AppCenter-SDK-React-Native#279]
### **Description**

```
React Native Appcenter fails gradle lint. Particularly the following issues:
 /Users/me/github/flock-react-app/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/crashes/AppCenterReactNativeCrashesUtils.java:21: Error: The logging tag can be at most 23 characters, was 27 (AppCenterReactNativeCrashes) [LongLogTag]
          Log.e(LOG_TAG, message);
                ~~~~~~~
  /Users/me/github/flock-react-app/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/crashes/AppCenterReactNativeCrashesUtils.java:25: Error: The logging tag can be at most 23 characters, was 27 (AppCenterReactNativeCrashes) [LongLogTag]
          Log.i(LOG_TAG, message);
                ~~~~~~~
  /Users/me/github/flock-react-app/node_modules/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/crashes/AppCenterReactNativeCrashesUtils.java:29: Error: The logging tag can be at most 23 characters, was 27 (AppCenterReactNativeCrashes) [LongLogTag]
          Log.d(LOG_TAG, message);
```

Looking into the code here: https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/appcenter-crashes/android/src/main/java/com/microsoft/appcenter/crashes/AppCenterReactNativeCrashesUtils.java#L18, the problem is failry obvious, 'AppCenterReactNativeCrashes' is longer than 23 characters long!

While I haven't gotten that far, I believe this will be a real problem in production as documented here:
https://developer.android.com/reference/android/util/Log.html#isLoggable(java.lang.String,%20int)

### **Repro Steps**

Create android app
Run ./gradlew lint with default settings

### **Details**

1. Which SDK version are you using?
    - 1.5.0
2. Which OS version did you experience the issue on?
    - Android 8.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. Google Pixel 2 emulator
4. What third party libraries are you using?
    - various
5. Run the following command and paste the output below: `react-native info`
```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.4
  Yarn: 1.5.1
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

**Comment by dhei** [comment]
Hi @apolishch,

Thanks for getting in touch. This looks like a bug and we have an item in backlog for tracking this. We will update the thread once the fix is released. Sorry for the inconvenience.

**Comment by dhei** [comment]
Hi @apolishch,

As a follow up, sdk v1.5.1 is released today and this issue should be fixed.

Thanks.
