### ISSUE TITLE
Enable silent notifications without prompting the user

### ISSUE THREAD

**Issue by hakonk** [microsoft/appcenter-sdk-react-native#297]
I'm using App Center and the App Center SDK for React Native to receive push messages in on both Android and iOS. 

After reading the integration guide and integrating App Center in a React Native app, it seems it's only possible to register for push notifications by presenting the standard user prompt that grants the push notification capabilities to the app. However, is there a way of registering for push notifications without also registering for `UNAuthorizationOptionAlert`, `UIUserNotificationTypeBadge`, or `UIUserNotificationTypeSound` (or the Android equivalent) such that the user does not have to make a choice so early on in the app life cycle?

I had a look at the iOS implementation for push notifications in https://github.com/Microsoft/AppCenter-SDK-Apple. To me, at `MPush.m:215`, the declaration of `authOptions` indicates to me that this is not possible as the `UNAuthorizationOptions` is hardcoded. Please correct me if I'm wrong :)

Thanks in advance!

Regards

**Comment by hakonk** [comment]
Alright, thanks for answering quickly!

Regards,

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue since [App Center Push has been removed from the SDK in 4.0.0](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400).
