### ISSUE TITLE
 library not found for -lMixpanel

### ISSUE THREAD

**Issue by dragosroua** [Microsoft/AppCenter-SDK-React-Native#304]
### **Description**

The project compiles fine on local env, both on XCode and on `react-native run-ios`, but on AppCenter it crashes by telling Mixpanel is not found.

### **Details**

1. Which SDK version are you using?
    - 1.5.0
2. Which OS version did you experience the issue on?
    - iOS 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - emulator
4. What third party libraries are you using?
    - Mixpanel
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 6.10.2
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.4.0

**Comment by achocron** [comment]
Hey thanks for reaching out. Is the issue occurring at build time or runtime? Can you please provide some more details regarding the precise error you are getting?

**Comment by clpolet** [comment]
Hey! 

We haven’t heard from you in a while, so I am going to go ahead and close this ticket. Should you still have any questions, you can write a message here & that will reopen the issue; or if you prefer you can create a new issue. Please don’t hesitate to contact us again.

Thanks for using App Center!
