### ISSUE TITLE
after install appcenter..., react-native link gives no output

### ISSUE THREAD

**Issue by jbuschke** [Microsoft/AppCenter-SDK-React-Native#306]
### **Description**

When I create a new create-react-native-app and follow the appcenters getting started guide https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native the **react-native link** command doesnt ask for additional information (i.e. the app secret). Instead 
```
Scanning folders for symlinks in ...\my-app\node_modules (86ms)
[empty line]
```
Not sure if this is an appcenter sdk or react-native link issue.

### **Repro Steps**

create-react-app-native my-app
cd my-app
npm install appcenter appcenter-analytics appcenter-crashes --save
react-native link

output after last command:
```
 Scanning folders for symlinks in ...\my-app\node_modules (86ms)
 [empty line]
```

### **Details**

    "appcenter": "^1.5.0",
    "appcenter-analytics": "^1.5.0",
    "appcenter-crashes": "^1.5.0",
    "expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2"

`react-native info`
Environment:
  OS: Windows 10
  Node: 9.8.0
  Yarn: Not Found
  npm:  6.0.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ~0.55.2 => 0.55.4

**Comment by clpolet** [comment]
Hi @jbuschke,
Thanks for contacting us. The AppCenter RN SDK doesn't support apps created via `create-react-native-app` since the SDK contains native components. Though it might work with "ejected" apps unless you fall into issue #129.

**Comment by clpolet** [comment]
Hey! 

We haven’t heard from you in a while, so I am going to go ahead and close this issue. Should you still have any questions, you can write a message here & that will reopen the issue; or if you prefer you can create a new issue. Please don’t hesitate to contact us again.

Thanks for using App Center!

**Comment by jbuschke** [comment]
Can you point me into some direction of what "type" of react native apps are supported? I didnt find the docs too informative in this direction.
I assumed that create-react-native-app is similar popular to the create-react-app template and would definetly supported by your build pipeline...

**Comment by guperrot** [comment]
Hi, create-react-native-app is supported if you don't use Expo and run [eject](https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md).

**Comment by jbuschke** [comment]
thanks for clarifying! 
I was now  able to run 'npm run eject' and 'react-native link'

**Comment by acomito** [comment]
@clpolet Are you aware of a step-by-step guide for migrating an expo app to AppCenter? I'm guessing there are some interim details between ejecting and it working on AppCenter.

If there isn't anything like that yet, maybe I can put a repo or medium post together. So, if you have some suggested reading for me, that helps too!

**Comment by dhei** [comment]
Hey @acomito,
Thanks for getting in touch. 
We currently don't have a step-by-step guide for migrating. I haven't tried out myself, if you could put together a repo or blog post that would be awesome. You may check out Expo's FAQ [How do I add custom native code to my Expo project](https://docs.expo.io/versions/v27.0.0/introduction/faq#how-do-i-add-custom-native-code) if that helps.
