### ISSUE TITLE
Argument list too long: recursive header expansion ...

### ISSUE THREAD

**Issue by elnygren** [Microsoft/AppCenter-SDK-React-Native#307]
When are we getting a fix released?

https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/209
https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/246
https://github.com/Microsoft/AppCenter-SDK-React-Native/pull/290

Edit: btw. the problem, at least for me, is definitely when React is installed in Pods dir, there are just too many files to go through recursively as React brings a little something called node_modules into the play :) 

Also, you guys are definitely not the only ones to assume that `Pods/` stays small enough to search through recursively. https://github.com/tinycreative/react-native-intercom/issues/202

**Comment by dhei** [comment]
Hey @elnygren,

Thanks for getting in touch. We are shipping next version that contains #290 which fixes #209 and #246 probably in new few days. Thanks for your patience.

**Comment by kdela** [comment]
Does anyone know which is the last version where this error not occur? I can't setup RN project through this error

**Comment by dhei** [comment]
Hey @kdela @elnygren,

As a follow up, sdk v1.5.1 is released today and the issue should be fixed.

Thanks.
