### ISSUE TITLE
android app does not show js stack trace on crash

### ISSUE THREAD

**Issue by macrozone** [Microsoft/AppCenter-SDK-React-Native#325]
### **Description**

In the crashlogs, i see the actual error that happened, but no js stacktrace. Instead, i see the java stack trace

### **Repro Steps**

1. build app for production
2. have a js crash, e.g. access property of undefined

### **Details**

1. Which SDK version are you using?
    - 1.5.0
2. Which OS version did you experience the issue on?
    - Android 6.0 and android 8.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - multiple actual devices
4. What third party libraries are you using?
    - react-native-maps
5. Run the following command and paste the output below: `react-native info`

```

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

```

My crashlogs look like this:

```
com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError
ExceptionsManagerModule.java - line 54
com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'this.map.setNativeProps')
com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError ExceptionsManagerModule.java:54
com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException ExceptionsManagerModule.java:38
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:372
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:160
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java
android.os.Handler.handleCallback Handler.java:739
android.os.Handler.dispatchMessage Handler.java:95
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java:29
android.os.Looper.loop Looper.java:148
com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run MessageQueueThreadImpl.java:192
java.lang.Thread.run Thread.java:818
```

while `undefined is not an object (evaluating 'this.map.setNativeProps')` is the actual error, i don't see any js stack trace, which would be crucial to be able to fix this error.

**Comment by dhei** [comment]
Hey @macrozone,

Thanks for getting in touch. Currently we only support source map on React Native iOS but not React Native Android, and I don't have an ETA of it. #208 is tracking this feature request.

**Comment by dhei** [comment]
close due to duplication and use #208 for tracking the feature request.
