### ISSUE TITLE
Unable to build app after attempting to add AppCenter multiple ways

### ISSUE THREAD

**Issue by creedmangrum** [Microsoft/AppCenter-SDK-React-Native#334]
### **Description**

Hi there. I'm looking forward to integrating the AppCenter into our app, but I am having some problems.

### **Repro Steps**

This is with

RN => 0.52
React => 16.2
AppCenterReactNative => 1.6
AppCenterIOS => 1.7.1

XCode 9.3

After running `react-native link` and then building the app I get errors in my `AppDelegate.m`

![screen shot 2018-06-21 at 4 38 19 pm](https://user-images.githubusercontent.com/16233247/41744364-91e0f71a-7571-11e8-8e9e-cab506058fc5.png)

I did find in one issue where it was suggested to remove the preceding part of the reference.

making

    #import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
    #import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
    #import <AppCenterReactNative/AppCenterReactNative.h>

into

    #import <AppCenterReactNativeCrashes.h>
    #import <AppCenterReactNativeAnalytics.h>
    #import <AppCenterReactNative.h>

which didn't do anything until I updated the `Header Search Paths`

![screen shot 2018-06-21 at 4 41 52 pm](https://user-images.githubusercontent.com/16233247/41744558-1a25964e-7572-11e8-9281-511881d4c661.png)

which then left me with this error...

![screen shot 2018-06-21 at 4 43 36 pm](https://user-images.githubusercontent.com/16233247/41744615-4f8be374-7572-11e8-8a75-bccb0d7749d5.png)

So after trying some things with that... I then started over and tried to bring it in manually. This strangely didn't give me any errors when I build at the end within XCode, the build just kept failing without telling me much. I tried to run from command line and was given...

    CompileC /Users/creedmangrum/roodat/roodat-native-ejected/ios/build/Build/Intermediates.noindex/AppCenterReactNative.build/Debug-iphonesimulator/AppCenterReactNative.build/Objects-normal/x86_64/AppCenterReactNative.o AppCenterReactNative/AppCenterReactNative.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### **Details**

1. Which SDK version are you using?
    - e.g. 1.6.0
2. Which OS version did you experience the issue on?
    - e.g. iOS 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. iPhone 7 simulator
4. What third party libraries are you using?
    - react-native-maps
    - react-apollo
    - react-navigation
    - react-native-auth0
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.6.0
  Yarn: 1.3.2
  npm: 4.1.2
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.52.0 => 0.52.3

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

Happy to provide more details if necessary

**Comment by acomito** [comment]
I'm also getting this issue using a fresh react-native init

**Comment by TroubleMakerBen** [comment]
Hi guys, I just tried a `react-native init` and added the latest version of our SDK and I don't run into any issue. One reason for this could be that I'm running a more current stack with Node 8, NPM 5, React-Native 0.56.
But before you guys upgrade your stack, can you check if you opened the `xcworkspace` to build the app?

**Comment by acomito** [comment]
I am slightly behind you.

```
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "appcenter": "^1.6.0",
    "appcenter-analytics": "^1.6.0",
    "appcenter-crashes": "^1.6.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-code-push": "^5.3.4"
  },
  "devDependencies": {
    "babel-jest": "23.0.1",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.1.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "./node_modules/appcenter/test/AppCenterMock.js",
      "./node_modules/appcenter-crashes/test/AppCenterCrashesMock.js",
      "./node_modules/appcenter-analytics/test/AppCenterAnalyticsMock.js"
    ]
  }
}
```


> But before you guys upgrade your stack, can you check if you opened the xcworkspace to build the app?

I think I recall this message in the terminal but wasn't 100% sure what to make of it. So we should open <root>/ios/<myproject>.xcworkspace in xcode rather than the xcodeproj?

**Comment by creedmangrum** [comment]
I have been using xcworkspace.

**Comment by creedmangrum** [comment]
Okay I was able to get this running by following the manual linking process [here](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) rather than what is in the AppCenter docs.

I'm not certain exactly what was different. The only thing I can glean at this point is that it skips optional step #3 from the AppCenter docs. I am going to start fresh and see if I can duplicate these results.

**Comment by acomito** [comment]
I'm still getting errors. What exactly did you need to change for step 3? I can't see anything wrong with the paths I have.

<img width="835" alt="screen shot 2018-06-22 at 7 06 44 am" src="https://user-images.githubusercontent.com/12701635/41773732-13c092c6-75eb-11e8-9273-7bbad4f7c260.png">

<img width="592" alt="screen shot 2018-06-22 at 7 06 29 am" src="https://user-images.githubusercontent.com/12701635/41773740-1801f35c-75eb-11e8-8a58-3ee4795eb9a3.png">

**Comment by dhei** [comment]
Hey @acomito,

Thanks for getting in touch. 

Since @creedmangrum mentioned manual linking, we have documentations on [manual linking App Center SDKs](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-manually) as well, maybe give it a try?

**Comment by TroubleMakerBen** [comment]
To answer questions above:

> So we should open /ios/.xcworkspace in xcode rather than the xcodeproj?

Yes!

**Comment by acomito** [comment]
Hey Guys, I started a new project and everything works great accept I ran into a hitch with react-native-code-push, which I had to link manually. If I can get more detail on where/when I ran afoul, I'll make a note or something to the docs. For now, I'm back on track.

**Comment by TroubleMakerBen** [comment]
glad to hear @acomito!

I'm closing this issue for now but please re-open/comment in case you have more questions or have a suggestion how we can improve the docs.

**Comment by ldco2016** [comment]
I would like to reopen this because I am getting behavior very similar to @creedmangrum and following the instructions he offered on creedmangrum commented on Jun 22, 2018 did not help me at all, its like I am going around in circles here.
