### ISSUE TITLE
'AppCenterCrashes/MSErrorReport.h' file not found

### ISSUE THREAD

**Issue by antonsivogrivov** [Microsoft/AppCenter-SDK-React-Native#335]
### **Description**

'AppCenterCrashes/MSErrorReport.h' file not found error when I try to build my iOS app

### **Repro Steps**

1. Manual link appcenter according to https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-manually
2. Run build

### **Details**

1. Which SDK version are you using?
    - 1.7.1
2. Which OS version did you experience the issue on?
    - iOS 11.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone SE
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.2.0
  react-native: ^0.53.0 => 0.53.3

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Don't use pods

**Comment by TroubleMakerBen** [comment]
Hey @antonsivogrivov,

Sorry to hear that you are running into issues. Unfortunately I cannot repro the issue on our end. Please check that
* you installed the AppCenter NPM packages
* you have added the different .frameworks to your project as well as the various projects
* you have added the appropriate .xcproject files to your app's project
* you have added the header search paths

**Comment by antonsivogrivov** [comment]
Libraries folder:

![screen shot 2018-06-23 at 01 53 19](https://user-images.githubusercontent.com/8429960/41802296-7dbc16e4-7688-11e8-8ef9-bc561e059365.png)

Headers search paths:

![screen shot 2018-06-23 at 01 55 14](https://user-images.githubusercontent.com/8429960/41802315-98fa8990-7688-11e8-8c8a-08fbffcc3cf5.png)

Linked stuff:

![screen shot 2018-06-23 at 01 54 17](https://user-images.githubusercontent.com/8429960/41802301-8ece3a70-7688-11e8-83c5-8e9fe5b8cecc.png)

**Comment by antonsivogrivov** [comment]
@TroubleMakerBen, what do you mean when you say "you have added the different .frameworks to your project as well as the various projects"?

**Comment by antonsivogrivov** [comment]
And now I have 'AppCenter/AppCenter.h' file not found error. Don't understand what I'm doing wrong :(

**Comment by bmourat** [comment]
Seems like AppCenter frameworks import issue. Maybe you should try reimporting AppCenter frameworks.

**Comment by TroubleMakerBen** [comment]
Hey @antonsivogrivov,

I just recorded a "quick-and-dirty" screen recording where I integrate the SDK with manual linking. It's 11min long, feel free to play this at a faster speed. I hope that it helps you tracking down what goes wrong.

The recording can be downloaded from [here](https://www.dropbox.com/s/fkk9ag91golwg8c/Screencast-RN-Manual-Linking-480.mov?dl=0).

**Comment by pennyandsean** [comment]
This is a pain.  I got it working with a bit of help from the manual install [instructions](https://github.com/Microsoft/appcenter-sdk-react-native/releases/tag/1.6.0).

Without XCode open, I did a `yarn add appcenter appcenter-analytics appcenter-crashes` then a `react-native link`. Before opening xcode I then looked in the project's ios folder.  There are a bunch of AppCenter .framework files there, each one has a Headers and Modules subfolder, but with no files.

So I went and downloaded the [SDK](https://github.com/Microsoft/appcenter-sdk-react-native/releases/tag/1.6.0) and the [other frameworks](https://github.com/Microsoft/AppCenter-SDK-Apple/releases/tag/1.7.1) unzipped them into a folder called /Vendor/AppCenter in the project's ios folder.  I deleted the blank ones that were put into the ios folder from the (react-native link) installer.
Open XCode and it built.  

If you look at the Framework Search Path for the library you're getting the 'file not found' error on, you'll see its looking for the non-existant 'ios/Vendor' folder.  Hope that helps.  And I hope this issue is short-lived.

**Comment by andreialecu** [comment]
I have seen the same problem when running `react-native link` without having cocoapods installed. Leaving this here as it may help somebody.

**Comment by TroubleMakerBen** [comment]
@andreialecu have you been able to resolve your issue by installing CocoaPods?

**Comment by andreialecu** [comment]
Yes, installing CocoaPods and then running `react-native link` made this error go away and the app compiled properly. I believe it should be added to a FAQ. The error that CocoaPods is not installed is present in the log when running `react-native link`, but it is not very prominent, so it can be easy to miss.

**Comment by guperrot** [comment]
@andreialecu We updated the troubleshooting docs as you suggested: https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#build-error-such-as-appcentercrashesmserrorreporth-file-not-found.

**Comment by awchang56** [comment]
> Hey @antonsivogrivov,
> 
> I just recorded a "quick-and-dirty" screen recording where I integrate the SDK with manual linking. It's 11min long, feel free to play this at a faster speed. I hope that it helps you tracking down what goes wrong.
> 
> The recording can be downloaded from [here](https://www.dropbox.com/s/fkk9ag91golwg8c/Screencast-RN-Manual-Linking-480.mov?dl=0).

Follow this video exactly if you want to do manual linking. I was having issues and followed it exactly, even creating the vendor folder and everything and it works. 

RN: v0.57.1
AppCenter-SDK-React-Native: v1.8.1
AppCenter-SDK-Apple: v1.9.0
Platform: iOS
Xcode: v10

**Comment by eduardodcastro** [comment]
> Hey @antonsivogrivov,
> 
> I just recorded a "quick-and-dirty" screen recording where I integrate the SDK with manual linking. It's 11min long, feel free to play this at a faster speed. I hope that it helps you tracking down what goes wrong.
> 
> The recording can be downloaded from [here](https://www.dropbox.com/s/fkk9ag91golwg8c/Screencast-RN-Manual-Linking-480.mov?dl=0).

Thank you, I followed the video and it worked for me.

**Comment by ElektrojungeMS** [comment]
I'm glad the screen recording seemes to help. =)

**Comment by ProteanDev** [comment]
We've just confirmed, it's the missing ios/Vendor folder, you should make one and put everything you extracted there, or at least the frameworks you need
