### ISSUE TITLE
build error AppCenterReactNativeCrashes

### ISSUE THREAD

**Issue by vishnukalakota** [Microsoft/AppCenter-SDK-React-Native#342]
`Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.11.3
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 8.3.3 Build version 8E3004b
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

pod --version
1.5.3`

this error in this file AppCenterReactNativeCrashes.m 

<img width="1048" alt="screen shot 2018-06-28 at 8 01 57 pm" src="https://user-images.githubusercontent.com/13937443/42033107-568653de-7b0e-11e8-8f38-10e17e79c369.png">

**Comment by bmourat** [comment]
Hi @vishnukalakota 

Did you tried to run ```pod install``` manually? 
Could you please provide the contents of your podfile?

Best,
Murat

**Comment by bmourat** [comment]
Hi!

Could you confirm that AppCenterCrashes framework is located under this path:
Pods/AppCenter/Crashes/Frameworks/AppCenterCrashes.framework?
I see in your podfile workspace keyword, why do you need it? Isn't this the whole pod file?
Also, could you provide the following settings for AppCenterReactNativeCrashes project in Libraries folder of your workspace:
Framework Search Paths
Header Search Paths

Best,
Murat

**Comment by clpolet** [comment]
Hi there,

We haven't heard from you for a while, I'll go ahead and close the issue for now.

Best,
Clement
