### ISSUE TITLE
App Center Android build fails with Error: Not found wrapperScript

### ISSUE THREAD

**Issue by ashavyrin** [Microsoft/AppCenter-SDK-React-Native#345]
### **Description**
Android build fails with below error. The build generates fine outside of the App Center. Also the IOS generates fine in App Center.

==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 1.128.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613720)
==============================================================================
##[error]Error: Not found wrapperScript: /Users/vsts/agent/2.134.2/work/1/s/android/app/gradlew
##[section]Finishing: Gradle Task
##[section]Starting: Post Job Cleanup
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Press Build Now in App Center

### **Details**

1. Which SDK version are you using?
    1.6.0
2. Which OS version did you experience the issue on?
    N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    N/A
4. What third party libraries are you using?
    N/A
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

N/A

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

N/A

**Comment by MatkovIvan** [comment]
Hi @ashavyrin,
Thanks for getting in touch!

The `gradlew` file is required and it should be committed into your git repository. Please check if it was not accidentally added to gitignore rules. Also, if you recently moved this file to another location, please try to re-save the build configuration.

PS We use this repo to track react native SDK specific issue. For the portal or CI issue please create a ticket using the blue chat button on any page of the https://appcenter.ms portal instead.

Best,
Ivan

**Comment by ashavyrin** [comment]
This can be closed, thanks. Fixed by doing a Save & Build rather than Build Now.

**Comment by aGORyan** [comment]
How did you do a "Save & Build"?

I don't see anything like this in the UI.

**Comment by guperrot** [comment]
@aGORyan <img width="3" alt="screen shot 2018-09-07 at 12 37 37 pm" src="https://user-images.githubusercontent.com/623672/45239726-13671d80-b29b-11e8-8e68-5065ba0d3253.png">
