### ISSUE TITLE
iOS build fails with error code 65 - 'AppCenter/MSAppCenter.h' file not found

### ISSUE THREAD

**Issue by M00ker** [Microsoft/AppCenter-SDK-React-Native#346]
### **Description**

After adding the App Center SDK to my React Native project the MS App Center iOS build fails with the following error:

##[error]Error: /usr/bin/xcodebuild failed with return code: 65

/Users/vsts/agent/2.134.2/work/1/s/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m:21:9: fatal error: 'AppCenter/MSAppCenter.h' file not found
#import <AppCenter/MSAppCenter.h>

It builds and archives fine in XCode but the build fails in App Center.

Android project builds fine.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Following instructions for add App Center SDK using CocoaPods
2. Build in App Center

### **Details**

1. Which SDK version are you using?
    - 1.6.0
2. Which OS version did you experience the issue on?
    - iOS 11.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Build fails
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.2.1
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

[logs_23.zip](https://github.com/Microsoft/AppCenter-SDK-React-Native/files/2165690/logs_23.zip)

**Comment by clpolet** [comment]
Hi @M00ker,

Thanks for contacting us. 
It feels like App Center Build doesn't found the App Center SDK dependency for your application.  AC Build needs you to commit your Pods repository so it can access your pod dependencies, can you please double check that your Pods folder is committed?

PS We use this repo to track react native SDK specific issue. For the portal or CI issue please create a ticket using the blue chat button on any page of the https://appcenter.ms portal instead. 

Regards,
Clement

**Comment by M00ker** [comment]
Thanks Clement,

Wasn't sure if this was a SDK issue or not, I'll create a ticket instead.

Just for anyone else reading this issue, the 'Pods' folder in my project wasn't tracked as it was excluded in my ,gitignore.  I've added it now and restarted the build.  It gets further but fails with:

ld: library not found for -lPods-FCW
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by clpolet** [comment]
No problem. I'll go ahead and close this issue.

**Comment by jonasostrom** [comment]
Any updates on this issue?
I can build my app with my local xcode but at App Center it fails:

ld: library not found for -lPods-MyAppNAme
code: 65

**Comment by guperrot** [comment]
@jonasostrom how is your .gitignore configured?

**Comment by jonasostrom** [comment]
```
# OSX
#
.DS_Store

# Xcode
#
build/
index/
*.pbxuser
!default.pbxuser
*.mode1v3
!default.mode1v3
*.mode2v3
!default.mode2v3
*.perspectivev3
!default.perspectivev3
xcuserdata
*.xccheckout
*.moved-aside
DerivedData
*.hmap
*.ipa
*.xcuserstate
project.xcworkspace

# Android/IntelliJ
#
build/
.idea
.gradle
local.properties
*.iml

# node.js
#
node_modules/
npm-debug.log
yarn-error.log

# BUCK
buck-out/
\.buckd/
android/app/libs
*.keystore

# fastlane
#
# It is recommended to not store the screenshots in the git repo. Instead, use fastlane to re-generate the
# screenshots whenever they are needed.
# For more information about the recommended setup visit:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Gitignore.md

fastlane/report.xml
fastlane/Preview.html
fastlane/screenshots
```

**Comment by guperrot** [comment]
@jonasostrom can you please run the following command *locally after building/running successfully*

`git ls-files -o -i --exclude-standard` inside the **ios** folder of your app and share the output? 

Please also make sure `git status` has nothing to be committed as AppCenter build takes a clean commit without your local changes.

**Comment by milesmatthias** [comment]
I'm seeing this issue building locally, not even building in App Center. The only commands I issued:

1. `npm install appcenter appcenter-analytics appcenter-crashes --save`
2. `react-native link`

Build fails.

3 App Center projects are added to my Xcode workspace: `AppCenterReactNative`, `AppCenterReactNativeAnalytics`, and `AppCenterReactNativeCrashes`, all 3 of which try to import `AppCenter/AppCenter.h` and they're all failing.

Is the repo or link command missing adding the `AppCenter` project?

I can see the [file in the iOS version](https://github.com/Microsoft/AppCenter-SDK-Apple/blob/develop/AppCenter/AppCenter/AppCenter.h) the AppCenter SDK, but I don't see it anywhere, or referenced anywhere, in the ReactNative version.

**Comment by guperrot** [comment]
@milesmatthias your issue looks different, and it's harder for us to monitor everything on 1 big thread, I would suggest you create a separate issue if you don't mind.

I have 2 questions to start the troubleshooting:

* Are you now opening xcworkspace instead of xcodeproj? Trying to build from xcodeproj will fail.
* What does react-native run-ios do in your case? Same build error?

Please reply on a separate issue and keep the template so we also have the basic info about your setup.

**Comment by milesmatthias** [comment]
@guperrot okay, opened https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/420

**Comment by guperrot** [comment]
@jonasostrom we have not heard from you for a while, if you still experience issues, please create a new issue using the template.
