### ISSUE TITLE
AppCenter Build does not support RN 0.56.0

### ISSUE THREAD

**Issue by acomito** [Microsoft/AppCenter-SDK-React-Native#348]
I have successful local builds (in xcode too) but fails in the appcenter cloud with this:

https://gist.github.com/acomito/f551b9c2db85cf8cc1f15fb5f48d91a0

```

  React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 30.86 MB / 8.00 GB
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 9.7.1 - /usr/local/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

**Comment by TroubleMakerBen** [comment]
Hey @acomito,

thanks for getting in touch. This is actually not an SDK issue. Currently AppCenter Build does not support RN 0.56.0 but the team is working on it.

I'm leaving this issue open for visibility.

**Comment by acomito** [comment]
@TroubleMakerBen appreciate the quick response! I was hoping it was something simple like that.

**Comment by janpieterz** [comment]
@TroubleMakerBen any rough idea for React Native 0.56 support? Are we talking next week, next month?

**Comment by TroubleMakerBen** [comment]
Hey @janpieterz,
This is actively being worked on and should be available later this month.

**Comment by declandowling** [comment]
https://github.com/facebook/react-native/issues/20167

React native 0.56 requires node 8 as a minimum, it has been in production for 10 days and was in RC for around a month before that, so hopefully this isn't something completely out of the blue to the app center team. 

Is the only solution here to wait for app center to support Node 8 as a minimum if wanting to use React Native 0.56?

...

While I'm aware it's nothing to do with the SDK, I wish there was a more public place to post about issues such as this rather than 
> please get in touch via Intercom (the blue button on the bottom right corner in the AppCenter portal).

**Comment by dhei** [comment]
Hey @declandowling, have you tried `npm install -g npm@8` in the [app center post clone script](https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone)?

**Comment by syq7970** [comment]
"Failed to execute aapt"
This is because targetSdkVersion is too low,  for android workaround just change appcenter and appcenter-analytics targetSdkVersion and compileSdkVersion to 26.

but hope merge this change by official.

**Comment by amhinson** [comment]
The node issue can be fixed by adding a `appcenter-post-clone.sh` with:

```
#!/usr/bin/env bash
set -ex
brew uninstall node@6
NODE_VERSION="8.9.4"
curl "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}.pkg" > "$HOME/Downloads/node-installer.pkg"
sudo installer -store -pkg "$HOME/Downloads/node-installer.pkg" -target "/"
```

This will just uninstall the version of Node App Center is currently using, and install Node 8.9.4 instead.

**Comment by ethanneff** [comment]
Release `1.7.0` is still broken. Still cannot build the SDK on Android with React Native 0.56.0.
https://github.com/Microsoft/AppCenter-SDK-React-Native/pull/359 may fix the issue?

Right now, I still have to hard code the changes to the appcenter/build.gradle, appcenter-analytics/build.gradle , appcenter-crashes/build.gradle files 
```sh
apply plugin: 'com.android.library'

def _ext = rootProject.ext
def _compileSdkVersion = _ext.has('compileSdkVersion') ? _ext.compileSdkVersion : 23
def _buildToolsVersion = _ext.has('buildToolsVersion') ? _ext.buildToolsVersion : '27.0.3'
def _minSdkVersion = _ext.has('minSdkVersion') ? _ext.minSdkVersion : 16
def _targetSdkVersion = _ext.has('targetSdkVersion') ? _ext.targetSdkVersion : 22

android {
    compileSdkVersion _compileSdkVersion
    buildToolsVersion _buildToolsVersion

    defaultConfig {
        minSdkVersion _minSdkVersion
        targetSdkVersion _targetSdkVersion
        versionCode 29
        versionName '1.5.1'
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:+'
    compile 'com.microsoft.appcenter:appcenter:1.6.1'

    // compile project(':AppCenterReactNativeShared')   // For testing with TestApp
    compile 'com.microsoft.appcenter.reactnative:appcenter-react-native:1.6.0'
}
```

**Comment by amhinson** [comment]
For the Android issues, I've also had to go in and change the `compileSkdVersion` from 23 to 26 on a handful of native dependencies in the node_modules, including App Center. As a helpful tool to make sure those changes stay in place, I use https://github.com/ds300/patch-package , which essentially patches the node_module each time they are installed. This pattern works for the time being while all of the libraries update to the new Android standards.

**Comment by jaelim-ms** [comment]
@ethanneff Can you uninstall appcenter packages and install it again? Looks the build.gradle file that you posted isn't 1.7.0.

**Comment by dhei** [comment]
Hi @ethanneff, 

App Center RN SDK v1.7.1 does works with RN 0.56.x. As @jaelim-ms pointed out, it appears that you're using v1.6.0 of [appcenter-react-native](https://bintray.com/vsappcenter/appcenter/appcenter-react-native) dependency that comes with v1.6.0 of App Center RN SDK:

```gradle
compile 'com.microsoft.appcenter.reactnative:appcenter-react-native:1.6.0'
```

Upgrade to v1.7.1 should address this issue.

**Comment by guperrot** [comment]
(Was closing the SDK bug as fixed, but we still need App Center build support, again this repository is only for SDK usually).

**Comment by dhei** [comment]
Hey folks,

We added the support of React Native **0.56.x** (with Xcode 9.4.1 for iOS) in App Center Build. No more [workaround like this](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/348#issuecomment-406651622) is needed anymore.

If your package.json contains RN 0.56+, then Node version on VM will select Node 8. In order to apply the new changes, you need to hit `Save` or `Save and Build` button to update build configurations in App Center portal.

FYI @acomito @ethanneff @declandowling @amhinson.

**Comment by wmalgadey** [comment]
> Hey folks,
> 
> We added the support of React Native **0.56.x** (with Xcode 9.4.1 for iOS) in App Center Build. No more [workaround like this](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/348#issuecomment-406651622) is needed anymore.

What if we need a specific node.js 8 version (8.10.0 to be specific), how can we uninstall node.js8 from post-clone script?

**Comment by dhei** [comment]
Hey @wmalgadey,

To install a specific version of Node, have you tried the workaround from https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/348#issuecomment-406651622?

**Comment by wmalgadey** [comment]
Yes, but this only deinstalls v6 of node.js. It downloads 8.10 (in my example) but still uses 8.12.

**Comment by ElektrojungeMS** [comment]
Hey @wmalgadey,

I think the issue you are seeing is that you are installing Node 8.10 but it doesn't use that version yet.As [this issue on SO](https://stackoverflow.com/questions/51716490/how-to-set-specific-version-of-node-as-default-using-n)explains, you might need to have to run `n` again after you installed Node 8.10.

**Comment by wmalgadey** [comment]
Hmm, I used the script from https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/348#issuecomment-406651622. There is no `sudo n` in this script, which can be run again :)

But I also tried to use `n`, which din't work neither. Still getting the error, that 8.12 is beeing used instead of 8.10.

**Comment by ElektrojungeMS** [comment]
Hey @wmalgadey,

Good news, there's a solution for you. Ever since App Center started to support RN 0.56.0, it's forcing node 8.12.0 per default.

Use this in you post clone script and you should be happy (verified this with a toy project of mine):


```bash
#!/bin/sh

# please specify required Node.js version
NODE_VERSION=8.10.0

# workaround to override the v8 alias
npm config delete prefix
. ~/.bashrc
nvm install "$NODE_VERSION"
nvm alias node8 "$NODE_VERSION"

```

Let me know how this goes!

**Comment by wmalgadey** [comment]
Is nvm installed by default? It is not mentioned on the documentation page https://docs.microsoft.com/en-us/appcenter/build/software. I will try, thank you for your efforts so far.

**Comment by ElektrojungeMS** [comment]
Hey Wolfgang, 

Did the workaround work?

To answer your question: While `nvm` should generally be available on the machines, it is only used as part of the provisioning process of the machines and not intended to be used or working in a way that allows customer's to use it and rely on it. Does that make sense?

Best,
Benjamin

**Comment by wmalgadey** [comment]
Ok, I didn't had the time to test it. We found a way to make our app compile with 8.12 :) So thanks for you efforts!

**Comment by ElektrojungeMS** [comment]
I'm glad things are working Wolfgang!
Don't hesitate to get in touch with us again! (If you do, please open an new issue here on GH or get in touch through our support - the blue floating button on the App Center portal)

**Comment by acollazomayer** [comment]
@ElektrojungeAtWork Hi, Im having troubles with the script. after I use it, it fails with NA/: "Version "N/A => N/A" is not yet installed.

**Comment by acollazomayer** [comment]
@ElektrojungeAtWork it fails in the select node version script

**Comment by evkhramkov** [comment]
Hello @acollazomayer,

Looks like you have some issue in script or in your app configuration, but that is not related to SDK.
Could you please reach out to App Center support (using blue intercom button in the right bottom) so we can closely look into your issue.
It would be much more convenient to help you with the access to build logs and script contents which you're using.

**Comment by baldursson** [comment]
Even though I'm using React 0.57.4, App Center wants to use node 6. The workaround provided by @amhinson worked perfectly until a days ago. Now App Center runs an additional script called "Select Node.js Version v2" (select-node-version.sh) that selects node 6 no matter what.

Any ideas?

**Comment by evkhramkov** [comment]
@baldursson you can set node version in build configuration instead of workaround scripts. By default it uses node v6

![image](https://user-images.githubusercontent.com/27571887/60038351-edafd700-9668-11e9-93e0-1b79b9c30f1d.png)

**Comment by baldursson** [comment]
Thank you @evkhramkov! I had no idea
