### ISSUE TITLE
please maintain changelog files

### ISSUE THREAD

**Issue by vonovak** [Microsoft/AppCenter-SDK-React-Native#371]
hi! thanks for the appcenter libs. I'm using the crashes service, and one thing that I look for when a new version of this package is made available, is a changelog. However, there isn't one available. I can go through the commits, but some commits are related to this service, other commits to that service - it's hard to tell what has changed between the versions that get released. Having a changelog would help a lot. Thanks.

**Comment by guperrot** [comment]
Hi, thanks for using App Center.
Our changelog is available via this link: https://github.com/Microsoft/AppCenter-SDK-React-Native/releases.

**Comment by vonovak** [comment]
ah, thanks, I was being blind

**Comment by guperrot** [comment]
No problem, it would be more convenient to have it available in a flat MD file and also linked to our docs so we understand the feedback actually.

**Comment by guperrot** [comment]
We know have a [changelog](https://github.com/Microsoft/AppCenter-SDK-React-Native/blob/develop/CHANGELOG.md) file in the repo to make it more convenient than using [releases](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases) view.
