### ISSUE TITLE
Push notifications appearing multiple times for Android users

### ISSUE THREAD

**Issue by martsie** [Microsoft/AppCenter-SDK-React-Native#372]
### **Description**

Our Android users are receiving push notifications multiple times, particularly those who have installed, uninstalled and re-installed the app. The way that Appcenter push works is that it registers push notifications automatically through native code - is it possible that users are being registered multiple times on the same device? If so how can we stop that from happening?

Also - does this mean we can't link push notification tokens to individual users? Eg a common use case could be to notify a specific user to say that somebody has liked their post.

### **Repro Steps**
1. Add Appcenter push to react-native project
2. Install and uninstall the app a few times on an Android device
3. Next time a push notification broadcast goes out, that Android device will be spammed with push notifications.

### **Details**
1. Which SDK version are you using?
    - 1.5.1
2. Which OS version did you experience the issue on?
    - Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical devices
4. What third party libraries are you using?
    - nothing that would influence push notifications
5. Run the following command and paste the output below: `react-native info`
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.4.0
  Yarn: 1.5.1
  npm: 5.10.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: ^0.54.0 => 0.54.2
```

**Comment by guperrot** [comment]
Hi, this problem was addressed in version [1.7.0](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.7.0), please update SDK to latest version (1.7.1 as of now) and then follow the migration steps: https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/react-native-android.

**Comment by debashistewary** [comment]
I am facing same problem in Android (AppCenter)
Please help me 

Thank you 
Debashis

**Comment by MatkovIvan** [comment]
Hi @debashistewary,

Please make sure you're using the latest SDK. If it's an issue of the latest version of the SDK, please open a new issue and fill out the template (versions, logs, etc).
