### ISSUE TITLE
Build error - 'React/RCTViewManager.h' file not found

### ISSUE THREAD

**Issue by tassock** [Microsoft/AppCenter-SDK-React-Native#374]
### **Description**

I'm trying to get my first successful build on App Center, but am experiencing the following error that I do not get building locally: 

```
CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/<redacted-my-app>/Build/Intermediates.noindex/ArchiveIntermediates/<redacted-my-app>/IntermediateBuildFilesPath/RCTImage.build/Release-iphoneos/RCTImage.build/Objects-normal/armv7/RCTImageViewManager.o RCTImageViewManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vsts/agent/2.136.1/work/1/s/node_modules/react-native/Libraries/Image
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin:/Library/Frameworks/Mono.framework/Versions/4/bin:/usr/local/bin:/usr/local/sbin:/Users/vsts/bin:/Users/vsts/.yarn/bin:/usr/local/go/bin:/Users/vsts/Library/Android/sdk/tools:/Users/vsts/Library/Android/sdk/platform-tools:/Users/vsts/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/vsts/.azcopy"
    /Applications/Xcode_9.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/vsts/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-lab...
In file included from /Users/vsts/agent/2.136.1/work/1/s/node_modules/react-native/Libraries/Image/RCTImageViewManager.m:8:
/Users/vsts/agent/2.136.1/work/1/s/node_modules/react-native/Libraries/Image/RCTImageViewManager.h:8:9: fatal error: 'React/RCTViewManager.h' file not found
#import <React/RCTViewManager.h>
```

In searching around for solutions, I came across [this](https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found) post that mentioned this issue. Per the accepted answer, "Parallelize Build" was already unchecked. I tried dragging React.xcodeproj from Libraries to the root project tree and adding 'React' as a target dependency, but the issue remained. 

Again, I'm only experiencing this build error on app center and not while building locally. Any advice on how to further debug this would be greatly appreciated! 

### **Repro Steps**

1. Followed [Getting Started With React Native](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native) guide using recommended CocoaPods installation. 
2. Followed [Building React Native apps for iOS](https://docs.microsoft.com/en-us/appcenter/build/react-native/ios/) and initiated a build. 

### **Details**

1. Which SDK version are you using?
    - Latest (1.7.1)
2. Which OS version did you experience the issue on?
N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
N/A
4. What third party libraries are you using?
  "dependencies": {
    "@redux-offline/redux-offline": "^2.3.3",
    "appcenter": "^1.7.1",
    "appcenter-analytics": "^1.7.1",
    "appcenter-crashes": "^1.7.1",
    "axios": "^0.18.0",
    "moment": "^2.22.2",
    "object-resolve-path": "^1.1.1",
    "react": "16.3.1",
    "react-native": "^0.55.4",
    "react-native-linear-gradient": "^2.4.0",
    "react-native-mplayer": "^1.0.1",
    "react-native-snap-carousel": "^3.7.0",
    "react-native-vector-icons": "^4.6.0",
    "react-native-video": "^2.0.0",
    "react-navigation": "^2.0.2",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.3.0",
    "redux-token-auth": "(private repo)",
    "remote-redux-devtools": "^0.5.12",
    "reselect": "^3.0.1"
  },

5. Run the following command and paste the output below: `react-native info`
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 10.4.0
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: Not Found
Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
1.5.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here: 
N/A

**Comment by achocron** [comment]
Hey - can you please post this question by using the blue Intercom chat button on `appcenter.ms` (it's in the bottom right corner). This will help get your question to our backend team. Thanks!
