### ISSUE TITLE
How to differentiate between user clicked notification and foreground notification for iOS (content-available not set)

### ISSUE THREAD

**Issue by buddhamangler** [Microsoft/AppCenter-SDK-React-Native#381]
Creating a new issue as was suggested to me since my old one was closed, which can be found here...

https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/375

Very similar, the suggestions from that issue solved my android issue.  But the iOS payload between automatically received event for foreground vs a user initiated click on a notification seems identical.  The documentation seems to imply that it is possible, but I can't quite tell how.  Thanks

### **Description**

I'm having trouble seeing how you can determine whether a notification was received while the app was in the foreground or not.  The behavior of the app is highly dependent on this information.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Send push notification via the portal
2. Debug application and see that there is no property for whether it was a user interaction or not

### **Details**

1. Which SDK version are you using?
    1.7.0
2. Which OS version did you experience the issue on?
    iOS 11.3 and 11.4.1
3. What device version did you see this error on?  Were you using an emulator or a physical device?
   iPhone 6 plus and iPhone 8
4. What third party libraries are you using?
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.1.0
  Yarn: 1.6.0
  npm: 6.2.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

**Comment by bmourat** [comment]
Hey @buddhamangler 

I think you can use [`AppState`](https://facebook.github.io/react-native/docs/appstate) to determine if your app was in foreground or background when notification was received.

Best,
Murat

**Comment by clpolet** [comment]
Yes if `AppState` is `background` it means the notification was received in background. Though, are you using silent notifications or classic notifications in iOS? iOS callbacks are executed in background for silent notifications only.

**Comment by guperrot** [comment]
I think the question was to determine if the callback was executed because of a notification click or if it was received in foreground. This is still a valid question when you don't use silent push.

**Comment by buddhamangler** [comment]
@guperrot correct

**Comment by buddhamangler** [comment]
@clpolet i am NOT using silent notifications.  I just need to be able to differentiate between a foreground received notification and a notification triggered by clicking the notification in the notification area.

**Comment by buddhamangler** [comment]
Surely this is a common scenario?  I don't think AppState suggested above helps me.

**Comment by buddhamangler** [comment]
@TroubleMakerBen Thank you for the detailed explanation! I will investigate this method.  Right now I have been trying to make a pure react native solution work where i check the AppState as suggested above and if the state is background or an initial state i set in the constructor (which is overwritten in the react native pipeline which always occurs after the delivery of the notification) then i assume it was launched by the user.  I really don't know if that's a good assumption yet, but it seems somewhat promising.

**Comment by TroubleMakerBen** [comment]
That sounds like it coulld work, too. Let us know how things go @buddhamangler.

**Comment by TroubleMakerBen** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.

**Comment by jdnichollsc** [comment]
Debugging the AppCenter listener from Android, `AppCenter.currentState` is always `active`, Do you know why?

**Comment by clpolet** [comment]
The `AppState.currentState` should definitely be background when the notification is received in background. Once the user clicks on the notification (even if the notification was received in background) then the state shouldn't be background anymore.

**Comment by FelipeGatti** [comment]
is there any idea on some modification in the SDK to make this happen easier?
I'm planning on following @buddhamangler path but not sure if it's the correct way to go on.

**Comment by annakocheshkova** [comment]
@FelipeGatti currently, there's no convenient way to do this except the solution described it the docs. If you want, you can follow @jdnichollsc's comment [here](https://github.com/microsoft/appcenter-sdk-react-native/issues/505#issuecomment-455622956) on an alternative approach.

**Comment by FelipeGatti** [comment]
Thank you @annakocheshkova for the rapid response! i will check this approach!
