### ISSUE TITLE
Notification Tray not coming in IOS when the app is in foreground state

### ISSUE THREAD

**Issue by venkat-waran** [Microsoft/AppCenter-SDK-React-Native#394]
### **Description**

I'm not getting notification tray in IOS when the app is in foreground state. I'm sending data with content-available = 1. Still, I'm not getting.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Send push notification via the portal

2. When the app is in the foreground state not getting Notification Tray

### **Details**

1. Which SDK version are you using?
    -  1.7.1
2. Which OS version did you experience the issue on?
    - iOS 11
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -  iPhone 7 physical device
4. What third party libraries are you using?
    - no 
5. Run the following command and paste the output below: `react-native info`

 React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 25.55 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.9.0 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.0.1 - ~/.npm-global/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here
1.5.3
7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

**Comment by clpolet** [comment]
Hi there, thanks for reaching us. On iOS any notifications received in foreground won't show up to the user, it will just trigger the appropriate callback. This is the OS default behavior. The `content-available = 1` flag allows to wake up the application in background so the callback can be executed.

**Comment by venkat-waran** [comment]
Hi thanks for the reply. In Android also notification tray is not coming in any states.

**Comment by TroubleMakerBen** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
