### ISSUE TITLE
Android Build Error: Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:1.8.0

### ISSUE THREAD

**Issue by Brian-Azizi** [Microsoft/AppCenter-SDK-React-Native#404]
### **Description**

On the latest Appcenter release, building the Android Debug APK fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':appcenter-crashes'.
      > Could not resolve all dependencies for configuration ':appcenter-crashes:_debugPublishCopy'.
         > Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:1.8.0.
           Required by:
               project :appcenter-crashes
```

Same problem when trying to build the release APK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new react-native project: `react-native init`
2. Install Appcenter SDK: `yarn add appcenter appcenter-analytics appcenter-crashes`
3. Link it: `react-native link`
4. Build Android Debug APK `cd android && ./gradlew assembleDebug` <- This step fails

### **Details**

1. Which SDK version are you using? 1.8.0

5. Run the following command and paste the output below: `react-native info`

Place output here:

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 29.34 MB / 8.00 GB
      Shell: 5.5 - /usr/local/bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.6.0 - ~/.yarn/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by guperrot** [comment]
Hi, the package was not published to jCenter, we just published it and you can retry building now. Sorry for the inconvenience.

**Comment by harshq** [comment]
Hi @guperrot, I'm getting the same error for appcenter-react-native:1.9.0. I'm guessing it isn't published to jCenter ? Any suggestions ?

**Comment by justinjoyn** [comment]
`* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':appcenter'.
      > Could not resolve all dependencies for configuration ':appcenter:_debugPublishCopy'.
         > Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:1.9.0.
           Required by:
               project:appcenter:unspecified`

**Comment by bmourat** [comment]
@harshq @justinjoyn Sorry for the inconvenience, could you please check again?

**Comment by justinjoyn** [comment]
Hi @bmourat , Thanks for the quick reply. It's working fine for me now. Awesome.

**Comment by harshq** [comment]
@bmourat Works like a charm. Thanks 👌
