### ISSUE TITLE
iOS build fails with: "no known class method for selector 'startFromLibraryWithServices:'"

### ISSUE THREAD

**Issue by Boatly** [Microsoft/AppCenter-SDK-React-Native#429]
### **Description**

Updated AppCenter. iOS build fails in AppCenter and in XCode. Android works.

My package.json looks like this:
```
"appcenter": "^1.8.1",
"appcenter-analytics": "^1.8.1",
"appcenter-crashes": "^1.8.1",
```

and my Podfile like this:
```
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Followed steps to update SDK: https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-update-react-native-sdk-to-the-latest-version
2. Followed steps from 'geocachingsyntaxerror' in post: https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/406
3. Build still fails.

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.8.1
2. Which OS version did you experience the issue on?
    - iOS 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Build fails.  Emulator runs fine.
4. What third party libraries are you using?
    - "@types/react-navigation": "^2.0.6",
    - "apisauce": "^0.15.2",
    - "appcenter": "^1.8.1",
    - "appcenter-analytics": "^1.8.1",
    - "appcenter-crashes": "^1.8.1",
    - "mobx": "^4.3.1",
    - "mobx-persist": "^0.4.1",
    - "mobx-react": "^5.2.3",
    - "moment": "^2.22.2",
    - "native-base": "^2.5.2",
    - "react": "16.3.1",
    - "react-native": "0.55.4",
    - "react-navigation": "^2.4.1",
    - "tslint": "^5.10.0"
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.2.1
  Yarn: 1.7.0
  npm: 6.3.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

**Comment by dhei** [comment]
Hi @Boatly,
Your Podfile and package.json looks fine to me.
As you mentioned, when you followed @geocachingsyntaxerror's [reply](https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/406#issuecomment-417790166), do you see any error in `react-native link` output? Do you see which versions of `AppCenter/Crashes` `AppCenter/Analytics` `AppCenterReactNativeShared` are installed from the output?

**Comment by Boatly** [comment]
Hi @dhei ,

No, I don't see any errors in `react-native link` output.

Version 1.8.1 is installed from the output.

Here is the output:

```
petersedman@Peters-MBP food-choice-at-work (master) $ react-native link
Scanning folders for symlinks in /Users/petersedman/projects/food-choice-at-work/node_modules (25ms)
rnpm-install info Platform 'ios' module appcenter is already linked 
rnpm-install info Platform 'android' module appcenter is already linked 
Configuring AppCenter Analytics for Android
Android App Secret is already set in android/app/src/main/assets/appcenter-config.json
Configuring AppCenter for iOS
Adding AppCenter configuration file...
iOS App Secret is already set in ios/FCW/AppCenter-Config.plist
Patching file ios/FCW/AppDelegate.m
Added code to initialize iOS AppCenter SDK in ios/FCW/AppDelegate.m
Installing Cocoapods dependencies...
Analyzing dependencies
Downloading dependencies
Using AppCenter (1.9.0)
Using AppCenterReactNativeShared (1.8.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 2 total pods installed.
rnpm-install info Platform 'ios' module appcenter-analytics is already linked 
rnpm-install info Platform 'android' module appcenter-analytics is already linked 
Configuring AppCenter Analytics for Android
Android App Secret is already set in android/app/src/main/assets/appcenter-config.json
? For the Android app, should user tracking be enabled automatically? Enable Automatically
Configuring AppCenter Analytics for iOS
Adding AppCenter configuration file...
iOS App Secret is already set in ios/FCW/AppCenter-Config.plist
? For the iOS app, should user tracking be enabled automatically? Enable Automatically
Patching file ios/FCW/AppDelegate.m
Added code to initialize iOS Analytics SDK in ios/FCW/AppDelegate.m
Installing Cocoapods dependencies...
Analyzing dependencies
Downloading dependencies
Using AppCenter (1.9.0)
Using AppCenterReactNativeShared (1.8.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 2 total pods installed.
rnpm-install info Platform 'ios' module appcenter-crashes is already linked 
rnpm-install info Platform 'android' module appcenter-crashes is already linked 
Configuring AppCenter Crashes for Android
Android App Secret is already set in android/app/src/main/assets/appcenter-config.json
? For the Android app, should crashes be sent automatically or processed in JavaScript before being sent? Automatically
Configuring AppCenter Crashes for iOS
Adding AppCenter configuration file...
iOS App Secret is already set in ios/FCW/AppCenter-Config.plist
? For the iOS app, should crashes be sent automatically or processed in JavaScript before being sent? Automatically
Patching file ios/FCW/AppDelegate.m
Added code to initialize iOS Crashes SDK in ios/FCW/AppDelegate.m
Installing Cocoapods dependencies...
Analyzing dependencies
Downloading dependencies
Using AppCenter (1.9.0)
Using AppCenterReactNativeShared (1.8.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 2 total pods installed.
rnpm-install info Linking assets to ios project 
rnpm-install info Linking assets to android project 
rnpm-install info Assets have been successfully linked to your project 
petersedman@Peters-MBP food-choice-at-work (master) $ 
```

**Comment by dhei** [comment]
Hey @Boatly,
We haven't heard from you for a few days. Do you still have this issue? I am going to close this issue for now. Please let us know if you still questions.
Thanks.

**Comment by ikaro88** [comment]
i have a similar problem....

if i create a new project and add to my Unity game the GameAnalytics SDK (https://github.com/GameAnalytics/GA-SDK-UNITY)

when i compile the xcode project it give me a lot of error like this:

No known class method for selector 'addBusinessEventWithCurrency:amount:itemType:itemId:cartType:autoFetchReceipt:fields:'

for example on: [GameAnalytics addBusinessEventWithCurrency:currencyString amount:amountInteger itemType:itemTypeString itemId:itemIdString cartType:cartTypeString autoFetchReceipt:TRUE fields:fields_dict];

can everyone help me?

**Comment by ikaro88** [comment]
if i digit react-native info inside my project it give me "Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project."

please help me, this stupid GameAnalytics SDK  stuck my work from a WEEK!!

**Comment by sanoofrahiman960** [comment]
> Hey @Boatly, We haven't heard from you for a few days. Do you still have this issue? I am going to close this issue for now. Please let us know if you still questions. Thanks.

i got issue like this
/Users/sanoofrahimanj/Desktop/Workspace/Newprpject/vidhyadhan-mobile-app/node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapManager.m:48:17 No known class method for selector 'setMetalRendererEnabled:'

**Comment by sanoofrahiman960** [comment]
@Boatly how to solve this error i am stuck with one week
