### ISSUE TITLE
error: package com.microsoft.appcenter.reactnative.crashes does not exist

### ISSUE THREAD

**Issue by duha5h** [Microsoft/AppCenter-SDK-React-Native#430]
I try to build an android application, but it get me this error: 

Compilation failed; see the compiler output for details.    

in compiler output:
error: package com.microsoft.appcenter.reactnative.crashes does not exist import com.microsoft.appcenter.reactnative.crashes.AppCenterReactNativeCrashesPackage;

error: package com.microsoft.appcenter.reactnative.analytics does not exist import com.microsoft.appcenter.reactnative.analytics.AppCenterReactNativeAnalyticsPackage;

error: package com.microsoft.appcenter.reactnative.appcenter does not exist import com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage;

error: cannot find symbol new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)),
                ^
  symbol: class AppCenterReactNativeCrashesPackage

error: cannot find symbol new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
  symbol: class AppCenterReactNativeAnalyticsPackage

error: cannot find symbol new AppCenterReactNativePackage(MainApplication.this),
                ^  symbol: class AppCenterReactNativePackage
 
Please list the steps used to reproduce your issue.

1. npm install appcenter appcenter-analytics appcenter-crashes --save
2. react-native link appcenter
3. react-native link appcenter-analytics
43 react-native link appcenter-crashes
Then rebuild but it still not working, 

I also make a search but build still fail

1. Which version of the App Center SDK are you using?
    - 1.8.1
2. Which OS version did you experience the issue on?
    - Android 6.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - I used emulator, 7_WSVGA_Tablet_API_23
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`
Environment:  OS: Windows 10
 Node: 8.11.1  
Yarn: Not Found  
npm: 5.6.0  
Watchman: Not Found 
 Xcode: N/A  
Android Studio: Version  3.1.0.0 AI-173.4819257
Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1  react-native: 0.55.3 => 0.55.3

Can anyone help me?

**Comment by duha5h** [comment]
I now know what happens,, 
I forgot add
  "compile project(':appcenter')
    compile project(':appcenter-analytics')
    compile project(':appcenter-crashes')" 
in app/build.gradle

it works now.

**Comment by Ramonr20** [comment]
Where exactly you add these lines?

**Comment by novonimo** [comment]
> Where exactly you add these lines?


Open the project's app level build.gradle file (android/app/build.gradle) and add the following lines into dependencies section
