### ISSUE TITLE
version 1.7.1 is no longer available

### ISSUE THREAD

**Issue by n1ru4l** [Microsoft/AppCenter-SDK-React-Native#431]
### **Description**

Version 1.7.1 was pinned in our `Podfile.lock`. Starting today the build failed because the version could no longer be downloaded during `pod install`.

I had to update appcenter to the newest version in order to get the build working again...

Can someone please explain why the version is no longer available?

**Comment by Irrelon** [comment]
Yup same here... right before a tech demo!!!!

**Comment by dhei** [comment]
@n1ru4l, @Irrelon,
[Version 1.7.1](https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/tag/1.7.1) is restored. Please try again. Sorry for the inconvenience.
