### ISSUE TITLE
Opt out of jest mock package.json modification

### ISSUE THREAD

**Issue by stmillMSFT** [Microsoft/AppCenter-SDK-React-Native#435]
### **Description**

Each of these packages include a script that modifies the host's package.json to add mocking files for jest tests.  There is no way to opt out of this behavior.  Also, the mock functions provided don't have any sort of default return/resolve values, limiting their usefulness.  In our case, we already had good mocks in place when this was added, and would rather opt-out of the stock ones if possible.  

Also, a dependency probably shouldn't modify its host's package.json by default, right?

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. create a new project with jest as a dependency, and a jest config inside the package.json
2. add appcenter to the project
3. look at the package.json, it now has extra fields in it

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.6.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
4. What third party libraries are you using?
    - jest
    - ts-jest
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: Windows 10
  Node: 8.11.1
  Yarn: 1.7.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: ^0.55.0 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

[this is being reported from windows]

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:
this is a build-time issue

**Comment by clpolet** [comment]
@stmillMSFT thanks for reporting this one. 
You are right, we definitely shouldn't overwrite the package.json. I'll followup on a fix for this one on the AppCenter side.

**Comment by dhei** [comment]
@stmillMSFT RN SDK v1.9.0 is released today. The issue should be fixed by now.
