### ISSUE TITLE
#import <AppCenterAnalytics/MSPropertyConfigurator.h> file not found

### ISSUE THREAD

**Issue by yeomann** [Microsoft/AppCenter-SDK-React-Native#453]
### **Description**

i'm not sure how this is happening. but the issue just starts to appear today. i don't remember when i configured appcenter, it been long time but all of sudden, it's complaing that 

```
Building library libFolly.a
▸ Compiling AppCenterReactNativeAnalytics.m

❌  /zzz/xxxx/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m:24:9: 'AppCenterAnalytics/MSPropertyConfigurator.h' file not found

#import <AppCenterAnalytics/MSPropertyConfigurator.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **
```

i'm attaching the screenshots here
<img width="1169" alt="screenshot 2018-10-28 at 02 13 24" src="https://user-images.githubusercontent.com/5970751/47610180-7ed99a00-da57-11e8-88c4-82de862825d2.png">
<img width="1072" alt="screenshot 2018-10-28 at 02 15 11" src="https://user-images.githubusercontent.com/5970751/47610181-7ed99a00-da57-11e8-9d79-8a1b44afc5c3.png">

also i am using fix versions as mentioned here https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/451#issuecomment-433225097
```
        "appcenter": "1.9.0",
        "appcenter-analytics": "1.9.0",
        "appcenter-crashes": "1.9.0",
``` 
React Native Info

```
  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
      Memory: 105.00 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 9.11.1 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.3
        API Levels: 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.0 => 0.57.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-bridge: 2.0.1
      react-native-git-upgrade: 0.2.7
```
`pod --version`
1.5.3

EDIT: I'm wondering is that because of versions mentioned in PodFile?
```
    "# Pods for AppCenter"
    pod 'AppCenter/Analytics', '~> 1.8.0'
    pod 'AppCenterReactNativeShared', '~> 1.7.1'
    pod 'AppCenter/Crashes', '~> 1.8.0'
    
```
Here new version are available https://cocoapods.org/pods/AppCenter Please advice..

**Comment by yeomann** [comment]
well i did update the Pod also but seems that Xcode 10 is breaking react-native https://github.com/facebook/react-native/issues/21168 

my solution was to remove linking and npm modules and reinstall appcenter and its components, followed by relinking. 
my new POD is this.
```
  "# Pods for AppCenter"
    pod 'AppCenter/Analytics', '~> 1.10.0'
    pod 'AppCenterReactNativeShared', '~> 1.9.0'
    pod 'AppCenter/Crashes', '~> 1.10.0'
```

but i had lots of other errors such as `double-conversion cannot be found` etc. Possible solution was this https://github.com/facebook/react-native/issues/19573

everything is building right now.

**Comment by dhei** [comment]
Hi @yeomann,

Thanks for getting in touch.
 
For the benefits of others reading this, the "import <AppCenterAnalytics/MSPropertyConfigurator.h> file not found" error may be caused by the same issue as https://github.com/Microsoft/AppCenter-SDK-React-Native/issues/449, hence upgrading to latest version of AppCenter SDK makes it go away.

Regarding the RN-Xcode 10 compatibility, we are aware of such issues with Xcode 10, though there is no much we can do. Thanks for sharing your findings and workarounds of such issues.
