### ISSUE TITLE
react-native link fails "buildConfigurationList of undefined"

### ISSUE THREAD

**Issue by HannanShaikYara** [Microsoft/AppCenter-SDK-React-Native#454]
### **Description**

I am trying to install the appcenter config via npm. It Fails to link iOS native modules.

```
➜  $ react-native link appcenter
Scanning folders for symlinks in /Users/hannanshaik/Documents/codebase/yara/lp/Dealer/node_modules (24ms)
rnpm-install info Linking appcenter ios dependency 
rnpm-install ERR! Something went wrong while linking. Error: Cannot read property 'buildConfigurationList' of undefined 
Please file an issue here: https://github.com/facebook/react-native/issues 
```
### **Repro Steps**

Please list the steps used to reproduce your issue.

1. `npm install appcenter`
2. `react-native link`

### **Details**

`appcenter version: 1.8.1`

```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 1.11 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.1
        API Levels: 21, 22, 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^3.4.0 => 3.4.11 
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7
      react-native-scripts: 1.14.0
```

Pod Version: 1.5.3

**Comment by bmourat** [comment]
Hi @HannanShaikYara 
Could you please try installing the latest version of `appcenter` and see if it would help? Also did you try removing your `node_modules` folder and running `npm i` again?

**Comment by HannanShaikYara** [comment]
@bmourat I did update to `1.9.0` and also removed `node_modules` and tried. Same issue.

**Comment by bmourat** [comment]
@HannanShaikYara I have couple of questions:
 - How did you create your project? 
 - Did you try running link with module name `react-native link appcenter`?

Meanwhile you can try integrate SDK manually, you can read about it [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-manually).

**Comment by bmourat** [comment]
Hi @HannanShaikYara !

Did you resolve your issue? If not, could you please provide information on questions above.

**Comment by HannanShaikYara** [comment]
@bmourat I created the project with `react-native init` and I tried manual integration was messing up in between so I left it. 

For my last project (less than 1 month ago), I was easily able to link with `react-native link appcenter`. I speculate if there is something to do with my node version.

**Comment by bmourat** [comment]
Closing this issue, if you'll have any more questions please feel free to open new issues.
