### ISSUE TITLE
Feature Request: Add API to enable/disable push notifications for React Native iOS/Android

### ISSUE THREAD

**Issue by jdnichollsc** [microsoft/appcenter-sdk-react-native#459]
Hi guys,
We have an option in our app to disable the push notifications (using 1.8.0 version of the packages), but the `await Push.setEnabled()` is not working after enable/disable it several times, check the code:
```
import { 
  NativeModules,
  Platform
} from 'react-native'
import axios from 'axios'
import Push from 'appcenter-push'
import AppCenter from 'appcenter'
import Permissions from 'react-native-permissions'
import { config } from '../config'

const _registerPush = async (enable) => {
  if (enable) {
    const hasPermissions = await _validatePermissions()
    if (hasPermissions) {
      await Push.setEnabled(true)
    } else {
      throw new Error('Permissions')
    } 
  }
  else {
    const installId = await AppCenter.getInstallId()
    await axios.delete(`${config.appCenterApi}/apps/${config.ownerName}/${config.appName}/push/devices/${installId}`)
    await Push.setEnabled(false)
  }
}

const _validatePermissions = async () => {
  if (Platform.OS === 'ios') {
    const response = await Permissions.request('notification')
    if (NativeModules.RegisterPushNotifications) {
      await NativeModules.RegisterPushNotifications.register()
    }
    return response === 'authorized'
  }
  return true
}
```
Any help is really appreciated,
Nicholls

**Comment by jwallra** [comment]
Including the response I've given from App Center's Intercom support center:

The only way that you can prevent notifications from being sent on iOS is to disable them in the iOS notification center.  It's possible to disable all notifications for all apps at a device level via platform APIs, but the APIs in AppCenter will not be able to disable them individually.  It's not possible to delete APNS push tokens manually; they will only be deleted after an uninstall, OS upgrade, device wipe, or similar.  Unfortunately Apple doesn't provide APIs to do this programmatically, so it's a limitation of our SDK.

**Comment by jwallra** [comment]
I'm reopening this so we have a record that this is a feature people want.  We won't have an ETA but we'll leave it open so we can prioritize it when we have time.

**Comment by jdnichollsc** [comment]
@jwallra thanks Jacob for the help! 👍

**Comment by jdnichollsc** [comment]
Hi guys, this is the native code:
**RegisterPushNotifications.h**
```
#import <React/RCTBridgeModule.h>

@interface RegisterPushNotifications : NSObject <RCTBridgeModule>
@end
```

**RegisterPushNotifications.m**
```
#import "RegisterPushNotifications.h"

#import <AppCenterReactNativePush/AppCenterReactNativePush.h>
#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
#import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNative/AppCenterReactNative.h>

@implementation RegisterPushNotifications

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(register)
{
  [AppCenterReactNativePush register];
}

@end
```
Thanks, Nicholls

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue since [App Center Push has been removed from the SDK in 4.0.0](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400).
