### ISSUE TITLE
Add MacOS React-Native support to AppCenterReactNativeShared

### ISSUE THREAD

**Issue by berickson1** [microsoft/appcenter-sdk-react-native#476]
### **Description**

We're working on a ReactNative MacOS app & want to finish integrating AppCenter using the ReactNative wrapper.  I've done the changes to add MacOS targets for AppCenter-React
Native-Analytics/Push/Crashes but need some help with the ReactNativeShared Pod.  Opened a PR that includes these changes (#477 )

I'm happy to help validate/test this but I don't have enough knowledge about your build process + pods to make the complete change.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
