### ISSUE TITLE
Feature Request: App Center Analytics: Allow tracking of authenticated users

### ISSUE THREAD

**Issue by syntax-e** [microsoft/appcenter-sdk-react-native#503]
### **Description**

We currently have an app in production that leverages App Center Analytics. We have App Center exporting analytical data to Azure Application Insights. Users of our app may be logged in with a username and password or may be anonymous at various times. We'd like to track the usernames of authenticated users so that rich reports may be generated in Application Insights.

It would be ideal if App Center Analytics exposed a method like that of the Application Insights JavaScript API: [SetAuthenticatedUserContext](https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#setauthenticatedusercontext)

Thank you

**Comment by elamalani** [comment]
@bearer-syntaxerror Thanks for using App Center. We don't have any plan to support this API in the Analytics module. For now, you could log user id using custom properties in an event.

We will keep this thread open for visibility and let you know once we decide to support it in the SDK.

**Comment by DmitriyKirakosyan** [comment]
Hi there, you can use [setUserId API](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#identify-users).
I'm closing this issue but feel free to reopen if you have additional questions.
