### ISSUE TITLE
'Framework not found AppCenterAnalytics' after manual linking iOS SDK

### ISSUE THREAD

**Issue by sanderwapstra** [Microsoft/AppCenter-SDK-React-Native#531]
### **Description**

Following exact steps in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-manually and the video https://www.dropbox.com/s/fkk9ag91golwg8c/Screencast-RN-Manual-Linking-480.mov?dl=0 results in:

```
ld: framework not found AppCenterAnalytics
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.12.0
2. Which OS version did you experience the issue on?
    - Deployment target 9.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone XR simulator
4. What third party libraries are you using?
    - Mapbox
5. Run the following command and paste the output below: `react-native info`

```
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 30.33 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 23.0.1, 26.0.1, 27.0.3, 28.0.3
        System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3
      react-native: 0.57.8 => 0.57.8
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.0
```

**Comment by jaelim-ms** [comment]
Unfortunately I couldn't reproduce the issue. Can you double check "Linked Frameworksand Libraries" in General for your app target and see there is AppCenterAnalytics.framework specified?
Also make sure Framework Search Paths contain a folder that contains all frameworks. If you have sub folders in the folder, the search paths should be "recursive".

**Comment by sanderwapstra** [comment]
@jaelim-ms Thanks for your help! It was indeed the Framework Search Paths that was missing. I added '$(PROJECT_DIR)/Vendor' (recursive) to debug and release and now it is working!
