### ISSUE TITLE
Dynamic Custom Properties with Push Notifications

### ISSUE THREAD

**Issue by michaelmerrill** [Microsoft/AppCenter-SDK-React-Native#533]
### **Description**

I'm experiencing an issue using custom properties with push notifications. Currently, I am updating custom properties dynamically and sending push notifications to audiences using those custom properties. However, it seems as though the custom properties are not updating immediately. Is this to be expected?

### **Repro Steps**

1. Set custom property "group" on device1 with value "A"
2. Set custom property "group" on device2 with value "A"
3. Send push notification to group "A" using an Audience where selector is group = A.
4. Both device should get notification.
5. Update custom property "group" on device2 with value "B"
6. Send push notification to group "A" using an Audience where selector is group = A
7. Send push notification to group "B" using an Audience where selector is group = B.
8. Device1 should get notification for group "A".
9. Device2 should get notification for group "B".

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.12.0
2. Which OS version did you experience the issue on?
    - iOS 12
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone X physical device, iPod Touch physical device
5. Run the following command and paste the output below: `react-native info`

```
React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 9.77 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-16 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.7.0 => 16.7.0 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

`1.5.3`

**Comment by jaelim-ms** [comment]
@michaelmerrill Yes, it is expected. We need to process the new value that takes up to 30 minutes.
