### ISSUE TITLE
Android: onPushNotificationReceived doesn't fire when app is in background

### ISSUE THREAD

**Issue by richardmtsr** [Microsoft/AppCenter-SDK-React-Native#541]
**Description**

On Android, the onPushNotificationReceived event isn't received If I receive a notification whilst the app is open, but in the background.
The event fires absolutely fine if the app is open and in the foreground or if the app is completely closed.

### **Details**

1. Which version of the App Center SDK are you using?
    - 1.9.0
2. Which OS version did you experience the issue on?
    - All Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Physical devices
5. Run the following command and paste the output below: `react-native info`

```
React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 840.66 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.3.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 26.0.1, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

6.  For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:

```
02-21 13:16:35.667 6469-6469/com.enlitened D/AppCenterPush: Received push intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=com.enlitened cmp=com.enlitened/com.microsoft.appcenter.push.PushReceiver (has extras) } background=true
    google.delivered_priority=high
    google.sent_time=1550754995440
    google.ttl=2419200
    google.original_priority=high
    gcm.notification.e=1
    screen=Shop
    gcm.notification.sound=default
    gcm.notification.title=Your idea is approved!
    from=756549915382
    gcm.notification.sound2=default
    google.message_id=0:1550754995482387%09e5cd2909e5cd29
    gcm.notification.body=Share it now to get support – and earn coins.
    google.c.a.e=1
    collapse_key=com.enlitened
    Background notifications are handled by Firebase SDK when integrated.
02-21 13:16:35.678 6469-6491/com.enlitened W/FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.google.firebase.messaging.zzb.zzb(Unknown Source:81)
        at com.google.firebase.messaging.zzb.zzc(Unknown Source:2)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:353)
        at com.google.firebase.iid.zzg.run(Unknown Source:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)
02-21 13:16:35.690 6469-6491/com.enlitened W/FirebaseMessaging: Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
02-21 13:16:41.415 1262-1923/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.enlitened/.MainActivity bnds=[640,1776][841,2074]} from uid 10056
02-21 13:16:41.460 6469-6537/com.enlitened W/ReactNativeJS: Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
    (Saw setInterval with duration 600000ms)
02-21 13:16:41.767 629-2053/? W/SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=AppWindowToken{548724a token=Token{670abb5 ActivityRecord{578bec u0 com.enlitened/.MainActivity t266}}})/@0x6b684ee - animation-leash#0
    Attempting to set client state on removed layer: Surface(name=AppWindowToken{d296ba3 token=Token{668bed2 ActivityRecord{cb7b55d u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t154}}})/@0x57c0392 - animation-leash#0
    Attempting to destroy on removed layer: Surface(name=AppWindowToken{548724a token=Token{670abb5 ActivityRecord{578bec u0 com.enlitened/.MainActivity t266}}})/@0x6b684ee - animation-leash#0
    Attempting to destroy on removed layer: Surface(name=AppWindowToken{d296ba3 token=Token{668bed2 ActivityRecord{cb7b55d u0 com.google.android.apps.nexuslauncher/.NexusLauncherActivity t154}}})/@0x57c0392 - animation-leash#0
02-21 13:16:46.744 1262-3128/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x14000000 pkg=com.enlitened cmp=com.enlitened/.MainActivity (has extras)} from uid 10170
02-21 13:16:46.752 6469-6469/com.enlitened W/FirebaseMessaging: Error while parsing timestamp in GCM event
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.google.firebase.messaging.zzb.zzb(Unknown Source:81)
        at com.google.firebase.messaging.zzb.zzd(Unknown Source:116)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(Unknown Source:44)
        at com.google.firebase.iid.zzf.zza(Unknown Source:38)
        at com.google.firebase.iid.zzh.zzc(Unknown Source:77)
        at com.google.firebase.iid.zzh.zza(Unknown Source:29)
        at com.google.firebase.iid.FirebaseInstanceIdReceiver.zza(Unknown Source:139)
        at com.google.firebase.iid.FirebaseInstanceIdReceiver.onReceive(Unknown Source:19)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-21 13:16:46.774 6469-6537/com.enlitened W/ReactNativeJS: Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
    (Saw setInterval with duration 600000ms)
02-21 13:16:47.193 1802-1802/? W/NotificationEntryMgr: removeNotification for unknown key: 0|com.enlitened|0|FCM-Notification:15481752|10170
02-21 13:16:47.207 629-651/? W/SurfaceFlinger: Attempting to set client state on removed layer: Surface(name=AppWindowToken{548724a token=Token{670abb5 ActivityRecord{578bec u0 com.enlitened/.MainActivity t266}}})/@0x6b684ee - animation-leash#0
    Attempting to destroy on removed layer: Surface(name=AppWindowToken{548724a token=Token{670abb5 ActivityRecord{578bec u0 com.enlitened/.MainActivity t266}}})/@0x6b684ee - animation-leash#0
```

**Comment by dtrabo** [comment]
Hi @richardmtsr , thanks for reporting this!

Can you share your build.gradle file?
I’m not sure, but it seems like the reason of the bug is old version of Firebase.

Thanks!

**Comment by richardmtsr** [comment]
`
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.enlitened"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 135
        versionName "1.9.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    buildToolsVersion '27.0.3'

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

dependencies {
    compile project(':react-native-video')
    compile project(':react-native-firebase')
    compile project(':appcenter')
    compile project(':appcenter-push')
    compile project(':react-native-svg')
    compile project(':react-native-vector-icons')
    compile project(':lottie-react-native')
    compile project(':appcenter-analytics')
    compile project(':appcenter-crashes')
    compile fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-analytics:15.0.2"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
`

**Comment by dtrabo** [comment]
@richardmtsr It seems that you are using the old version of AppCenter which are using the old firebase-messaging module. Please, update AppCenter to the latest version and tried to reproduce this bug.

**Comment by justinjoyn** [comment]
`apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile
project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

def enableSeparateBuildPerCPUArchitecture = false
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "******"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        vectorDrawables.useSupportLibrary = true
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        release {
       
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':appcenter-push')
    implementation project(':react-native-config')
    implementation project(':react-native-image-crop-picker')
    implementation project(':appcenter-crashes')
    implementation project(':appcenter-analytics')
    implementation project(':appcenter')
    implementation project(':react-native-auth0')
    implementation project(':react-native-gesture-handler')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.firebase:firebase-core:16.0.7'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'`

This is my `build.gradle`. 
The `onPushNotificationReceived` is never called when the app is in the background. According to docs, it should be called when the user clicks on the notification. Right?

**Comment by dtrabo** [comment]
Hi @justinjoyn , thanks for reporting this!

Tell me how you installed the plugin, please? And what version of App Center are you using?

Thanks!

**Comment by annakocheshkova** [comment]
@justinjoyn Hi, do you have any updates on this?

**Comment by TomerRon** [comment]
Hi, I am having the exact same issue.

- When a notification is received and the app is in the foreground, it works.
- When a notification is clicked and the app is completely closed (not running in the background), it works.
- When a notification is clicked and the app is in the background, it does not work.

My listener, which is located in my top-level js file `App.tsx`:

```
Push.setListener({
   onPushNotificationReceived: _pushNotification => {
      console.log('received push')
   }
})
```

I can see the `console.log` in the first two scenarios, but not the third.

My `build.gradle` file:

```
apply plugin: "com.android.application"

...

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "com.foobar.app"
        minSdkVersion 19
        targetSdkVersion 28
        versionName "2.0.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        multiDexEnabled true
    }
    
   ...

}

dependencies {
    compile project(':react-native-mixpanel')
    compile project(':react-native-intercom')
    compile project(':appcenter')
    compile project(':appcenter-crashes')
    compile project(':appcenter-analytics')
    compile project(':appcenter-push')
    implementation project(':react-native-webview')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-svg')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-background-timer')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    compile 'io.intercom.android:intercom-sdk-base:5.1.0'
    compile project(':react-native-code-push')
    compile project(':react-native-custom-tabs')
    implementation 'com.google.firebase:firebase-core:16.0.1'
}

...

apply plugin: 'com.google.gms.google-services'

```

Thanks!

**Comment by guperrot** [comment]
Can you share the AndroidManifest.xml of your application and does the appcenter-config.json file contain more entries than just the appSecret?

**Comment by TomerRon** [comment]
Hey @guperrot, definitely, here is my `AndroidManifest.xml`:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.nativeapp"
    android:versionCode="1"
    android:versionName="1.0"
    xmlns:tools="http://schemas.android.com/tools"
>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />

    <uses-sdk android:targetSdkVersion="27" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter android:label="filter_react_native">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="allthings" android:host="" />
          <data android:scheme="allthings" android:host="home" />
          <data android:scheme="allthings" android:host="settings" />
          <data android:scheme="allthings" android:host="signIn" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <service
        android:name="com.robinpowered.react.Intercom.IntercomIntentService"
        android:exported="false">
        <intent-filter
          android:priority="999">
            <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        </intent-filter>
      </service>
      <receiver
        android:name="io.intercom.android.sdk.push.IntercomPushBroadcastReceiver"
        tools:replace="android:exported"
        android:exported="true" />
    </application>

</manifest>
```

My `appcenter-config.json` only contains the `app_secret`.

Thanks.

**Comment by guperrot** [comment]
Ok, so your activity has `singleTask` launch mode which is not the default value for new apps (including in React Native).

In your scenario you need to add:

```
@Override
protected void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    Push.checkLaunchedFromNotification(this, intent);
}
```

To `MainActivity.java`.

This was documented in Android Java/Kotlin page but not React Native documentation, we will fix the docs.

**Comment by TomerRon** [comment]
Thank you! This solved my issue, clicking the push now successfully triggers the push listener even when the app is running in the background.

For others with this problem (especially those like me that don't do Java), here is everything I had to do in `MainActivity.java`. First, add the imports:

```
import android.content.Intent;
import com.microsoft.appcenter.push.Push;
```

Then add the `onNewIntent` (note: I had to make it a public method, it did not work with protected):

```
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    Push.checkLaunchedFromNotification(this, intent);
}
```

**Comment by guperrot** [comment]
The docs are now live with this change.
Thanks for using AppCenter.
