### ISSUE TITLE
Use more standard way to link pod

### ISSUE THREAD

**Issue by jpolo** [microsoft/AppCenter-SDK-React-Native#556]
### **Description**

At the moment appcenter links pods with a static pod version `pod 'appcenter ~> 'VERSION'`

It seems the standard way is to do something like : `pod 'appcenter', :path => '../node_modules/appcenter'`

This npm package must contains the corresponding podspec at the root to properly resolve the pod dependency.

**Comment by annakocheshkova** [comment]
Hi @jpolo yes you may be right. We already have a thread with an issue which is solved by linking this way: #510 
I'll see I guess we should file a bug.

Thanks!

**Comment by annakocheshkova** [comment]
@jpolo, I discussed this with the team. The solution you provided should solve the issue for those who have linked their pods realtive to node_modules. However, the default way to link pods is using the static pod version, so we will keep the linking script this way, but we will add the "relative path" linking in our dicumentation. 

Thanks!

**Comment by jpolo** [comment]
Nice !

**Comment by guperrot** [comment]
Documentation was updated for manual linking.

**Comment by jpolo** [comment]
When using the new documented way of linking with pods+path, I just saw that the  version of AppCenter pod and appcenter npm package were not consistent. This is probably because the podspec file points to git : `https://github.com/Microsoft/AppCenter-SDK-React-Native.git` instead of pointing to a relative path.

Another standard matter but less critical, I would also suggest to use the `pod 'appcenter', :path => '../node_modules/appcenter'` instead `pod 'appcenter', :path => '../node_modules/appcenter/ios'`
That seems to be the new standard used by almost every library now.

**Comment by guperrot** [comment]
> When using the new documented way of linking with pods+path, I just saw that the version of AppCenter pod and appcenter npm package were not consistent. This is probably because the podspec file points to git : `https://github.com/Microsoft/AppCenter-SDK-React-Native.git` instead of pointing to a relative path.
> 
> Another standard matter but less critical, I would also suggest to use the `pod 'appcenter', :path => '../node_modules/appcenter'` instead `pod 'appcenter', :path => '../node_modules/appcenter/ios'`
> That seems to be the new standard used by almost every library now.

The documentation was updated on April 3rd regarding that comment but the ticket here should have been closed. Doing that now.
