### ISSUE TITLE
Zip file is missing "ios" folder per manual install instructions

### ISSUE THREAD

**Issue by bobber205** [Microsoft/AppCenter-SDK-React-Native#560]
### **Description**

On https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native it says

```
Unzip both archives and you will see a folder called AppCenter-SDK-Apple/iOS that contains different frameworks for each App Center service. 
```

As you can see when you download the latest zip of this SDK there is no "ios" folder basically making the instructions a guessing game on what to do. The instructions are already pretty complicated so it's very unfortunate that the very first instruction is so vague on what to do.

Can anyone help me here? I can't use the pod installation method. I've tried for a week to get it to work without making any progress. (I can't use the `use_frameworks!` statement in my Podfile because of a incompatibility with another framework I must use)

I'm happy to do this process manually but I am scared to get started since I can't find the ios folder.

**Comment by annakocheshkova** [comment]
Hi @bobber205, I'm sorry the instruction confused you a little bit. So first 2 points say that you should download **both** Apple SDK and React Native SDK. _iOS_ folder is inside the Apple SDK zip file:
![image](https://user-images.githubusercontent.com/34677812/54747932-46428480-4be1-11e9-90b3-a818d6e039b0.png)

I will edit the docs to make this more clear.
Feel free to ask any questions.

**Comment by bobber205** [comment]
Can you show me a larger path from the root folder for this folder? I'm looking and looking at the unzipped files and can' find what's in that screenshot.

**Comment by bobber205** [comment]
Or maybe include a link of where to download it?

**Comment by guperrot** [comment]
You need both the frameworks inside the AppCenterReactNativeShared zip: https://github.com/Microsoft/AppCenter-SDK-React-Native/releases/latest

And also the native SDK that React Native SDK depends on:
https://github.com/Microsoft/AppCenter-SDK-Apple/releases/latest.

Both zip contains frameworks, you need them all (except Distribute or the modules you don't use from react-native).

The one named only "AppCenter" is the core and is needed by every other module.

**Comment by annakocheshkova** [comment]
hi @bobber205 do you have any updates? Did you manage to get it working?

**Comment by bobber205** [comment]
Sorry I haven't had a good chance to get back to this but I will soon!

**Comment by bobber205** [comment]
oh my. I was downloading the wrong folder -- I was getting the source code files not the pod file. :doh:

**Comment by annakocheshkova** [comment]
Ah that's why you were confused with our explanations! Ok glad the issue is resolved :)
