### ISSUE TITLE
RN 0.59 Android build error

### ISSUE THREAD

**Issue by gunnartorfis** [Microsoft/AppCenter-SDK-React-Native#562]
### **Description**
> Task :appcenter:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':appcenter:compileDebugJavaWithJavac'.
> Could not create service of type DefaultGeneralCompileCaches using GradleScopeCompileServices.createGeneralCompileCaches().

### **Repro Steps**
react-native run-android

### **Details**
1. Which version of the App Center SDK are you using?
   "appcenter": "^1.13.0",
    "appcenter-analytics": "^1.13.0",
    "appcenter-crashes": "^1.13.0",
2. Which OS version did you experience the issue on?
    - Android 9
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel 2 emulator
4. What third party libraries are you using?
    
5. Run the following command and paste the output below: `react-native info`
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 22.05 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.1 => 0.59.1

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:
In my MainApplication.java:
@Override
  public void onCreate() {
    super.onCreate();
    AppCenter.setLogLevel(android.util.Log.VERBOSE);
    SoLoader.init(this, /* native exopackage */ false);
  }

Running react-native run-android doesn't output anything more with that enabled.

**Comment by dtrabo** [comment]
Hi @gunnartorfis, thanks for reporting. I tried to reproduce your problem, but for me all works fine. Could you please provide detail steps of how you installed App Center modules?

**Comment by guperrot** [comment]
Please also share the full build logs at least all the end of it that actually contain the errors.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
