### ISSUE TITLE
After installing FBSDK, I get an error ld:  framework not found  AppCenter

### ISSUE THREAD

**Issue by heyaj19** [Microsoft/AppCenter-SDK-React-Native#564]
## Bug report

 ld: framework not found AppCenter 
:-1: linker command failed with exit code 1 (use -v to see invocation)

## To Reproduce
 1) Have Microsoft codepush installed. (Its working with just this installed)

2) When I install FBSDK for react native using steps https://developers.facebook.com/docs/react-native/configure-ios. 

The FBSDK installs perfectly but when I build it I get the above error.

## Expected behaviour
Should build.

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 1.13.0
2. Which OS version did you experience the issue on?
    the issue is in the build itself
3. What device version did you see this error on?  Were you using an emulator or a physical device?
     iPhone X physical device
4. What third party libraries are you using?
    - FBSDK, TipsiStripe, ReactNavigation, ExpoUnimodules
5. Run the following command and paste the output below: `react-native info`

System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 23.51 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - /usr/local/bin/node
      Yarn: 1.1.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 23, 24, 25, 26, 27, 28
        Build Tools: 25.0.0, 27.0.3, 28.0.2, 28.0.3
        System Images: android-21 | Google APIs Intel x86 Atom_64, android-24 | Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

**Comment by dtrabo** [comment]
Hi @heyaj19, thanks for reporting this!
Please share the full link logs at least all the end of it that actually contain the errors.

**Comment by heyaj19** [comment]
@dtrabo  Here you go 


`Ld /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/projectheyaj.app/projectheyaj normal arm64 (in target: projectheyaj)
    cd /Users/usernamexxx/reactcode/projectheyaj/ios
    export IPHONEOS_DEPLOYMENT_TARGET=10.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/Bolts -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/DoubleConversion -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXConstants -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXFileSystem -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXFont -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXLinearGradient -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXPermissions -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/EXWebBrowser -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/FBSDKCoreKit -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/FBSDKLoginKit -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/FBSDKShareKit -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/FirebaseCore -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/FirebaseMessaging -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/Folly -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/GoogleUtilities -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/Protobuf -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/RNGestureHandler -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/RNVectorIcons -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/React -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/ReactNativePermissions -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/Stripe -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/UMCore -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/UMReactNativeAdapter -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/glog -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/nanopb -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/react-native-fbsdk -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/react-native-splash-screen -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/tipsi-stripe -L/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/yoga -F/Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos -F/Users/usernamexxx/reactcode/projectheyaj/ios/Frameworks/ -filelist /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Intermediates.noindex/projectheyaj.build/Debug-iphoneos/projectheyaj.build/Objects-normal/arm64/projectheyaj.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=10.0 -Xlinker -object_path_lto -Xlinker /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Intermediates.noindex/projectheyaj.build/Debug-iphoneos/projectheyaj.build/Objects-normal/arm64/projectheyaj_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -ObjC -lBolts -lDoubleConversion -lEXConstants -lEXFileSystem -lEXFont -lEXLinearGradient -lEXPermissions -lEXWebBrowser -lFBSDKCoreKit -lFBSDKLoginKit -lFBSDKShareKit -lFirebaseCore -lFirebaseMessaging -lFolly -lGoogleUtilities -lProtobuf -lRNGestureHandler -lRNVectorIcons -lReact -lReactNativePermissions -lStripe -lUMCore -lUMReactNativeAdapter -lc++ -lglog -lnanopb -lreact-native-fbsdk -lreact-native-splash-screen -lsqlite3 -lstdc++ -ltipsi-stripe -lyoga -lz -framework AppCenter -framework AppCenterAnalytics -framework AppCenterCrashes -framework AppCenterReactNativeShared -framework Contacts -framework CoreLocation -framework CoreTelephony -framework FIRAnalyticsConnector -framework FirebaseAnalytics -framework FirebaseCoreDiagnostics -framework FirebaseInstanceID -framework Foundation -framework GoogleAppMeasurement -framework JavaScriptCore -framework PassKit -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework WebKit -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -ObjC -lc++ -framework JavaScriptCore /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTBlob.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTAnimation.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libReact.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTActionSheet.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTGeolocation.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTImage.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTLinking.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTNetwork.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTSettings.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTText.a -framework AuthenticationServices /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTVibration.a /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/libRCTWebSocket.a -lRNFirebase -lAppCenterReactNative -lAppCenterReactNativeAnalytics -lAppCenterReactNativeCrashes -lPods-projectheyaj -framework FBSDKCoreKit -framework FBSDKShareKit -framework FBSDKLoginKit -Xlinker -dependency_info -Xlinker /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Intermediates.noindex/projectheyaj.build/Debug-iphoneos/projectheyaj.build/Objects-normal/arm64/projectheyaj_dependency_info.dat -o /Users/usernamexxx/Library/Developer/Xcode/DerivedData/projectheyaj-aynkhpjwixalzidjoqhfteqrcmvz/Build/Products/Debug-iphoneos/projectheyaj.app/projectheyaj
`

**Comment by MatkovIvan** [comment]
Hi @heyaj19,

Does framework file really exist in your file system (`ios/Pods/AppCenter/AppCenter-SDK-Apple/iOS/AppCenter.framework`)?
If not, could you please try to re-run `react-native link`?

Thanks,
Ivan

**Comment by heyaj19** [comment]
Even when I unlink and delete app center it still gives me the issue. And yes it was there

**Comment by heyaj19** [comment]
I cant even archive my app.. any help here

**Comment by jpolo** [comment]
@heyaj19 
I had a strange bug involving AppCenter and FBSDK too. My build was broken because of 2 `AppCenter-config.plist`. There is one present in the examples directory of FBSDK that was linked either by AppCenter, or FBSDK (I would say AppCenter probably)

**Comment by MatkovIvan** [comment]
> Even when I unlink and delete app center it still gives me the issue.

So, it happens without AppCenter SDK? Or do you mean that you integrated it again after that?

**Comment by annakocheshkova** [comment]
Hey @heyaj19, just a friendly ping. Any updates on this?

**Comment by heyaj19** [comment]
@MatkovIvan @annakocheshkova Hey I decided to not use FBSDK right now. Other thing I noticed was I couldn't create an IPA because my header search paths were messed up. So I did fix them and was able to upload it to the app center. 

Ill try with FBSDK at another time this can be closed for now

**Comment by annakocheshkova** [comment]
Ok thanks for the heads up. I'm going to close this issue.
