### ISSUE TITLE
Fix license file extension mismatch

### ISSUE THREAD

**Issue by bnash2501** [microsoft/AppCenter-SDK-React-Native#570]
### **Description**

We use a license crawler to help generate a list of packages that our React Native app relies on.  However, the generate license URLs for AppCenter submodules are incorrect due to an extension mismatch on the license file between the main AppCenter-SDK-React-Native repo and the sub modules.

We end up with a license URL of `https://github.com/Microsoft/appcenter-sdk-react-native/raw/master/LICENSE.md` instead of `https://github.com/Microsoft/appcenter-sdk-react-native/raw/master/LICENSE` due to the submodules having the .md extension.

Can the license files be changes so they are consistent across all the modules?

**Comment by AnastasiaKubova** [comment]
Hi! Thank you for your comment. We have already started to fix it.

**Comment by bnash2501** [comment]
Thanks so much @AnastasiaKubova

**Comment by dhei** [comment]
It is fixed in #571 and should be out in the next App Center RN SDK release.

**Comment by dhei** [comment]
Hi @bnash2501,

This bug should be fixed in RN SDK v2.0.0 (https://github.com/microsoft/AppCenter-SDK-React-Native/releases/tag/2.0.0). Thanks.
