### ISSUE TITLE
Could not link the SDK on react-native 0.59

### ISSUE THREAD

**Issue by annakocheshkova** [microsoft/appcenter-sdk-react-native#612]
### **Description**

*Note: Opening this issue to track the problem a customer has run into while installing our SDK in an app with react-native installed using cocopods.*
_______________
Created a github repo [here](https://github.com/markmadlangbayan/appcenter-react-native-pods) that recreated my issue where installing AppCenter on a react-native project that is using cocoapods. Official React-Native instructions on how to install React-Native using Cocoapod is located [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps#3-install-cocoapods).

I tried several attempts but no success:

- Manually linked AppCenter (avoiding cocoapod), but ran into issues locating RN header files.
- Modified appcenter.podspec file that is referenced in the PodFile. Pod install failed with "target has transitive dependencies that include static binaries:" Modified the appcenter.podspec in node_modules and added s.static_framework = true, and the pod install ran without issues. But when I built the workspace, it couldn't find `<AppCenter/AppCenter.h>`. I stopped at trying to create a podspec for `AppCenterReactNativeShared` and add `s.static_framework = true` there instead of `appcenter.podspec`.

### **Repro Steps**

https://github.com/markmadlangbayan/appcenter-react-native-pods

### **Details**

1. Which version of the App Center SDK are you using?
    
2. Which OS version did you experience the issue on?
    
4. What third party libraries are you using?
   
5. Run the following command and paste the output below: `react-native info`

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

**Comment by annakocheshkova** [comment]
@markmadlangbayan Opening this issue for you. Please fill in th details above by editing the comment.

**Comment by markmadlangbayan** [comment]
> Could you also please confirm if you've followed [these steps](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-without-react-native-link) ?

@annakocheshkova It's almost the same step except I had to manually convert the project from manual to CocoaPods.   < 0.59's `react-native --init` doesn't use CocoaPod.

**Comment by annakocheshkova** [comment]
Got it @markmadlangbayan. What issues have you run into after performing those steps?

**Comment by annakocheshkova** [comment]
Hi @markmadlangbayan we haven't heard from you in a while, do you have any updates? If so, please re-open this issue, we'd love to hear from you!

**Comment by markmadlangbayan** [comment]
> Hi @markmadlangbayan we haven't heard from you in a while, do you have any updates? If so, please re-open this issue, we'd love to hear from you!

@annakocheshkova , please close the case.  I was in touch with Vyas at the AppCenter support and determined that this has something to do with use_framework! support.

**Comment by JuanSeBestia** [comment]
@markmadlangbayan You know if there is any way to deal with the error that is occurring with the use_framework! flag?. Because I need it

**Comment by markmadlangbayan** [comment]
> @markmadlangbayan You know if there is any way to deal with the error that is occurring with the use_framework! flag?. Because I need it

@JuanSeBestia, I haven't tested yet, but RN 0.61.0 should have this fix.  https://github.com/facebook/react-native/releases/tag/v0.61.0 .

Let me know if that works.

**Comment by JuanSeBestia** [comment]
Not work :/
I know that in RN 0.61.0 it's "solved", I use RN 0.61.2 but when import your modules and use use_frameworks!, the error "it couldn't find <AppCenter/AppCenter.h>" appear

**Comment by Jamminroot** [comment]
Hey, @JuanSeBestia, let's track this problem [here](https://github.com/microsoft/appcenter-sdk-react-native/issues/714/)
