### ISSUE TITLE
No podspec found for `appcenter-auth` in `../node_modules/appcenter-auth/ios`

### ISSUE THREAD

**Issue by dhei** [microsoft/appcenter-sdk-react-native#623]
Hello App Center RN developers, 

We found a bug in RN Auth SDK v2.1.0. The `podspec` file is named `appcenter-data.podspec` instead of `appcenter-auth.podspec`. 

We already fixed it in #621 and it should be fixed in the next SDK release.

I am creating this as an Issue for visibility.

### Context
If you are integrating Auth SDK without `react-native link` as documented at https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-without-react-native-link, you may run into this error during `pod install`:
>[!] No podspec found for `appcenter-auth` in `../node_modules/appcenter-auth/ios`

### Workaround (before next SDK release)
After installing `appcenter-auth` module, go to **node_modules/appcenter-auth/ios** directory, rename `appcenter-data.podspec` to `appcenter-auth.podspec` should fix the issue.

**Comment by dhei** [comment]
App Center RN SDK v2.2.0 is released with the fix to this bug. If anyone still run into this issue, please upgrade to v2.2.0 or higher.

**Comment by prabodhDelaplex** [comment]
Please upgrade to 2.2.0 in Package.json.
Then run npm i.
