### ISSUE TITLE
Push: Add a property to indicate receive state

### ISSUE THREAD

**Issue by janpieterz** [microsoft/appcenter-sdk-react-native#625]
Currently push notifications on iOS are hard to distinguish between if they're received through clicking a notification or in-app.
Workarounds exist (https://github.com/microsoft/appcenter-sdk-react-native/issues/505#issuecomment-455622956) but are, obviously, not ideal.

It'd be great if there was an added property that would indicate this, making the receiving code very easy for all consumers to handle.

Probably more a platform change for all SDK's, but filing here as well as it affects us using react-native.

Related on the .net sdk: https://github.com/microsoft/appcenter-sdk-dotnet/issues/875

**Comment by jwargo** [comment]
@janpieterz thank you for this, we’ve heard this from many customers and it’s on our roadmap.

**Comment by AnastasiaKubova** [comment]
I'm closing this issue since [App Center Push has been removed from the SDK in 4.0.0](https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/CHANGELOG.md#version-400).
