### ISSUE TITLE
SDK v2.2.0 is not working for Android on react native v0.60

### ISSUE THREAD

**Issue by simformsolutions** [microsoft/appcenter-sdk-react-native#651]
### **Description**

I am trying to set up the appcenter SDK for my react native project which is running on react native version 0.60.4. I have followed exact same steps given on getting started guide from appcenter.ms (Attached screenshot below) but It worked just fine for iOS but it is not working for android.
![Screen Shot 2019-07-26 at 2 19 10 PM](https://user-images.githubusercontent.com/8736329/61939284-8c08c280-afb0-11e9-9c0b-62be11ca1118.png)

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.2.0
2. Which OS version did you experience the issue on?
    - Android 8.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel 2 XL emulator, Mi4 physical device (Not getting log on any android device)
4. What third-party libraries are you using?
    - does not apply
5. Run the following command and paste the output below: `react-native info`

info Fetching system and libraries information...
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 9.95 GB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

does not apply

**Comment by russelarms** [comment]
Hi @simformsolutions, thanks for reaching out!

Do you get any errors or events just do not appear on the portal?

First, please make sure that the **appcenter-config.json** file is located under:
`*project_root*/android/app/src/main/assets`

**Comment by simformsolutions** [comment]
Yes, It is there with the proper key. On looking further into it, I found that auto-linking is not working in android as none of the three modules are available in android.

**Comment by clpolet** [comment]
Hi @simformsolutions, our documentation was refreshed especially for RN 0.60 you may want to give it a try https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#31-integrate-the-sdk-automatically-for-react-native-060. Sorry for the inconvenience.

**Comment by simformsolutions** [comment]
> Hi @simformsolutions, our documentation was refreshed especially for RN 0.60 you may want to give it a try https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#31-integrate-the-sdk-automatically-for-react-native-060. Sorry for the inconvenience.

Hi, I have done exact same steps but it seems like auto-link is not working properly for android (also tried in a fresh project) but luckily we were able to get it working by following manual linking steps for android.

**Comment by guperrot** [comment]
@simformsolutions can this issue be closed or was autolinking actually required for your scenario?

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
