### ISSUE TITLE
Latest version (2.2.0) moved podspec

### ISSUE THREAD

**Issue by gla5001** [microsoft/appcenter-sdk-react-native#652]
### **Description**

This is more of a question/FYI than an issue

Upgrading to latest version (2.2.0) broke app since the podspec files moved. I think this should have been a major version change since it breaks apps that reference the podspec in the ios directory

Or should have been documented more clearly.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. have a react native app that has a podfile that points podspec file to ios directory

**Comment by clpolet** [comment]
Hello @gla5001, thanks for reaching out and sorry for the inconvenience. This change was introduced to support the new integration available on RN v0.60 and our documentation was just refreshed especially for that RN version https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#31-integrate-the-sdk-automatically-for-react-native-060.

**Comment by guperrot** [comment]
Looks like the issue was resolved, please reopen if not.
