### ISSUE TITLE
Push.setEnabled() is unintuitive and only works "once" per install

### ISSUE THREAD

**Issue by bobber205** [microsoft/appcenter-sdk-react-native#657]
So no matter how many times you call `Push.setEnabled(true)` the platform specific "can this application send you push notifications" dialogue only appears once.

That makes sense.

What would be great is it somehow it could be changed to appear everytime when not in production mode. Having to delete the app off a simulator and recompile every time you wanna test that interaction is a pain.

Another small comment about this otherwise delightful library:

I am using `await` on the setEnabled() call and it's behaving very oddly.

```
            //prompt user to enable push
            await Push.setEnabled(true);
            let check = await Push.isEnabled();
            let value = check ? 1 : 0;
            let url = `${Config.USER_ACTIONS_URL}/${user_create_result.user.id}`;
            let payload = {
                push_enabled: value
            };
            await fetch(url, { method: 'PUT', headers: FORM_REQUEST_HEADERS(), body: JSON.stringify(payload) });
            store.dispatch(processLoginResult(user_create_result.user)).then(() => {
                this.props.navigation.navigate('MainFeedStack', { user_id: user_create_result.user.id });
            });
```

Been using await for a decent amount of time now but this is the first time I've seen behavior like this: While the dialog is present the rest of the code executes and the navigation library moves on even with the dialog still visible. Curious if this could have something to do with how `isEnabled()` is implemented.

**Comment by guperrot** [comment]
Today Push.isEnabled / setEnabled controls only the AppCenter SDK aspect of push being enabled.

The first time push is enabled, we try to get the token which triggers a system dialog managed by Apple and Apple only to ask user permission. If the user go to settings > app > Allow notifications and disables that, our SDK does not reflect that state in isEnabled (and setEnabled does not act on that toggle).

Today disabling push after it's been enabled once will just do the following;
* stop sending token updates to the server.
* stop processing pushes and thus stops calling listeners that we provide.

In particular it does not stop notifications from being received from server.

For the dialog, I don't think there is a solution for any SDK, it's not managed by our SDK (system dialog) and we have no control over it. I tried disabling both SDK and notifications in settings then restarting the app and enabling SDK: you are not prompted a second time.

**Comment by MatkovIvan** [comment]
Hi @bobber205,
we haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
