### ISSUE TITLE
Could not find auto-linked framework 'AppKit'

### ISSUE THREAD

**Issue by MarcosRenato266** [microsoft/appcenter-sdk-react-native#659]
### **Description**

I`ve beeing trying to build my project that use appcenter, I just made the process to link manually (SDK) and for this part, everything just work fine, but at the end of the build process in Xcode I just got: 

'''ld: warning: directory not found for option '-L/Users/marcosnunes/Library/Developer/Xcode/DerivedData/sanarflix-awnwylokutjwivdcwqnojtacduai/Build/Products/Debug-iphonesimulator/React'
ld: warning: Could not find auto-linked framework 'AppKit'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ASWebAuthenticationSession", referenced from:
      objc-class-ref in AppCenterAuth(libIdentityCore.a-x86_64-master.o)
  "_OBJC_CLASS_$_SFAuthenticationSession", referenced from:
      objc-class-ref in AppCenterAuth(libIdentityCore.a-x86_64-master.o)
  "_OBJC_CLASS_$_SFSafariViewController", referenced from:
      objc-class-ref in AppCenterAuth(libIdentityCore.a-x86_64-master.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)'''

### **Details**

1. Which version of the App Center SDK are you using?
    - "appcenter": "^2.2.0",
    "appcenter-analytics": "^2.2.0",
    "appcenter-crashes": "^2.2.0",
    "appcenter-push": "^2.2.0",

2. Which OS version did you experience the issue on?
    - target 9

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

pod 1.7.5

**Comment by guperrot** [comment]
Hi, it looks like a Mac OS framework for Auth is used in your project instead of a iOS lib. We don't support Auth for Mac OS so I was wondering where did you get the Auth native framework? Is it cocoapods? (if yes please shared podspec), if it's manual framework integration, please describe where you got the binaries for the native apple SDK for App Center.

**Comment by MatkovIvan** [comment]
Hi @MarcosRenato266,
we haven't heard from you in a while so I'm closing this issue.
Feel free to reopen this issue if it isn't resolved or you have additional questions.
