### ISSUE TITLE
 Where is this assets folder of the Android app?

### ISSUE THREAD

**Issue by arunharidas** [microsoft/appcenter-sdk-react-native#661]
In the documentation, it's saying that I need to copy this appcenter-config.json to the assets folder. Where do I find this folder?

> Create a new file with the new `appcenter-config.json` with the following content. Don't forget to add this file to the **assets** folder of your Android app.

I cannot find this assets folder in my react native app.

**Comment by Narcis11** [comment]
@arunharidas  You can create it by yourself in the "android" folder of your app. That's what I did and the installation worked find.

**Comment by MatkovIvan** [comment]
Hi @arunharidas,

Yes, the right path is `android/app/src/main/assets`. It's mentioned a bit below at the same docs page (in sections `3.2.2` and `3.4.5`).
We'll update the docs to make it more clear. Thanks for bringing our attention to it!

Best,
Ivan

**Comment by MatkovIvan** [comment]
The documentation has been updated, so I'm closing this issue.

**Comment by chonz0** [comment]
Hi, I am looking at the documentation right now and I can confirm **it has not been updated, sorry**.

![image](https://user-images.githubusercontent.com/2694422/81880754-9f4b4580-9564-11ea-96ac-20cb6f468ffc.png)

**Comment by MatkovIvan** [comment]
@chonz0 the documentation page has been updated, you can find it here -  https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#312-integrate-react-native-android

The instruction on the portal is only brief summary. Please look at the documentation instead of inline help to get more details. You always can find the link to detailed docs right on the page that you are referring to:

> For detailed instructions on SDK integration go to: [Getting Started with the React Native SDK](https://aka.ms/getting-started/React-Native)

**Comment by chonz0** [comment]
@MatkovIvan yes, I've already seen it in the URL you've provided, but I though I would be useful to have it explicit in both pages. Sorry for any confusion and thanks for pointing it out!

**Comment by russelarms** [comment]
@chonz0 we have updated the instruction on the portal too, it will be there soon.
