### ISSUE TITLE
Automatic installation issue iOS

### ISSUE THREAD

**Issue by anthonyhumphreys** [microsoft/appcenter-sdk-react-native#682]
### **Description**

Hi, I can't seem to build for iOS after adding the appcenter-push package. If I don't touch the appdelegate then all is well.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. yarn add appcenter-push
2. cd ios && pod install
3. Add
```
 #import <AppCenterReactNativePush/AppCenterReactNativePush.h>

...

[AppCenterReactNativePush register];

```
4. Build
### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 2.1.0
2. Which OS version did you experience the issue on?
    - iOS 12/13
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iOS 12 Emulator, also build only target
4. What third party libraries are you using?
    - n/a
5. Run the following command and paste the output below: `react-native info`
```
React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 11.60 GB / 32.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.17.3 - ~/.yarn/bin/yarn
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.3 => 0.59.3
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
```
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenter/Push', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
```
1.7.4

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:
n/a - doesn't build

**Comment by anthonyhumphreys** [comment]
Huh so I updated everything to 2.2.0, ran react-native link appcenter-push and it builds now.....
But only if I import as #import <AppCenterReactNativePush.h>

**Comment by jmazier-j2d** [comment]
Ran into a similar issue with all AppCenter 2.2.0 import for iOs, but I've seen a PR with this being fixed in 2.3.0 👍

**Comment by anthonyhumphreys** [comment]
Ahh didn’t spot that. Seems ok now, need to test on device :)

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AnastasiaKubova** [comment]
We haven't heard from you in a while so I'm closing this issue. Please comment if you have more questions about this.
