### ISSUE TITLE
AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h is not found

### ISSUE THREAD

**Issue by alex-mironov** [microsoft/appcenter-sdk-react-native#703]
I've followed the steps listed here https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native in order to add appcenter crashes.

Eventually after installation and linking I've got an error: `'AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h' file not found`'

<img width="955" alt="Screenshot 2019-09-11 18 17 55" src="https://user-images.githubusercontent.com/2544767/64711431-405b9b00-d4c2-11e9-9017-1046e4b3225b.png">

<img width="857" alt="Screenshot 2019-09-11 18 20 46" src="https://user-images.githubusercontent.com/2544767/64711689-b4963e80-d4c2-11e9-8305-689b7a1bdd4b.png">

Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myApp' do
  pod 'AppCenter/Crashes', '~> 2.3.0'
  pod 'AppCenter/Analytics', '~> 2.3.0'
  pod 'AppCenterReactNativeShared', '~> 2.3.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myApp

  

  platform :ios, '9.0'
  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics'

  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes'

  target 'myAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'myApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for myApp-tvOS

  target 'myApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

App Center SDK version
`2.3.0`

React Native Environment Info:
```
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

pod --version
`1.6.1`

**Comment by dtrabo** [comment]
Hi @alex-mironov , please notice that there are two ways to integrate AppCenter: one of them for RN 0.60 and other - for lower than 0.60. I see that you are using RN 0.59, you can check next link for this version https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#33-ios-only-integrate-the-sdk-manually-for-react-native-lower-than-060-without-react-native-link-or-cocoapods. Please make sure that all steps were correctly passed. If this issue won't be resolved after that, I'll help you with pleasure.

**Comment by alex-mironov** [comment]
thanks @dtrabo, I've noticed that. But does it mean that automatic integration for  < v.60 described here is not reliable? https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-integrate-the-sdk-automatically-for-react-native-lower-than-060

**Comment by alex-mironov** [comment]
just wondering as I was using that guide ^

**Comment by alex-mironov** [comment]
@russelarms I've dropped those lines. Unfortunately, the build still fails:
```
AppDelegate.m:9:9: fatal error: 'AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h' file not found
#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

info 1 error generated.

info

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening farutexMobile.xcworkspace

** BUILD FAILED **
```
will be checking the link you've added though. thnx

**Comment by alex-mironov** [comment]
I've checked the app you linked, didn't really spot so much difference except that you use `v2.2.0`.
AppDelegate.m
```
 #import "AppDelegate.h"
+#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
+#import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
+#import <AppCenterReactNative/AppCenterReactNative.h>

 #import <React/RCTBridge.h>
 #import <React/RCTBundleURLProvider.h>
@@ -15,6 +18,9 @@ @implementation AppDelegate

 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
 {
+  [AppCenterReactNativeCrashes registerWithAutomaticProcessing];  // Initialize AppCenter crashes
+  [AppCenterReactNativeAnalytics registerWithInitiallyEnabled:true];  // Initialize AppCenter analytics
+  [AppCenterReactNative register];  // Initialize AppCenter
   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
   RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
```
Podfile
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'farutexMobile' do
  pod 'AppCenter/Crashes', '~> 2.3.0'
  pod 'AppCenter/Analytics', '~> 2.3.0'
  pod 'AppCenterReactNativeShared', '~> 2.3.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for farutexMobile

  

  platform :ios, '9.0'

  target 'farutexMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'farutexMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for farutexMobile-tvOS

  target 'farutexMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
Will try downgrading the lib version...

**Comment by alex-mironov** [comment]
k, I've added 
```
AppCenterReactNativeCrashes
AppCenterReactNativeAnalytics
```
from `node_modules` to Libraries manually. Not sure if that is right approach to take but eventually it worked. 
Thanks for the support!

**Comment by russelarms** [comment]
I believe it should be fixed in the upcoming release. But anyway feel free to re-open this issue if you encounter this problem on the SDK version 2.4.0 or above.
Thanks for using AppCenter!

**Comment by effektsvk** [comment]
Just a small side note, if this happens on RN >=0.60 then you need to fix imports in `AppDelegate.m`. https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#311-integrate-react-native-ios

**Comment by martinattin** [comment]
after updating rn from 0.59 to 0.63 , i too got the same issue.I solved it .
prev my import statements in appdelegate.m were,


#import <AppCenterReactNativeCrashes/AppCenterReactNativeCrashes.h>
#import <AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNative/AppCenterReactNative.h>


after updating RN I changed it to 
#import <AppCenterReactNative.h>
#import <AppCenterReactNativeAnalytics.h>
#import <AppCenterReactNativeCrashes.h>
 
and error gone now.

**Comment by annakocheshkova** [comment]
Great! You can also refer to [this section](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#311-integrate-react-native-ios) which describes how the app should be integrated on RN >=0.60.
