### ISSUE TITLE
DemoApp not building for Android

### ISSUE THREAD

**Issue by codeithuman** [microsoft/appcenter-sdk-react-native#721]
The DemoApp in the repository is not building for Android. 

To reproduce, clone the repository and navigate to the DemoApp directory. 

The run the following:
```
npm install && npm run start
react-native run-android
```

When the Android app is building, you get the following error:

```
> Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED
/Users/aj/Projects/appcenter-sdk-react-native/DemoApp/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:36: error: cannot find symbol
import androidx.annotation.Nullable;
```

**Comment by annakocheshkova** [comment]
Hi there, DemoApp is for our internal testing, and we usually run **upgrade-appcenter-npm-packages.sh** before using it.
Is there any particular reason you want to use it?

**Comment by codeithuman** [comment]
I was having issues with App Center Push, and I was looking for an example to compare against my project. The related issue is, https://github.com/microsoft/appcenter-sdk-react-native/issues/720.

**Comment by annakocheshkova** [comment]
Ok. I would prefer to communicate on the original problem, but in this case - were you able to build using the script I mentioned?

**Comment by russelarms** [comment]
@codeithuman we made some fixes today regarding `react-native-gesture-handler` version, so could you pull the code from develop or master branch and try again?

**Comment by codeithuman** [comment]
Thanks for the quick replies. Unforchanetly I need to start work on another priority and will close this issue for now so it is not lingering.
