### ISSUE TITLE
Swift applications are not supported by react-native link

### ISSUE THREAD

**Issue by syq7970** [microsoft/appcenter-sdk-react-native#73]
After run react-native link, I get some Error:

`Added code to initialize iOS Crashes SDK in ios/DoctorApp/public/AppDelegate.m
(node:95889)`
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: pod init`
`(node:95889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

My project already has a podfile, so how could I fix this？ please help me. thanks

**Comment by syq7970** [comment]
Solved, because my AppDelegate file is not in project root path. And I suggest to support swift AppDelegate, like AppDelegate.swift.

**Comment by yaronlevi** [comment]
+1 for Switt support

**Comment by guperrot** [comment]
Since we had to support RN 0.60, react-native link does not alter AppDelegate.m anymore.
So this feature doesn't need to be done anymore (now the code to inject in AppDelegate is manual instructions).
