### ISSUE TITLE
signIn failed with appcenter-auth

### ISSUE THREAD

**Issue by callmejm** [microsoft/appcenter-sdk-react-native#731]
### **Description**

I tried to add login in my `react-native` app, but getting this error **Error: signIn is called while it's not configured.** when using `appcenter-auth'` in `react-native`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. i followed the instruction in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native 
2. because my `react-native` version is higher than `0.60` so after install i just add **appcenter-config.json** and **Modify the app's res/values/strings.xml**
3. then I followed this https://docs.microsoft.com/en-us/appcenter/sdk/auth/react-native
4. use the example script given in the site

```
import Auth from 'appcenter-auth';
async signIn() {
    try {
        const userInformation = await Auth.signIn();
        // Sign-in succeeded
        const accountId = userInformation.accountId;
    } catch (e) {
        // Do something with sign in failure.
    }
}

signIn();
```
5. i console.log the `catch` and get **Error: signIn is called while it's not configured.**

### **Details**
I very new in this library, so I not sure which step i stuck

**Comment by russelarms** [comment]
Hi, @callmejm!
This kind of error may happen if you didn't configure Azure B2C Tenant or didn't integrate it with AppCenter properly and therefore the SDK can't download a configuration file.
Did you follow [this document](https://docs.microsoft.com/en-us/appcenter/auth/getting-started)?

**Comment by russelarms** [comment]
We haven't heard back from you for a while, I'm closing this issue now but you can reopen it anytime you want.

**Comment by callmejm** [comment]
@russelarms Hi, sorry for late response, I had give up what i try, because I cannot stuck here
