### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) security vulnerability

### ISSUE THREAD

**Issue by jcomplex** [microsoft/appcenter-sdk-react-native#743]
### **Description**

The Regular expression Denial of Service (ReDoS) is a type of Denial of Service attack. Regular expressions are incredibly powerful, but they aren't very intuitive and can ultimately end up making it easy for attackers to take your site down. Currently, `appcenter-link-scripts` and uses version 2.2.0 and should be bumped to version 2.6.9, 3.1.0 or higher.

### **Details**

- Introduced through: appcenter@2.4.0 › appcenter-link-scripts@2.4.0 › debug@2.2.0
- Introduced through: appcenter-crashes@2.4.0 › appcenter@2.4.0 › appcenter-link-scripts@2.4.0 › debug@2.2.0

**Comment by russelarms** [comment]
Hi, @jcomplex!
Thank you for pointing out this vulnerability!
I've changed the debug version in the following PR:
https://github.com/microsoft/appcenter-sdk-react-native/pull/744

I'm closing this issue. Please reopen/comment if you have more details or have any other questions.

**Comment by dhei** [comment]
Hi @jcomplex,

Thanks for reaching out to us.

The fix (#744) of this bug was released in App Center RN SDK latest release https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/2.5.0.
