### ISSUE TITLE
Auth service hasn't been started. You need to call [MSAppCenter start:YOUR_APP_SECRET withServices:LIST_OF_SERVICES]

### ISSUE THREAD

**Issue by suresh777** [microsoft/appcenter-sdk-react-native#745]
I am integrating react native AppCenter-Auth plugin. I have done couple of things
1. i installed npm install appcenter-auth --save-exact
2. In Xcode pod install and added embedded library libappcenter-auth
3. Imported 
#import "AppCenterReactNativeAuth.h" in Appdelegate.m
added  [AppCenterReactNativeAuth register]; in didFinishLaunchingWithOptions
4. In info.plist i added msalXXXXXXXXXXXXXXXXXXXXXX in url schemes
5. i added this code in app.js 
 async signIn() {
        try {
            const userInformation = await Auth.signIn();
            // Sign-in succeeded
            const accountId = userInformation.accountId;
        } catch (e) {
            // Do something with sign in failure.
        }
    }

am i missing anything

**Comment by Jamminroot** [comment]
Hey, @suresh777, thanks for getting in touch.
You seem to have skipped initial App Center SDK integration steps: the error in ticket's caption (`Auth service hasn't been started. You need to call [MSAppCenter start:YOUR_APP_SECRET withServices:LIST_OF_SERVICES]`) means that AppCenter wasn't started with desired set of services. 
Please refer to official documentation's [Getting Started page](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native) for detailed instructions on how to integrate App Center SDK to your project.

**Comment by russelarms** [comment]
We haven't heard back from you for a while, so I'm closing this issue now but you can reopen with answers anytime you want. Thanks!
