### ISSUE TITLE
appcenter-push: how to change notification channel name and description?

### ISSUE THREAD

**Issue by heroandtn3** [microsoft/appcenter-sdk-react-native#755]
### **Description**

Hi, thanks for your great work. I'm using appcenter-push for push notification but I cannot find documentations any instructions to change the notification channel name and description. The current one is "Miscellaneous" as shown in the image below:

![image](https://user-images.githubusercontent.com/2512088/67620892-f5110800-f835-11e9-9b3f-ff3c330a8416.png)

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.5.0
2. Which OS version did you experience the issue on?
    - Android 10
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Google Pixel 2 emulator
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

```
System:
    OS: Linux 5.3 Arch Linux 
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.61.2 => 0.61.2
```

**Comment by guperrot** [comment]
Hi, AppCenter portal&backend does not currently support pushing the android channel name as a special custom data field. Also it would require to create the alternate channel in the application before the first push is triggered.

**Comment by guperrot** [comment]
What you can do if you always want to use the same channel is:

```
<meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="@string/default_notification_channel_id"/>
```

And declare a string resource with `default_notification_channel_id` key to use as a channel name.

Then in your MainApplication.java file use the `https://developer.android.com/reference/android/app/NotificationManager#createNotificationChannel(android.app.NotificationChannel)` API to create a channel with the resource name and configure it (you will need to test version code before using the API, Android Studio will assist you with a warning and a quick fix for that if check).

**Comment by heroandtn3** [comment]
@guperrot thanks for your quick response, I'm going to go with that solution.

**Comment by guperrot** [comment]
Closing here as the question was answered, feel free to reopen should you encounter issues with this approach.
