### ISSUE TITLE
Support for gradle 2.x

### ISSUE THREAD

**Issue by imanpeeman** [microsoft/appcenter-sdk-react-native#756]
When a new react-native application is created with react-native init the gradle version used is the latest on jcenter (jcenter()) which is gradle version 2.2.4. Unfortunately this version doesn't support the 'implementation' and 'api' keywords in the build.gradle file.

just changing 'implemenation' and 'api' to 'compile' doesn't work.

1. Which version of the App Center SDK are you using?
    - 2.5
2. Which OS version did you experience the issue on?
    - Building with windows / Gradle 2.2.4
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -
4. What third party libraries are you using?
    - Gradlew 2.2.4
5. Run the following command and paste the output below: `react-native info`
Environment:
  OS: Windows 10
  Node: 10.15.3
  Yarn: 1.16.0
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5791312

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0
Place output here

**Comment by annakocheshkova** [comment]
Hi there, when creating a new app with a new version of react-native, the gradle version is also new. Is there a particular reason you want to keep the old react-native version?
I don't think it would be a good idea to change new keywords in our sdk back to old, but could you elaborate why changing the keywords doesn't work for you?

**Comment by imanpeeman** [comment]
Hi, thanks for the response. 
When i create a new RN project (windows tooling) the default gradle is the jcenter() gradle implentation. There the highest version is 2.2.4. 
I've already tried changing the keyboards, but that doesn't work.

**Comment by annakocheshkova** [comment]
What is your react-native-cli version? 
What exactly does fail if you change the keyword?

**Comment by clpolet** [comment]
Hello there, I have tested running `react-native init testNewApp` on Windows and it used `react-native@0.61.2`. By looking at the generated build.gradle for the Android app I could see that it's using Gradle 3.4.2. 
I am wondering what pins you down to RN 0.52.0 and Gradle 2.0.
The thing is `compile` is deprecated so is unpredictable to use on newer versions and also generates warnings (cf: #501 ).

**Comment by annakocheshkova** [comment]
Hello, do you have any more updates? If so, please let us know and re-open the issue. Thanks!
