### ISSUE TITLE
RN60 autolinking issues

### ISSUE THREAD

**Issue by kristfal** [microsoft/appcenter-sdk-react-native#766]
### **Description**

While upgrading from RN59 to RN60, we migrated from manually linked to autolinked `appcenter`, `appcenter-crashes` and `appcenter-analytics`. The version of AppCenter installed is 2.5.0.

During this process, we encountered two issues with Autolinking while following the [getting started guide](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native).

a) iOS: Even while enabling `use_native_modules!`, `appcenter`, `appcenter-crashes` and `appcenter-analytics` had to be manually added to Podfile. Result:

```

  use_native_modules!

  # Other pods
  pod 'appcenter', :path => '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', :path => '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-crashes', :path => '../node_modules/appcenter-crashes/ios'
```

b) Android required [full manual linking](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#34-android-only-integrate-the-sdk-manually-for-react-native-lower-than-060-without-react-native-link)

With these changes, we were able to get it running.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Init a clean RN59.X project
2. Install and manually link AppCenter@2.2.0
3. Unlink and uninstall appcenter
4. Manually verify that no `appcenter` code or remains of 2.2.0 resides in `/android` folder 
5. Follow the [getting started guide](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)

**Comment by guperrot** [comment]
Hi, I understand the ask here is that we provide documentation for this upgrade process.
Indeed the getting started does not cover the upgrade scenario but only installing the App Center modules for the first time.
I am forwarding this feedback.

**Comment by dhei** [comment]
Thanks for the feedback.

We have added [How to upgrade app using App Center SDK from React Native 0.59 to 0.60](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-upgrade-app-using-app-center-sdk-from-react-native-059-to-060) documentation.
