### ISSUE TITLE
I don't think app centre should hard crash production users on calls to Analytics.trackEvent with 'badly formatted' second parameter

### ISSUE THREAD

**Issue by iamacup** [microsoft/appcenter-sdk-react-native#774]
### **Description**

We are seeing what AppCenter can do and to be honest, the analytics has been harder work than we would expect.

We dropped this code in:

```
const trackEvent = (name, properties) => {
  amplitudeInstance.logEvent(name, properties);
  Analytics.trackEvent(name, microsoftSafe(properties));
}
```

but ended up with this

```
import Dot from 'dot-object';

const microsoftSafe = (obj) => {
  const items = Dot.dot(obj);

  Object.keys(items).forEach((value) => {
    const item = items[value];

    if (typeof item !== 'string' && typeof item !== 'number' && typeof item !== 'boolean') {
      delete items[value];
    }
  });

  return items;
};

const trackEvent = (name, properties) => {
  amplitudeInstance.logEvent(name, properties);
  Analytics.trackEvent(name, microsoftSafe(properties));
}
```

Which reproduced the behaviour of Amplitude. 

My concern is that the default behaviour of the below method is always to throw a breaking error, on production.

It does not matter if your analytics lib fails to serialise some properties on production, you will see this problem in your analytics, but as it is you see crash analytics of AppCenter going through the roof because you badly formatted one of your analytics calls...

I am happy to open up a pull request to change the behaviour of `sanitizeProperties` to only error in debug builds, but would like some feedback from the community if this is a good idea or if maybe someone from the core project would pick it up?  

```
function sanitizeProperties(props = null) {
    // Only string:string mappings are supported currently.

    const result = {};
    if (props === null) {
        return result;
    }
    Object.keys(props).filter((key) => props[key] !== null).forEach((key) => {
        switch (typeof props[key]) {
            case 'string':
            case 'number':
            case 'boolean':
                result[key] = `${props[key]}`;
                break;
            case 'undefined':
                break;
            default:
                throw new Error('Properties cannot be serialized. Object must only contain strings');
        }
    });
    return result;
}
```

**Comment by guperrot** [comment]
Hi, this is a valid point and actually we have this in more recent code: https://github.com/microsoft/appcenter-sdk-react-native/blob/develop/appcenter/AppCenter.js#L123

**Comment by iamacup** [comment]
Ahh super - this is why i opened an issue for feedback instead of just making a ham fisted pull request :)

I assume AppCenterLog.error(...) will handle it based on environment etc.?

fantastic work!

**Comment by dhei** [comment]
Hi @iamacup,

Thanks for reporting this to us. Pull request is welcome.

> I assume AppCenterLog.error(...) will handle it based on environment etc.?
`AppCenterLog` API emits the different levels of native device log for diagnostic purpose (can be seen in Android Studio or Xcode console), and `AppCenterLog.error` emits the error level log.

**Comment by guperrot** [comment]
AppCenterLog is simply mapped to console APIs: console.warn and console.error.
We have a setLogLevel to configure what calls actually go through to filter (same as the native version of AppCenterLog).

In release logs are disabled by default but if you enable them you can see those logs in Console or Logcat depending on the platform.

In debug (specifically when using the local dev JS server), it will also trigger the additional behavior of RN: warning makes a yellow banner and error triggers an error screen (both can be dismissed).
