### ISSUE TITLE
Push notifications initially gets Bad channel status

### ISSUE THREAD

**Issue by bjarkof** [microsoft/appcenter-sdk-react-native#779]
### **Description**

When sending notifications the status we receive for it is initially "Bad channel", however all notifications seems to be delivered and eventually the status is removed in the Appcenter UI. The problem only seem to occour when sending to specific devices. 

### **Details**

1. Which version of the App Center SDK are you using?
    2.3.0
2. Which OS version did you experience the issue on?
    iOS

**Comment by MatkovIvan** [comment]
Hi @bjarkof,

Thanks for getting in touch!
Could you please specify the steps used to reproduce, information about used tools versions, and verbose logs from the device?
If you think that this is not client SDK problem, please open a support ticket in intercom instead (blue chat button in the corner on portal).

**Comment by annakocheshkova** [comment]
@bjarkof hi, I'm closing this issue for now. Feel free to re-open once you have more info. Thanks in advance!
