### ISSUE TITLE
Execution failed for task ':app:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by Arwantys** [microsoft/appcenter-sdk-react-native#780]
### **Description**

By installing the App Center SDK my application can no longer build for android, but for iOS no problem.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install new react-native project
2. run npm install appcenter appcenter-analytics appcenter-crashes --save-exact
3. react-native run-android

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.6.0
2. Which OS version did you experience the issue on?
    - Android 9, iOS 13
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Nexus 5X, iPhone 11 Pro physical device
4. What third party libraries are you using?
    - No
5. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 23.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
    react-native-gesture-handler: 1.4.1
    react-native-paper: 2.16.0
    react-native-reanimated: 1.2.0
    react-native-rename: 2.4.1
    react-native-scripts: 2.0.1
    react-native: 0.61.4

Thanks for help

**Comment by MatkovIvan** [comment]
Hi @Arwantys,

Thanks for getting in touch!
Could you please share full error message (or even full build log)? Currently the description doesn't contain this key info.

**Comment by Arwantys** [comment]
@MatkovIvan Oh yes I forgot, here's the mistake:

```
/Users/mathis/Développements/MWActuDev/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:94: error: cannot find symbol
      new AppCenterReactNativeAnalyticsPackage(getApplication(), getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
                                                                                                  ^
  symbol:   variable appCenterAnalytics_whenToEnableAnalytics
  location: class string
/Users/mathis/Développements/MWActuDev/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:95: error: cannot find symbol
      new AppCenterReactNativeCrashesPackage(getApplication(), getResources().getString(R.string.appCenterCrashes_whenToSendCrashes)),
                                                                                                ^
  symbol:   variable appCenterCrashes_whenToSendCrashes
  location: class string
/Users/mathis/Développements/MWActuDev/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:97: error: cannot find symbol
      new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG),
                                                    ^
  symbol:   variable reactNativeCodePush_androidDeploymentKey
  location: class string
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/mathis/Développements/MWActuDev/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by annakocheshkova** [comment]
Hi there @Arwantys, have you followed step number 2 [here](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#312-integrate-react-native-android)? Thing is, these settings values have to be created manually.

**Comment by Arwantys** [comment]
@annakocheshkova Actually it was that, I had to withdraw these lines because there was also a problem of compilation with the manual version, but with an unlink then a link everything works, thank you!

**Comment by RedEarthBlueSky** [comment]
I'm late to the party but here goes.  Read the details of the error code more carefully.  With me it was simply a link to an unistalled and unlinked package - react-native-pdf.  What I am finding atm is that when i uninstall and unlink packages do a search of the whole project to make sure there are no calls anywhere else.
