### ISSUE TITLE
The following build commands failed: CopyPlistFile

### ISSUE THREAD

**Issue by AhmedSamiEssayed** [microsoft/appcenter-sdk-react-native#791]
### **Description**

Hi, 
I have a problem when trying to build the app on IOS. I managed to link Microsoft Azure repo to my app on appcenter and when I am trying to build on IOS it gives me the error mentioned below.
Note: It works fine on android and doesn't produce this issue.
And also I enable "Use legacy build system" in build configuration.

**Error Message**
```
** ARCHIVE FAILED **
The following build commands failed:
	CopyPlistFile /Users/runner/Library/Developer/Xcode/DerivedData/MyApp-doqvtiutinyfgbgouwgkpjxgbfoc/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app/AppCenter-Config.plist /Users/runner/runners/2.163.1/work/1/untitled\ folder/AppCenter-Config.plist
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```
### **Repro Steps**
Please list the steps used to reproduce your issue.

1. I linked the app with Azure repo.
2. When I try to build for IOS, it failed and produce the error i mentioned above.

### **Details**

1. Which version of the App Center SDK are you using?
    - 2.6.1
2. Which OS version did you experience the issue on?
    - Android 10, iOS 13

5. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 228.27 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.5.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
- 1.8.4

**Comment by russelarms** [comment]
Hi! Thank you for getting in touch!
Could you please make sure that the `AppCenter-Config.plist` 
was added to your Xcode project: https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#311-integrate-react-native-ios
You build iOS from appcenter.ms **Build** tab, right? If that is the case, is it possible for you to try to build it locally?

**Comment by AhmedSamiEssayed** [comment]
Hi @russelarms 
Thanks for your fast respond!
Yes, I am trying to build the app from Build tab on appcenter.ms. I tried to build it locally and it builds successfully.
here's a screenshot for plist file, I did added it to the project
<img width="319" alt="Screen Shot 2019-12-23 at 3 05 08 PM" src="https://user-images.githubusercontent.com/22711584/71359683-05273880-2596-11ea-878a-b2d7ad7f4dd9.png">
Sorry I have to hide app name, I just wanted to clarify the file on app hierarchy.
Hope that help!

**Comment by russelarms** [comment]
@AhmedSamiEssayed just to be sure that we are on the same line: have you tried to _archive_ it locally?

**Comment by AhmedSamiEssayed** [comment]
@russelarms 
Yes, and I uploaded it also

**Comment by russelarms** [comment]
@AhmedSamiEssayed what Xcode version do you use locally?

**Comment by AhmedSamiEssayed** [comment]
@russelarms 
11.2.1

**Comment by russelarms** [comment]
@AhmedSamiEssayed 
Can you please file a support ticket with us so we can look into your specific issues and logs? https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us
Screenshot of the support icon on the bottom right of the screen when you load up appcenter.ms:
![chatbtn](https://user-images.githubusercontent.com/10907757/71411089-56e8c500-2661-11ea-80e9-84c7d8044ce2.png)

I'm closing this issue now as it seems unrelated to the SDK.

**Comment by luketgriffith** [comment]
@AhmedSamiEssayed We are having the same problem - were you able to solve this?

**Comment by annakocheshkova** [comment]
@luketgriffith could you please file a separate issue or open a ticket as @russelarms mentioned?

**Comment by sugaith** [comment]
same here xcode 11

**Comment by sugaith** [comment]
I fixed this issue deleting the *.plist file from the project and adding it again. In my case it was the GoogleService-Info.plist.

@AhmedSamiEssayed  The link to your file must be broken.

**Comment by nabilnalakath** [comment]
@AhmedSamiEssayed were you able to solve this issue? I am stuck with the same problem.

**Comment by russelarms** [comment]
@nabilnalakath have you tried this:
> I fixed this issue deleting the *.plist file from the project and adding it again.
?

**Comment by shawnzheng99** [comment]
I think its that when you add .plist file, right clicked 'AppName' -> Add files to 'AppName -> select .plist file. This only add .plist file reference to the project, not the .plist file itself.
If you open the project directory in Finder, it dose not contains the .plist file even it shows in the Xcode.

My solution was drag and drop this .plist file into project directory in Finder. 
It works.

**Comment by panrosk** [comment]
just had this issue. It was a typo in the config file
