### ISSUE TITLE
null is not an object (evaluating 'AppCenterReactNativePush.sendAndClearInitialNotification')

### ISSUE THREAD

**Issue by sayob** [microsoft/appcenter-sdk-react-native#793]
### **Description**

When I compile my project, I'm getting the following warning:
![Screenshot_1578429907](https://user-images.githubusercontent.com/10841598/71928070-1a57b600-3197-11ea-8458-606155c92d34.png)

This happens when I build my android project after adding `appcenter-push`

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Create a new React-Native project
2. Install `appcenter-push` 
3. Run `react-native run-android` after setting up all necessary instructions [here](https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-android) 

### **Details**

1. Which version of the App Center SDK are you using?
    "appcenter-push": "^2.6.1" 
    "appcenter": "2.6.1"
2. Which OS version did you experience the issue on?
     Android 9.0
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    Google Pixel 2 emulator
4. What third party libraries are you using?
    
5. Run the following command and paste the output below: `react-native info`

React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 160.35 MB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5900203
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by jaelim-ms** [comment]
Can you provide me the code how you set up App Center in your app? Looks like your SDK setup isn't correct. It would be good if you can share your repository (if it is public) or at least the code that you configure App Center SDK.

**Comment by sayob** [comment]
@jaeklim [Here](https://github.com/sayob/react-native-startup-project/tree/pushNotification) is the repo

**Comment by ilyashumihin** [comment]
@sayob thanks for sharing the sample!

As I see you add sdk manually, but do not connect the push package.
Please, follow next steps:

1. In app level build.gradle file add this lines into dependencies section:
```
dependencies {
  implementation project(':appcenter-push') 
  ...
}
``` 
2. Include the dependencies that you want in your project. Open android/settings.gradle file and insert the following lines:
``` 
include ':appcenter-push'
project(':appcenter-push').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-push/android') 
```
3. Modify the app's MainApplication.java file to include code for Push SDK:
`import com.microsoft.appcenter.reactnative.push.AppCenterReactNativePushPackage;`
4. Add this package to the List<ReactPackage> getPackages() inside MainApplication.java
```
@Override
protected List<ReactPackage> getPackages() {
     return Arrays.<ReactPackage>asList(
     ...
     new AppCenterReactNativePushPackage(MainApplication.this),
     ...
     )
}
```

**Comment by annakocheshkova** [comment]
Hey, do you have any updates? If so, please let us know and reopen the issue. Thanks!
