### ISSUE TITLE
How to detect if notification clicked?

### ISSUE THREAD

**Issue by abdallaemadeldin** [microsoft/appcenter-sdk-react-native#794]
### **Description**

I need to know when the user click the notification to perform a specific action according to the data

**Comment by abdallaemadeldin** [comment]
@theill @axemclion @brannon @DanRigby 
please help me

**Comment by MatkovIvan** [comment]
It's documented here - https://docs.microsoft.com/en-us/appcenter/sdk/push/react-native-ios#detecting-when-a-user-has-tapped-on-a-push-notification

Also, it's already discussed in #375 and #381

@abdallaemadeldin please, check the linked resources.

Closing as duplicate, but feel free to reopen the issue if you have more questions.
