### ISSUE TITLE
Typescript iOS build failed with Generate source map section

### ISSUE THREAD

**Issue by pavinthan** [microsoft/appcenter-sdk-react-native#797]
I try to build react-native ios app (codebase in typescript) but build failed with error Unable to resolve module `./src/navigator` from `App.tsx`:  but I have `index.tsx` file inside the `./src/navigator`.

Project structure
<img width="421" alt="Screen Shot 2020-01-31 at 10 50 13 AM" src="https://user-images.githubusercontent.com/13897936/73514391-8e445180-4417-11ea-8f4a-ff24155aabab.png">

babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          '~': './',
          '@': './src/',
        },
      },
    ],
  ],
};
```

tsconfig.json
```
...
"moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    "baseUrl": "./" /* Base directory to resolve non-absolute module names. */,
    "paths": {
      "~/*": ["*"],
      "@/*": ["src/*"]
    } /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */,
...
```

App.ts
```
...
import Navigator from '@/navigator';
...
```

##[section]Starting: Generate source map
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.163.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
========================== Starting Command Output ===========================
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:1540) Warning: Use Cipheriv for counter mode of aes-256-ctr
[command]/bin/bash --noprofile --norc /Users/runner/runners/2.164.6/work/_temp/04e00a29-c524-4680-946c-1a4b5da80ab7.sh
Found index.js for ReactNative index.
warning: the transform cache was reset.
Loading dependency graph, done.
error Unable to resolve module `./src/navigator` from `App.tsx`: 

None of these files exist:
  * src/navigator(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * src/navigator/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx). Run CLI with --verbose flag for more details.
Error: Unable to resolve module `./src/navigator` from `App.tsx`: 

None of these files exist:
  * src/navigator(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * src/navigator/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/runner/runners/2.164.6/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
##[error]Bash exited with code '1'.
##[section]Finishing: Generate source map

**Comment by AnastasiaKubova** [comment]
Hi, @pavinthan ! Thanks for getting in touch with us.
I’m don’t see any points related to App Center SDK. Could you please clarify how exactly App Center SDK effects this issue?

**Comment by Jamminroot** [comment]
Hey! 
We haven’t heard from you in a while, do you have any more questions? If so, please reopen the issue and let us know.  
Thanks for using App Center!

**Comment by pavinthan** [comment]
@AnastasiaKubova and @Jamminroot  I resolve the issue by removeing `.git` and repository folder and reinstall `.git` repository, sorry the issue from my `git` history.

Thanks for your actions.

**Comment by Marcuspo** [comment]
same error

**Comment by DmitriyKirakosyan** [comment]
Hi @Marcuspo , do you build the app locally or on the App Center portal?
If you face this error when building on the portal, please reach out to the [support team](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) with this question.
If you build the app locally, then please add more details on how exactly it is related to the AppCenter SDK.

**Comment by Marcuspo** [comment]
In App center portal
