### ISSUE TITLE
add support for React Native Windows

### ISSUE THREAD

**Issue by matthargett** [microsoft/appcenter-sdk-react-native#8]
We are shipping a desktop application using React Native Windows, and want to evaluate using Mobile Center. Is Mobile Center totally incompatible with Windows applications, or does someone just need to do the work to make it react-native-windows friendly? /cc @rozele

**Comment by quincycs** [comment]
@matthargett  i suppose they'll need to first support any UWP application first.  i know that is planned, but they havn't released an SDK for UWP yet.  Once that is out, I'd suppose someone needs to write the native module for it.

**Comment by BretJohnson** [comment]
@quincycs is right--Mobile Center support for Windows is definitely on the road map, and once that's available we'll provide support for React Native UWP apps soon after.

**Comment by matthargett** [comment]
Shouldn't this issue stay open, then?

**Comment by kozorezal** [comment]
According to https://docs.microsoft.com/en-us/appcenter/sdk/analytics/uwp app center supports analytics for UWP. Is there any plans on providing support for react-native for Windows?
Thanks

**Comment by elamalani** [comment]
@kozorezal It isn't in our mid-term roadmap to support React Native Windows platform. We will keep this thread posted if we decide to prioritize the platform support in App Center.

**Comment by vmoroz** [comment]
We have two "virtual interns" @avmoroz and @alexmoroz15 working this summer on implementing the ReactNative for Windows AppCenter modules for analytics and crashes. Currently they work on implementing the Demo App that uses .Net SDK and the new C# native modules based on https://microsoft.github.io/react-native-windows/docs/native-modules instructions. There are a few questions:
- What is the best way to implement tests? There are test apps, but it is not clear how to use or extend them for UWP apps.
- What are the expectations for the pull requests? Should they do a gigantic PR in the end or it is acceptable to submit work in progress with functional bits?

**Comment by matthargett** [comment]
Thanks for taking this on, I think this will help people who are still shipping React Native Windows apps (like @pre10der89
and the Xbox desktop app team). @acoates-ms or @rozele can probably comment on how to unit test the new modules and how they'd like the incoming changes to be split up.

**Comment by rtorr** [comment]
Any updates on this? Will it support winui3?

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
