### ISSUE TITLE
Pods aren't installing / auto-linking, preventing from building.

### ISSUE THREAD

**Issue by nandorojo** [microsoft/appcenter-sdk-react-native#803]
### **Description**

It seems like the pods aren't installing/autolinking on my project. When I try to run the app, it says that the pods aren't found:

![Screen Shot 2020-02-18 at 6 07 37 PM](https://user-images.githubusercontent.com/13172299/74785950-93a7f580-5279-11ea-9ab8-ed3977c0d4d2.png)

Meanwhile, if I try `react-native link appcenter`, I get this message after running `pod install`:
![Screen Shot 2020-02-18 at 6 08 54 PM](https://user-images.githubusercontent.com/13172299/74786024-c05c0d00-5279-11ea-9950-db1a22239de0.png)

I am running `react-native 0.61.4`, so I'm not sure why it isn't auto-linking.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Follow [installation instructions](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#33-ios-only-integrate-the-ios-sdk-manually-without-react-native-link-or-cocoapods)
2. Run `npx react-native run-ios`.

My `AppDelegate.m` gives me these errors:

<img width="708" alt="Screen Shot 2020-02-18 at 6 21 21 PM" src="https://user-images.githubusercontent.com/13172299/74787105-4e38f780-527c-11ea-8458-71dc87c2a457.png">

<img width="710" alt="Screen Shot 2020-02-18 at 6 21 54 PM" src="https://user-images.githubusercontent.com/13172299/74787104-4da06100-527c-11ea-9a51-7ff6cf768086.png">

Here's what I see when I run `pod install`:

![Screen Shot 2020-02-18 at 6 04 22 PM](https://user-images.githubusercontent.com/13172299/74785797-2b591400-5279-11ea-8e43-a9790110619b.png)

And this is my `Podfile`:

![Screen Shot 2020-02-18 at 6 05 25 PM](https://user-images.githubusercontent.com/13172299/74785822-3f9d1100-5279-11ea-9e45-0f022bd79e7d.png)

### **Details**

1. Which version of the App Center SDK are you using?
```JSON
    "appcenter": "2.6.1",
    "appcenter-analytics": "2.6.1",
    "appcenter-crashes": "2.6.1",
```
**2. Which OS version did you experience the issue on?**
`iOS 13.3.1`

**3. What device version did you see this error on?  Were you using an emulator or a physical device?**
`iPhone 11 Simulator, and iPhone X device`

**4. What third party libraries are you using?**

![Screen Shot 2020-02-18 at 5 58 47 PM](https://user-images.githubusercontent.com/13172299/74785440-53944300-5278-11ea-8f81-39f547a45c59.png)

`package.json`

![Screen Shot 2020-02-18 at 5 58 35 PM](https://user-images.githubusercontent.com/13172299/74785452-5d1dab00-5278-11ea-806b-9f435dd446a9.png)

**5. Run the following command and paste the output below: `react-native info`**

![Screen Shot 2020-02-18 at 6 12 38 PM](https://user-images.githubusercontent.com/13172299/74786266-48daad80-527a-11ea-879e-2b7bb938f840.png)

**6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`**

`1.8.4`

**7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:**

Build won't work.

<img width="714" alt="Screen Shot 2020-02-18 at 6 29 13 PM" src="https://user-images.githubusercontent.com/13172299/74787196-92c49300-527c-11ea-881a-acc92f397c15.png">

**Comment by olmisa** [comment]
Hi @nandorojo, I was not able to reproduce this issue. Looks like 'AppCenter' node modules were not installed. Could you, please, check that 'node_modules' folder (folder near 'ios' and 'android' project subfolders) contains 'App Center' modules? 
Could you, please, provide more detailed repro steps? I used today the same installation instructions and all works for me.
Thanks

**Comment by nandorojo** [comment]
Sure thing, I’ll try that again! That said, I only need code push, and I managed to get that to work with only the code push library and app center cli. I’ll close this for now, and will follow up if the problem persists. Thanks for your help!
