### ISSUE TITLE
iOS frameworks version mismatch in docs

### ISSUE THREAD

**Issue by zinoviev** [microsoft/appcenter-sdk-react-native#807]
Hi there, 

at this moment Appcenter ios frameworks from https://github.com/Microsoft/AppCenter-SDK-Apple/releases is version 3 and react native framework SDK from https://github.com/Microsoft/appcenter-sdk-react-native/releases/latest is version 2, npm libraries is also version 2 and seems they all don't work together.

I follow "Integrate the SDK manually for React Native lower than 0.60 without react-native link or CocoaPods" manual and struggle for hours with with Xcode linking error at compile time:

`
Undefined symbol: _OBJC_CLASS_$_MSAuthTokenContext
`

As I download version 2 of iOS frameworks from december'19 code compiles succesfully

**Comment by MatkovIvan** [comment]
Hi Igor,

A new version of the App Center React-Native SDK compatible with version 3.0 will be release soon. Please use the SDK with the same major version for now.

Closing as you already managed to solve this issue by using the right version.

**Comment by MatkovIvan** [comment]
BTW the current version of docs includes the note about it:

>  The latest App Center React Native SDK doesn't necessarily depend on the latest App Center iOS SDK, because the iOS SDK is updated and released before the React Native one.
