### ISSUE TITLE
Build is failing after update appcenter version 3.0.0

### ISSUE THREAD

**Issue by Pruthvinreddy** [microsoft/appcenter-sdk-react-native#809]
Downloading dependencies
Installing AppCenter 3.0.0 (was 2.5.3 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing AppCenterReactNativeShared 3.0.0 (was 2.6.1 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing appcenter-analytics 3.0.0 (was 2.6.1)
Installing appcenter-core (3.0.0)
Installing appcenter-crashes 3.0.0 (was 2.6.1)
Installing react-native-webview 8.1.0 (was 8.1.1)
Removing appcenter
Generating Pods project
[!] Attempt to read non existent folder `/Users/runner/runners/2.165.0/work/1/s/ios/Pods/AppCenter`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
##[error]/bin/sh failed with return code: 1
##[error]/bin/sh failed with error: /bin/sh failed with return code: 1

**Comment by Jamminroot** [comment]
Hello, does it only occur on update? As in: can it be reproduced on your side with clean project?

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, so I'm closing the issue. Face you the problem again - please respond in this thread.
Have a nice day.
