### ISSUE TITLE
App Center Push Retirement

### ISSUE THREAD

**Issue by jdnichollsc** [microsoft/appcenter-sdk-react-native#811]
### **Description**
I want to know about the future of [appcenter-push](https://www.npmjs.com/package/appcenter-push) package, if we need to migrate to another solution and what's the suggestion here?

### **Details**

1. The logs from `AppCenter` portal:
>App Center Push Retirement
>We are retiring the App Center Push service. To learn more about how this announcement impacts you and the next steps involved, refer to the App Center blog.

2. This anouncement: https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/

Let us know and thanks in advance!

**Comment by jwargo** [comment]
@jdnichollsc there is no future for the appcenter-push package, it's been pulled from the SDK and the service is shutting down. As we described in the blog post, we recommend customers migrate to Azure Notification Hubs and we'll publish a migration guide soon.

**Comment by jdnichollsc** [comment]
ok, thanks!
