### ISSUE TITLE
Set version number in SDK programmatically

### ISSUE THREAD

**Issue by arlyon** [microsoft/appcenter-sdk-react-native#829]
**Is your feature request related to a problem? Please describe.**

I am using expo-updates to distribute new versions of my app, meaning new versions can be published without having to swap out the `versionName`, `versionCode`, `CFBundleVersion` or `CFBundleShortVersionString` etc.

To get a good picture of the usage, it would be useful to be able to set the version number programmatically rather than from what I can only presume to be the android version code.

**Describe the solution you'd like**

It would be great if we are able to set the version of a session programmatically so that the analytics accurately model what versions are _actually_ deployed.

**Describe alternatives you've considered**

I've considered using CodePush but would like to keep inside the expo ecosystem if possible.

**Comment by MatkovIvan** [comment]
Thanks for getting in touch!
We already have similar request for another platform - https://github.com/microsoft/appcenter/issues/1313 and I guess it makes sense to combine it because this requires changes in our native (Android/iOS) SDKs anyway.

**Comment by arlyon** [comment]
Thanks for the link. Happy to close this if you want to. For now, we're just disregarding the version number and using events to keep track.

**Comment by annakocheshkova** [comment]
Tracking this in https://github.com/microsoft/appcenter/issues/1313
