### ISSUE TITLE
Analytics.trackEvent should allow boolean | number | undefined in event property value

### ISSUE THREAD

**Issue by NullPainter2** [microsoft/appcenter-sdk-react-native#843]
Hi,

This is Analytics.trackEvent type 
```
export function trackEvent(     
    eventName: string,     
    properties?: {[p: string]: string} | undefined): Promise<void>
```

Internally Azure allows numbers, booleans and undefined values to be there and I have to work around this typing with extra code on my side. 

They are converted to string, so why not allow them? :)

```
function sanitizeProperties(props = null) {
    // Only string:string mappings are supported currently.

    const result = {};
    if (props === null) {
        return result;
    }
    Object.keys(props).filter((key) => props[key] !== null).forEach((key) => {
        switch (typeof props[key]) {
            case 'string':
            case 'number':
            case 'boolean':
                result[key] = `${props[key]}`;
                break;
            case 'undefined':
                break;
            default:
                throw new Error('Properties cannot be serialized. Object must only contain strings');
        }
    });
    return result;
}
```

### **Details**

1. Which version of the App Center SDK are you using?
    3.0.3

**Comment by vvechkanov** [comment]
Hi, @xchmelmilos! Thanks for getting in touch with us.
Thank you for suggesting these changes. I will mark this as a feature request. As I see you already write a great workaround, using string to send this value to the portal.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
