### ISSUE TITLE
build error 65 on appcenter-ios - RN app with typescript enabled.

### ISSUE THREAD

**Issue by thiagobucca** [microsoft/appcenter-sdk-react-native#855]
### **Description**

Hello, i'm having trouble with Appcenter on a React Native 0.62 app with typescript enabled, when i build my app via appcenter dashboard, the build output can't find my internal components, please check the log output for further info.

Things that i've already tried:

1 - Manually generate **ios/main.jsbundle and ios/assets files** and linking on bundle
2 - Check Build Phases for react-native-xcode.sh script
3 - Clearing Cache and removing/reinstalling node modules and Pods

Any help on this? My app build and run normaly on simulator and physical device, i only get this problem when trying to build on appcenter panel.

### **Repro Steps**

1. Build app with typescript enabled on appcenter dashboard
2. Check build output

### **Details**

1. Which version of the App Center SDK are you using?
    - latest
2. Which OS version did you experience the issue on?
    - iOS 13
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    appcenter, the issue doesn't happen on simulator or physical device
4. What third party libraries are you using?
    - example
5. Run the following command and paste the output below: `react-native info`

`info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.48 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.2, 28.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found`

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

`1.8.4`

Logs:

```
`error Unable to resolve module `pages/Tasks/TasksPageComponent` from `src/App.tsx`: pages/Tasks/TasksPageComponent could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*. Run CLI with --verbose flag for more details.
Error: Unable to resolve module `pages/Tasks/TasksPageComponent` from `src/App.tsx`: pages/Tasks/TasksPageComponent could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/runner/work/1/s/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/runner/work/1/s/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/runner/work/1/s/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
+ [[ false != true ]]
+ [[ ! -f /Users/runner/Library/Developer/Xcode/DerivedData/ReliefyApp-fkjjbbwnbpeblgdtglzalchiuftg/Build/Intermediates.noindex/ArchiveIntermediates/ReliefyApp/BuildProductsPath/Release-iphoneos/Reliefy.app/main.jsbundle ]]
+ echo 'error: File /Users/runner/Library/Developer/Xcode/DerivedData/ReliefyApp-fkjjbbwnbpeblgdtglzalchiuftg/Build/Intermediates.noindex/ArchiveIntermediates/ReliefyApp/BuildProductsPath/Release-iphoneos/Reliefy.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/runner/Library/Developer/Xcode/DerivedData/ReliefyApp-fkjjbbwnbpeblgdtglzalchiuftg/Build/Intermediates.noindex/ArchiveIntermediates/ReliefyApp/BuildProductsPath/Release-iphoneos/Reliefy.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
+ exit 2

warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 6.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'OpenSSL-Universal' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 5.0, but the range of supported deployment target versions is 8.0 to 13.6.99. (in target 'CocoaAsyncSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'armv7' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'armv7' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'armv7' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
warning: no rule to process file '/Users/runner/work/1/s/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/ReliefyApp-fkjjbbwnbpeblgdtglzalchiuftg/Build/Intermediates.noindex/ArchiveIntermediates/ReliefyApp/IntermediateBuildFilesPath/ReliefyApp.build/Release-iphoneos/ReliefyApp.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (not signed)
##[section]Starting: Xcode build (not signed)`
```

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Not sure that it related to SDK. Could you please open an Intercom ticket with this issue (question mark on the right top corner on the App Center portal).
Thanks

**Comment by KawaljeetSBagga** [comment]
@thiagobucca were you able to overcome this? If yes, how?

**Comment by Jamminroot** [comment]
Hey @KawaljeetSBagga, I think the problem was in babel.config.js file, it was not translating correctly the paths in the application. It was running fine locally but failed on  App Center portal.
Can you check, if that's the problem for you? If it's not, it'd be great if you shared details regarding the problem.

**Comment by KawaljeetSBagga** [comment]
Before updating 'react-native' version to 0.63, the build was Archiving successfully on my local machine, but **not** on App center. It was still failing to archive on app center. And when I upgraded the version to 0.63 on my local, it started failing even on my local machine with the **same** error that I got from App Center. The error is as below: 

> ** ARCHIVE FAILED **


> The following build commands failed:
> 	PhaseScriptExecution [CP-User]\ Config\ codegen /Users/runner/Library/Developer/Xcode/DerivedData/member_app-asdvtfmtttbmzebymgoozuysrbhi/Build/Intermediates.noindex/ArchiveIntermediates/member_app/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-config.build/Script-022AB83FD5413275A802AD409F1B2A1B.sh
> (1 failure)
> ##[error]Error: /usr/bin/xcodebuild failed with return code: 65

**Comment by Jamminroot** [comment]
Can you open a ticket in the intercom? You can do it from appcenter.ms portal, in top-right corner
![image](https://user-images.githubusercontent.com/6387654/98687475-36158500-2383-11eb-89b7-da5140ce726a.png)
