### ISSUE TITLE
Send push notification from mobile device

### ISSUE THREAD

**Issue by Yoruba** [Microsoft/AppCenter-SDK-React-Native#86]
Is it possible to send push notification with mobile-center from a mobile device?
If yes, how?
If no, are there plans for implementing this feature?

Thanks, Adri

**Comment by dhei** [comment]
Hello @Yoruba,

Today mobile center supports sending push notifications from the mobile center portal(https://mobile.azure.com). I am not sure if I understand your question, what do you mean by "send push notification from mobile device"? Can you explain your scenario a little bit? 

Thanks

**Comment by Yoruba** [comment]
Thanks for you response, is it possible to send a push notification from a React Native app to other app users.   

Scenario;
App user create and sends a notification message within the app.
Other app users see this message as notification message within the app.

Thanks, Adri

**Comment by dfoulk** [comment]
@dhei - I was under the impression that we could send push notifications via the Mobile Center Client API?

I am trying to use [the documentation](https://docs.mobile.azure.com/api/#/push/Push_Send) to learn how to do this, but I've hit a bit of a wall. When I send a notification via this API, it is added to Mobile Center- but not sent to our devices... Am I misunderstanding the purpose of this API?

Thanks,
-Derek

**Comment by dhei** [comment]
@dfoulk Do you mean that you didn't get push notifications on devices but saw push notifications history on mobile center portal? 

Just double checking, are you able to get push notifications on device when sent from mobile center portal?

**Comment by dfoulk** [comment]
@dhei Correct, I do not receive push notifications on my devices, but I do see them listed in Mobile Center (when I send a push notification via the Mobile Center Client API).

When I send the push notification from the Mobile Center web portal, I see the notifications listed in Mobile AND I receive them on the devices.

I am trying to send push notifications from a backend we are hosting locally using the Mobile Center API (not the Mobile Center web portal). We need to generate push notifications and send them without using the Mobile Center web portal.

**Comment by MehrdadMzfr** [comment]
@dfoulk , can you please share the payload you used to send push via API?
also, can you please contact us on Intercom from Mobile Center portal and share your app secret so that we can take a closer look?

**Comment by dfoulk** [comment]
Will do! I'll get that to you on monday morning. My JSON payload:

	https://api.mobile.azure.com/v0.1/apps/MyOrg/MyApp/push/notifications

	No Auth

	Accept: application/json
	X-API-Token: MyToken12345
	Content-Type: application/json

	{
		"notification_target": {
			"type": "NotificationTarget"
		},
		"notification_content": {
			"name": "From Postman",
			"title": "Title",
			"body": "Body",
			"custom_data": {
				"Key 1": "Value 1",
				"Key 2": "Value 2",
				"Key 3": "Value 3"
			}
		}
	}

**Comment by guperrot** [comment]
REST API issue tracked in intercom.
Not a SDK issue so closing here.

**Comment by dfoulk** [comment]
Definitely not an issue with the SDK. For anyone who comes across this thread, the following works for me:

https://api.mobile.azure.com/v0.1/apps/MyOrg/MyApp/push/notifications

No Auth

Accept: application/json
X-API-Token: MyToken12345
Content-Type: application/json

{
	"notification_target": null,
	"notification_content": {
		"name": "From Postman",
		"title": "Title",
		"body": "Body",
		"custom_data": {
			"Key 1": "Value 1",
			"Key 2": "Value 2",
			"Key 3": "Value 3"
		}
	}
}

Note the "notification_target" property... Had to set that bad boy to NULL. I'm sure that property also accepts an ID for an audience segment (or similar) also- but I just wanted to send a notification to all devices.

We constructed an SQL trigger that executes an EXE, which constructs and sends the above API call: BOOM! Super awesome push notifications that let our users know something has changed in our data!

Thanks guys- and congrats on the launch yesterday!
