### ISSUE TITLE
React Native: 'AppCenterCrashes/MSACErrorReport.h' file not found

### ISSUE THREAD

**Issue by ulrichsi-hrbl** [microsoft/appcenter-sdk-react-native#878]
### **Description**

'AppCenterCrashes/MSACErrorReport.h' file not found

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. npm install appcenter appcenter-crashes appcenter-analytics
2. pod install
3. xcode clean
4. xcode build
5. build fails

### **Details**

1. Which version of the App Center SDK are you using?
   4.0
2. Which OS version did you experience the issue on?
    Catalina 10.15.7
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - n/a
4. What third party libraries are you using?
    - vanilla typescript 
5. Run the following command and paste the output below: `react-native info`
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 819.98 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.2, 27.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_151 - /usr/bin/javac
    Python: 3.7.4 - /Users/ulrichsinn/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.10.0

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by ulrichsi-hrbl** [comment]
![Uploading Screen Shot 2020-11-20 at 6.47.46 PM.png…]()

**Comment by ulrichsi-hrbl** [comment]
![Screen Shot 2020-11-20 at 6 47 46 PM](https://user-images.githubusercontent.com/67665288/99865949-29064c00-2b62-11eb-925a-39bf4fab7de7.png)

**Comment by ulrichsi-hrbl** [comment]
also:
npm ERR! accenter-crashes-4@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the accenter-crashes-4@0.0.1 android script.

**Comment by CyberMew** [comment]
Can you show your Podfile.lock?

**Comment by ulrichsi-hrbl** [comment]
PODS:
  - appcenter-analytics (4.0.0):
    - AppCenter/Analytics
    - AppCenterReactNativeShared
    - React-Core
  - appcenter-core (4.0.0):
    - AppCenterReactNativeShared
    - React-Core
  - appcenter-crashes (4.0.0):
    - AppCenter/Crashes
    - AppCenterReactNativeShared
    - React-Core
  - AppCenter/Analytics (3.3.4):
    - AppCenter/Core
  - AppCenter/Core (3.3.4)
  - AppCenter/Crashes (3.3.4):
    - AppCenter/Core
  - AppCenterReactNativeShared (3.1.2):
    - AppCenter/Core (= 3.3.4)
  - boost-for-react-native (1.63.0)
  - CocoaAsyncSocket (7.6.4)
  - CocoaLibEvent (1.0.0)
  - DoubleConversion (1.1.6)
  - FBLazyVector (0.63.2)
  - FBReactNativeSpec (0.63.2):
    - Folly (= 2020.01.13.00)
    - RCTRequired (= 0.63.2)
    - RCTTypeSafety (= 0.63.2)
    - React-Core (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - Flipper (0.41.5):
    - Flipper-Folly (~> 2.2)
    - Flipper-RSocket (~> 1.1)
  - Flipper-DoubleConversion (1.1.7)
  - Flipper-Folly (2.3.0):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.20)
  - Flipper-Glog (0.3.6)
  - Flipper-PeerTalk (0.0.4)
  - Flipper-RSocket (1.1.0):
    - Flipper-Folly (~> 2.2)
  - FlipperKit (0.41.5):
    - FlipperKit/Core (= 0.41.5)
  - FlipperKit/Core (0.41.5):
    - Flipper (~> 0.41.5)
    - FlipperKit/CppBridge
    - FlipperKit/FBCxxFollyDynamicConvert
    - FlipperKit/FBDefines
    - FlipperKit/FKPortForwarding
  - FlipperKit/CppBridge (0.41.5):
    - Flipper (~> 0.41.5)
  - FlipperKit/FBCxxFollyDynamicConvert (0.41.5):
    - Flipper-Folly (~> 2.2)
  - FlipperKit/FBDefines (0.41.5)
  - FlipperKit/FKPortForwarding (0.41.5):
    - CocoaAsyncSocket (~> 7.6)
    - Flipper-PeerTalk (~> 0.0.4)
  - FlipperKit/FlipperKitHighlightOverlay (0.41.5)
  - FlipperKit/FlipperKitLayoutPlugin (0.41.5):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutTextSearchable
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutTextSearchable (0.41.5)
  - FlipperKit/FlipperKitNetworkPlugin (0.41.5):
    - FlipperKit/Core
  - FlipperKit/FlipperKitReactPlugin (0.41.5):
    - FlipperKit/Core
  - FlipperKit/FlipperKitUserDefaultsPlugin (0.41.5):
    - FlipperKit/Core
  - FlipperKit/SKIOSNetworkPlugin (0.41.5):
    - FlipperKit/Core
    - FlipperKit/FlipperKitNetworkPlugin
  - Folly (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - Folly/Default (= 2020.01.13.00)
    - glog
  - Folly/Default (2020.01.13.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - OpenSSL-Universal (1.0.2.20):
    - OpenSSL-Universal/Static (= 1.0.2.20)
  - OpenSSL-Universal/Static (1.0.2.20)
  - RCTRequired (0.63.2)
  - RCTTypeSafety (0.63.2):
    - FBLazyVector (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTRequired (= 0.63.2)
    - React-Core (= 0.63.2)
  - React (0.63.2):
    - React-Core (= 0.63.2)
    - React-Core/DevSupport (= 0.63.2)
    - React-Core/RCTWebSocket (= 0.63.2)
    - React-RCTActionSheet (= 0.63.2)
    - React-RCTAnimation (= 0.63.2)
    - React-RCTBlob (= 0.63.2)
    - React-RCTImage (= 0.63.2)
    - React-RCTLinking (= 0.63.2)
    - React-RCTNetwork (= 0.63.2)
    - React-RCTSettings (= 0.63.2)
    - React-RCTText (= 0.63.2)
    - React-RCTVibration (= 0.63.2)
  - React-callinvoker (0.63.2)
  - React-Core (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.2)
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/CoreModulesHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/Default (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/DevSupport (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.2)
    - React-Core/RCTWebSocket (= 0.63.2)
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - React-jsinspector (= 0.63.2)
    - Yoga
  - React-Core/RCTActionSheetHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTAnimationHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTBlobHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTImageHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTLinkingHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTNetworkHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTSettingsHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTTextHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTVibrationHeaders (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-Core/RCTWebSocket (0.63.2):
    - Folly (= 2020.01.13.00)
    - glog
    - React-Core/Default (= 0.63.2)
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-jsiexecutor (= 0.63.2)
    - Yoga
  - React-CoreModules (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.2)
    - React-Core/CoreModulesHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-RCTImage (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-cxxreact (0.63.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-callinvoker (= 0.63.2)
    - React-jsinspector (= 0.63.2)
  - React-jsi (0.63.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-jsi/Default (= 0.63.2)
  - React-jsi/Default (0.63.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
  - React-jsiexecutor (0.63.2):
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
  - React-jsinspector (0.63.2)
  - react-native-safe-area-context (0.7.3):
    - React
  - react-native-splash-screen (3.2.0):
    - React
  - React-RCTActionSheet (0.63.2):
    - React-Core/RCTActionSheetHeaders (= 0.63.2)
  - React-RCTAnimation (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.2)
    - React-Core/RCTAnimationHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTBlob (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - React-Core/RCTBlobHeaders (= 0.63.2)
    - React-Core/RCTWebSocket (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-RCTNetwork (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTImage (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.2)
    - React-Core/RCTImageHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - React-RCTNetwork (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTLinking (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - React-Core/RCTLinkingHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTNetwork (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.2)
    - React-Core/RCTNetworkHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTSettings (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - RCTTypeSafety (= 0.63.2)
    - React-Core/RCTSettingsHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - React-RCTText (0.63.2):
    - React-Core/RCTTextHeaders (= 0.63.2)
  - React-RCTVibration (0.63.2):
    - FBReactNativeSpec (= 0.63.2)
    - Folly (= 2020.01.13.00)
    - React-Core/RCTVibrationHeaders (= 0.63.2)
    - React-jsi (= 0.63.2)
    - ReactCommon/turbomodule/core (= 0.63.2)
  - ReactCommon/turbomodule/core (0.63.2):
    - DoubleConversion
    - Folly (= 2020.01.13.00)
    - glog
    - React-callinvoker (= 0.63.2)
    - React-Core (= 0.63.2)
    - React-cxxreact (= 0.63.2)
    - React-jsi (= 0.63.2)
  - RNCAsyncStorage (1.12.1):
    - React-Core
  - RNCMaskedView (0.1.10):
    - React
  - RNGestureHandler (1.8.0):
    - React
  - RNKeychain (6.1.1):
    - React
  - RNLocalize (1.4.3):
    - React-Core
  - RNScreens (2.15.0):
    - React-Core
  - Yoga (1.14.0)
  - YogaKit (1.18.1):
    - Yoga (~> 1.14)

DEPENDENCIES:
  - appcenter-analytics (from `../node_modules/appcenter-analytics/ios`)
  - appcenter-core (from `../node_modules/appcenter/ios`)
  - appcenter-crashes (from `../node_modules/appcenter-crashes/ios`)
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)
  - FBReactNativeSpec (from `../node_modules/react-native/Libraries/FBReactNativeSpec`)
  - Flipper (~> 0.41.1)
  - Flipper-DoubleConversion (= 1.1.7)
  - Flipper-Folly (~> 2.2)
  - Flipper-Glog (= 0.3.6)
  - Flipper-PeerTalk (~> 0.0.4)
  - Flipper-RSocket (~> 1.1)
  - FlipperKit (~> 0.41.1)
  - FlipperKit/Core (~> 0.41.1)
  - FlipperKit/CppBridge (~> 0.41.1)
  - FlipperKit/FBCxxFollyDynamicConvert (~> 0.41.1)
  - FlipperKit/FBDefines (~> 0.41.1)
  - FlipperKit/FKPortForwarding (~> 0.41.1)
  - FlipperKit/FlipperKitHighlightOverlay (~> 0.41.1)
  - FlipperKit/FlipperKitLayoutPlugin (~> 0.41.1)
  - FlipperKit/FlipperKitLayoutTextSearchable (~> 0.41.1)
  - FlipperKit/FlipperKitNetworkPlugin (~> 0.41.1)
  - FlipperKit/FlipperKitReactPlugin (~> 0.41.1)
  - FlipperKit/FlipperKitUserDefaultsPlugin (~> 0.41.1)
  - FlipperKit/SKIOSNetworkPlugin (~> 0.41.1)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - RCTRequired (from `../node_modules/react-native/Libraries/RCTRequired`)
  - RCTTypeSafety (from `../node_modules/react-native/Libraries/TypeSafety`)
  - React (from `../node_modules/react-native/`)
  - React-callinvoker (from `../node_modules/react-native/ReactCommon/callinvoker`)
  - React-Core (from `../node_modules/react-native/`)
  - React-Core/DevSupport (from `../node_modules/react-native/`)
  - React-Core/RCTWebSocket (from `../node_modules/react-native/`)
  - React-CoreModules (from `../node_modules/react-native/React/CoreModules`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)
  - react-native-splash-screen (from `../node_modules/react-native-splash-screen`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - ReactCommon/turbomodule/core (from `../node_modules/react-native/ReactCommon`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-community/async-storage`)"
  - "RNCMaskedView (from `../node_modules/@react-native-community/masked-view`)"
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNKeychain (from `../node_modules/react-native-keychain`)
  - RNLocalize (from `../node_modules/react-native-localize`)
  - RNScreens (from `../node_modules/react-native-screens`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  trunk:
    - AppCenter
    - AppCenterReactNativeShared
    - boost-for-react-native
    - CocoaAsyncSocket
    - CocoaLibEvent
    - Flipper
    - Flipper-DoubleConversion
    - Flipper-Folly
    - Flipper-Glog
    - Flipper-PeerTalk
    - Flipper-RSocket
    - FlipperKit
    - OpenSSL-Universal
    - YogaKit

EXTERNAL SOURCES:
  appcenter-analytics:
    :path: "../node_modules/appcenter-analytics/ios"
  appcenter-core:
    :path: "../node_modules/appcenter/ios"
  appcenter-crashes:
    :path: "../node_modules/appcenter-crashes/ios"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  FBLazyVector:
    :path: "../node_modules/react-native/Libraries/FBLazyVector"
  FBReactNativeSpec:
    :path: "../node_modules/react-native/Libraries/FBReactNativeSpec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  RCTRequired:
    :path: "../node_modules/react-native/Libraries/RCTRequired"
  RCTTypeSafety:
    :path: "../node_modules/react-native/Libraries/TypeSafety"
  React:
    :path: "../node_modules/react-native/"
  React-callinvoker:
    :path: "../node_modules/react-native/ReactCommon/callinvoker"
  React-Core:
    :path: "../node_modules/react-native/"
  React-CoreModules:
    :path: "../node_modules/react-native/React/CoreModules"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  react-native-safe-area-context:
    :path: "../node_modules/react-native-safe-area-context"
  react-native-splash-screen:
    :path: "../node_modules/react-native-splash-screen"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  ReactCommon:
    :path: "../node_modules/react-native/ReactCommon"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-community/async-storage"
  RNCMaskedView:
    :path: "../node_modules/@react-native-community/masked-view"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  RNKeychain:
    :path: "../node_modules/react-native-keychain"
  RNLocalize:
    :path: "../node_modules/react-native-localize"
  RNScreens:
    :path: "../node_modules/react-native-screens"
  Yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  AppCenter: 0487be185c038ed2ecc5ed38219af1dcd280af23
  appcenter-analytics: 3e8bf76870877c5abdfb752e1dc014be2b2030e4
  appcenter-core: e7aa4513ee9173b82c4a4497d49abb0ec7ceb159
  appcenter-crashes: 0052b9ae5cc6b5c184238eb6c230ed5942d91f10
  AppCenterReactNativeShared: 66667cd2dfad295b84bbf0f462e0e139e2128284
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  CocoaAsyncSocket: 694058e7c0ed05a9e217d1b3c7ded962f4180845
  CocoaLibEvent: 2fab71b8bd46dd33ddb959f7928ec5909f838e3f
  DoubleConversion: cde416483dac037923206447da6e1454df403714
  FBLazyVector: 3ef4a7f62e7db01092f9d517d2ebc0d0677c4a37
  FBReactNativeSpec: dc7fa9088f0f2a998503a352b0554d69a4391c5a
  Flipper: 33585e2d9810fe5528346be33bcf71b37bb7ae13
  Flipper-DoubleConversion: 38631e41ef4f9b12861c67d17cb5518d06badc41
  Flipper-Folly: e4493b013c02d9347d5e0cb4d128680239f6c78a
  Flipper-Glog: 1dfd6abf1e922806c52ceb8701a3599a79a200a6
  Flipper-PeerTalk: 116d8f857dc6ef55c7a5a75ea3ceaafe878aadc9
  Flipper-RSocket: 64e7431a55835eb953b0bf984ef3b90ae9fdddd7
  FlipperKit: bc68102cd4952a258a23c9c1b316c7bec1fecf83
  Folly: b73c3869541e86821df3c387eb0af5f65addfab4
  glog: 40a13f7840415b9a77023fbcae0f1e6f43192af3
  OpenSSL-Universal: ff34003318d5e1163e9529b08470708e389ffcdd
  RCTRequired: f13f25e7b12f925f1f6a6a8c69d929a03c0129fe
  RCTTypeSafety: 44982c5c8e43ff4141eb519a8ddc88059acd1f3a
  React: e1c65dd41cb9db13b99f24608e47dd595f28ca9a
  React-callinvoker: 552a6a6bc8b3bb794cf108ad59e5a9e2e3b4fc98
  React-Core: 9d341e725dc9cd2f49e4c49ad1fc4e8776aa2639
  React-CoreModules: 5335e168165da7f7083ce7147768d36d3e292318
  React-cxxreact: d3261ec5f7d11743fbf21e263a34ea51d1f13ebc
  React-jsi: 54245e1d5f4b690dec614a73a3795964eeef13a8
  React-jsiexecutor: 8ca588cc921e70590820ce72b8789b02c67cce38
  React-jsinspector: b14e62ebe7a66e9231e9581279909f2fc3db6606
  react-native-safe-area-context: 8260e5157617df4b72865f44006797f895b2ada7
  react-native-splash-screen: 200d11d188e2e78cea3ad319964f6142b6384865
  React-RCTActionSheet: 910163b6b09685a35c4ebbc52b66d1bfbbe39fc5
  React-RCTAnimation: 9a883bbe1e9d2e158d4fb53765ed64c8dc2200c6
  React-RCTBlob: 39cf0ece1927996c4466510e25d2105f67010e13
  React-RCTImage: de355d738727b09ad3692f2a979affbd54b5f378
  React-RCTLinking: 8122f221d395a63364b2c0078ce284214bd04575
  React-RCTNetwork: 8f96c7b49ea6a0f28f98258f347b6ad218bc0830
  React-RCTSettings: 8a49622aff9c1925f5455fa340b6fe4853d64ab6
  React-RCTText: 1b6773e776e4b33f90468c20fe3b16ca3e224bb8
  React-RCTVibration: 4d2e726957f4087449739b595f107c0d4b6c2d2d
  ReactCommon: a0a1edbebcac5e91338371b72ffc66aa822792ce
  RNCAsyncStorage: cb9a623793918c6699586281f0b51cbc38f046f9
  RNCMaskedView: f5c7d14d6847b7b44853f7acb6284c1da30a3459
  RNGestureHandler: 7a5833d0f788dbd107fbb913e09aa0c1ff333c39
  RNKeychain: db956c02a018f7dd3a0ea8a6cf3087bc1894bf2b
  RNLocalize: ff8b96bffbe096a158f952a170741208f2c18746
  RNScreens: 2ad555d4d9fa10b91bb765ca07fe9b29d59573f0
  Yoga: 7740b94929bbacbddda59bf115b5317e9a161598
  YogaKit: f782866e155069a2cca2517aafea43200b01fd5a

PODFILE CHECKSUM: f6618a74483f4bca53ac7d32ec5045280cf7b64c

COCOAPODS: 1.10.0

**Comment by CyberMew** [comment]
Can you try run `pod repo update`, delete your Podfile.lock and Pods folders and try to npm install (or pod install, depending on your setup) again? You updated your npm package version but seems like it is still pulling the old native dependencies (the RN packages depends on some native pods).

**Comment by MatkovIvan** [comment]
@CyberMew thanks for helping here :)

@ulrichsi-hrbl - it's because of mixing 4.x and 3.x:
```
appcenter-analytics (4.0.0):
AppCenter/Analytics
AppCenterReactNativeShared
React-Core
appcenter-core (4.0.0):
AppCenterReactNativeShared
React-Core
appcenter-crashes (4.0.0):
AppCenter/Crashes
AppCenterReactNativeShared
React-Core
AppCenter/Analytics (3.3.4):
AppCenter/Core
AppCenter/Core (3.3.4)
```

reinstalling pods as suggested should help

**Comment by ulrichsi-hrbl** [comment]
Thank you, that fixed it.

**Comment by midoalone** [comment]
@CyberMew Your solution worked, thanks

**Comment by KristenLeach** [comment]
I have followed the above steps of pod repo update > delete podfile & pods > pod install; I've cleared my caches, reinstalled npm packages, and I am still getting the exact mismatch mentioned above. Is there a step that I have misunderstood? If I understand the [troubleshooting docs](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#build-error-such-as-appcentercrashesmsacerrorreporth-file-not-found) correctly, it seems as though there is some issue with cocoapods CLI not being installed properly? I can see that the node_modules/appcenter/ios/scripts/postlink.js should be adding { pod: 'AppCenterReactNativeShared', version: '4.0.0' }] to the pod dependencies. This doesn't appear to be happening.

**Comment by KristenLeach** [comment]
^ Actually, I finally figured out my issue. We had previously been using 'appcenter-push'. Although the docs suggested uninstalling appcenter, appcenter-analytics, & appcenter-crashes before updating their versions, it did not mention appcenter-push. I assume this is because it is being phased out; but I did not know _that_ until I dug deeper into this issue. A note in the react-native sdk troubleshooting documentation to uninstall this package (and any other outdated deps if they exist) could only help. It would have saved me a lot of time digging!

It appears as though the appcenter-push pod depended on lower versions of AppCenter/Core & AppCenterReactNativeShared (3.3.1 & 3.3.4, I believe). I assume that because this package required a lower version than the rest, cocoapods was installing the lower versions for compatibility? I can't be sure, but that's what it seems to be. Once I ran npm uninstall appcenter-push and deleted my pods/updated/re installed, it finally built.

**Comment by yogieeka** [comment]
1. delete pods folder folder in ios/Pods
2. delete podfile.lock
3. yarn remove appcenter-push
4. pod install again
5. clean project
6. build and run !!!!

**Comment by Zabi-Progton** [comment]
This is my Podfile.lock, I have tried removing the pods and reinstalling using the above commands but still same issue. This is the pods present:

  **- appcenter-analytics (4.1.0):
    - AppCenter/Analytics (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-core (4.1.0):
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - appcenter-crashes (4.1.0):
    - AppCenter/Crashes (~> 4.0)
    - AppCenterReactNativeShared (~> 4.0)
    - React-Core
  - AppCenter/Analytics (4.1.1):
    - AppCenter/Core
  - AppCenter/Core (4.1.1)
  - AppCenter/Crashes (4.1.1):
    - AppCenter/Core
  - AppCenterReactNativeShared (4.1.0):
    - AppCenter/Core (= 4.1.1)**

**Comment by DmitriyKirakosyan** [comment]
@Zabi-Progton 

Can you try to reproduce the issue on an empty project and possibly share a sample app?
If it is not reproducing on a new project, please create a separate issue and fill out the issue template form.

**Comment by yungpear** [comment]
I'm getting the same issue

**Comment by DmitriyKirakosyan** [comment]
Hi @yungpear 

Please answer the questions from the issue template form. This will help us to investigate the issue.
Can you reproduce the issue on an empty project?
