### ISSUE TITLE
Send manually a crash report

### ISSUE THREAD

**Issue by jsellam** [microsoft/appcenter-sdk-react-native#881]
Hi,
Is it possible to send manually a crash report to app center ?

The reports are automatically send after a real crash, but is it possible to send a crash report without a real crash of the app ?
In my case, the crash is handled by a try / catch , but I would like to send a report about it.

Best regards,
Jeremie.

**Comment by olmisa** [comment]
Hello @jsellam ,
thanks for using App Center. We already track a similar feature request [here](https://github.com/microsoft/appcenter/issues/358). Our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) mentioned that the App Center team will prioritize improving reliability and performance for the service through mid-2021. This means new feature work will be significantly reduced.
I can't definitely say when this functionality will be implemented. The native SDKs already have this functionality. If you need it asap you could implement it to react-native SDK.
Thanks

**Comment by tdevere** [comment]
also sharing reference to uploading crashes via the API - https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes

**Comment by jsellam** [comment]
Thank you @olmisa and @tdevere it's done with the crash api. !
It could be a good to expose the app_secret to react-native app via :
`await AppCenter.getAppSecret()`

**Comment by DmitriyKirakosyan** [comment]
Hi @jsellam ,

The feature is implemented and included in the recent [release 4.3.0](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.3.0).
Here is the [Handled Errors API documentation](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native#handled-errors).
I'm closing the issue but feel free to reach out if you have additional questions.
