### ISSUE TITLE
Building app on physical iOS device fails (error: building for iOS, but linking in object file built for Mac Catalyst) 

### ISSUE THREAD

**Issue by Echelpoel** [microsoft/appcenter-sdk-react-native#889]
### **Description**

When upgrading appcenter, appcenter-analytics and appcenter-crashes to `^4.0.2` (coming from `^3.0.2`), the app fails to build on an iOS **device** showing this error message in Xcode:

```
in XXX/Build/Products/Debug-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalyticsAuthenticationProvider.o), building for iOS, but linking in object file built for Mac Catalyst, file 'XXX/Build/Products/Debug-iphoneos/AppCenterAnalytics.framework/AppCenterAnalytics' for architecture arm64
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Add or upgrade appcenter, appcenter-analytics and appcenter-crashes to `^4.0.2`
2. Try to run React Native app on iOS device

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.0.2
2. Which OS version did you experience the issue on?
    - macOS 11.1 / Xcode 12.3
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - trying to build on physical device
4. What third party libraries are you using?
    - not applicable
5. Run the following command and paste the output below: `react-native info`

```
System:
    OS: macOS 11.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 622.00 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /var/folders/4z/clxr5g_12zn8sy5624f2j4d40000gn/T/yarn--1610564773412-0.7056831412165951/node
    Yarn: 1.22.4 - /var/folders/4z/clxr5g_12zn8sy5624f2j4d40000gn/T/yarn--1610564773412-0.7056831412165951/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: javac 14 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

```
Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2
1.9.1
```

**Comment by gintsmurans** [comment]
Hi! 

We are having the same issue: 
```
ld: in .../AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalytics.o), building for iOS, but linking in object file (.../AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalytics.o)) built for Mac Catalyst, for architecture arm64
```

**Comment by Echelpoel** [comment]
Reverting back to version `3.1.3` fixes the issue for now.

**Comment by gintsmurans** [comment]
It does, thanks.

**Comment by bmkopp10** [comment]
I am also having the same issue, and reverting it also fixes it.

**Comment by russelarms** [comment]
Hi @Echelpoel @gintsmurans @bmkopp10, please try to update your Cocoapods version to 1.10 or above, it should fix the issue.
It was reported in our Apple SDK: https://github.com/microsoft/appcenter-sdk-apple/issues/2251
and turned out to be a bug in the previous Cocoapods versions.

**Comment by karlotracs** [comment]
> Hi @Echelpoel @gintsmurans @bmkopp10, please try to update your Cocoapods version to 1.10 or above, it should fix the issue.
> It was reported in our Apple SDK: [microsoft/appcenter-sdk-apple#2251](https://github.com/microsoft/appcenter-sdk-apple/issues/2251)
> and turned out to be a bug in the previous Cocoapods versions.

This worked for me.

**Comment by russelarms** [comment]
I'm closing this issue, feel free to reply if you encounter the same problem again and we'll re-open it.

**Comment by andreaagudo3** [comment]
> microsoft/appcenter-sdk-apple#2251

Updated cocoapods but still having the same issue

**Comment by Jamminroot** [comment]
Hey @andreaagudo3, sorry to hear that, and my apologize for such a delay in response. Would you mind sharing some additional details:
Environment details (rn\pod version, xcode version)
Is it an update from previous version, or you just have added the SDK?
Can you share some build logs describing the problem? That'd help us understand what's wrong.
Also, can you check if it is reproduced on an empty project?

**Comment by russelarms** [comment]
@andreaagudo3 please, run `pod repo update` and then `pod install` and try again.

**Comment by Jamminroot** [comment]
We haven't heard from you for a while, so I'm closing the issue for now, but feel free to reopen would you need further assistance.

**Comment by LoganBrownStFX** [comment]
Hey everyone,

I seem to be still having this issue.

**Comment by LoganBrownStFX** [comment]
Hi everyone,

I seem to still be having this issue.

I've followed all the steps listed here, but I'm still getting the same output from xcode.

1. Which version of the App Center SDK are you using?
3.1.2
2. Which OS version did you experience the issue on?
macOS 11.3 / Xcode 12.5.1
3. What device version did you see this error on? Were you using an emulator or a physical device?
iPhone 12 emulator
4. react-native info
`System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 33.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

Other members on the team with intel based macbooks seem to be fine

**Comment by DmitriyKirakosyan** [comment]
Hi @LoganBrownStFX

Thank you for getting back to us with this report and the updated details about your dev environment!

Was the issue fixed for you previously and if "yes", what steps did you make to fix that?
What was updated so the issue appeared again? AppCenter SDK update, Xcode update, macOS update, react-native update? 
Have you tried to update App Center SDK to the latest version (4.2.0)?
Have you tried to reproduce the issue on a new project?

**Comment by DmitriyKirakosyan** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
