### ISSUE TITLE
Not Able to use Login Functionality in React Native SDK in Android API Level 30

### ISSUE THREAD

**Issue by prorohit** [microsoft/appcenter-sdk-react-native#893]
### **Not Able to Login use Login Functionality in RN SDK in Android API Level 30**

I am not able to use the login functionality by using the React Native SDK in Android level 30.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. User the SDK version as described below
     "appcenter": "4.0.2",
    "appcenter-analytics": "4.0.2",
    "appcenter-crashes": "4.0.2",
2. Sign in functionality does not open the in App browser for filling up the login details.

**{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"message":"Error not specified.","code":"browser_not_found","line":2144,"column":45,"sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}**

### **Details**

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 26.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5

Place output here

**{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"message":"Error not specified.","code":"browser_not_found","line":2144,"column":45,"sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}**

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
Could you please clarify in which case this issue happens? Our Analytics and Crashes modules don't use the browser.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if it isn’t resolved or you have additional questions.
