### ISSUE TITLE
i have a problem with v 4.0.2 on my react native app android version

### ISSUE THREAD

**Issue by Saeid-Barzegar** [microsoft/appcenter-sdk-react-native#897]
I installed app center v 4.0.2 on my react native app
in IOS everything is okay and working properly with V4.0.2
but in Android, I can't run the project with this version
when I'm using version 3.1.2 everything is okay in android but I can't use v3.1.2 on IOS because I'm using IOS 14.3 and can't downgrade it

just in Android with v4.0.2 of app center I receiving this error

> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
121 actionable tasks: 2 executed, 119 up-to-date
/Users/alephian/Projects/my-digi-mobile/android/app/src/debug/AndroidManifest.xml:36:5-38:41 Error:
	uses-sdk:minSdkVersion 17 cannot be smaller than version 21 declared in library [:appcenter] /Users/alephian/Projects/my-digi-mobile/node_modules/appcenter/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.microsoft.appcenter.reactnative.appcenter" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 21 declared in library [:appcenter] /Users/alephian/Projects/my-digi-mobile/node_modules/appcenter/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 17
  	Suggestion: use a compatible library with a minSdk of at most 17,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.microsoft.appcenter.reactnative.appcenter" to force usage (may lead to runtime failures)

Project Settings: 
- react native v0.62
- android:minSdkVersion="17"
- android:targetSdkVersion="29"
- gradle v6.3

to complete my description
- I increased the minSdkVerion to 21 and more (even 29) but it didn't work
- already changed the Gradle version to the last release but it didn't work again

**Comment by russelarms** [comment]
Hi @Saeid-Barzegar, I've had the same problem with a new app, but after increasing the minSdkVersion to 21 the problem disappeared.
Pls, share what are the errors after you increased the minSdkVersion.

**Comment by Saeid-Barzegar** [comment]
Hi @russelarms, your right
I was changing my app minSdkVeriosn in the wrong **build.gradle** file
it's okay and working fine with **SDK 21**
but I have a question here:
I have to use SDK 17 as the minimum SDK version
what will happen if I use two different versions of appCenter for android and IOS ( 4.0.2 for IOS and 3.1.2 for Android )
can I use them separately and manage them from appCenter panel?

**Comment by russelarms** [comment]
@Saeid-Barzegar most of the changes between 3.1.2 and 4.0.2 are related to the iOS platform and there are no breaking changes in Android (except for the min SDK version change): https://github.com/microsoft/appcenter-sdk-react-native/compare/3.1.2...4.0.2
That's why I would give it a try. You can try installing 4.0.2 and then downgrade build.gradle dependencies inside each appcenter node module you use to the following versions:
https://github.com/microsoft/appcenter-sdk-react-native/blob/d040c0fa547a03b71e896b31252fb9d960821f13/appcenter/android/build.gradle#L27-L30
https://github.com/microsoft/appcenter-sdk-react-native/blob/d040c0fa547a03b71e896b31252fb9d960821f13/appcenter-analytics/android/build.gradle#L27-L30
https://github.com/microsoft/appcenter-sdk-react-native/blob/d040c0fa547a03b71e896b31252fb9d960821f13/appcenter-crashes/android/build.gradle#L27-L30

**Comment by Jamminroot** [comment]
Hey, @Saeid-Barzegar, we haven't heard from you for a while, is the issue resolved? I'm closing it now, but feel free to reopen with details requested [in the message above](https://github.com/microsoft/appcenter-sdk-react-native/issues/897/#issuecomment-772278782) otherwise.

**Comment by Saeid-Barzegar** [comment]
yes @Jamminroot ,
thanks for closing
