### ISSUE TITLE
Build failed for Mac Catalyst

### ISSUE THREAD

**Issue by robertying** [microsoft/appcenter-sdk-react-native#901]
### **Description**

`AppCenterReactNativeShared` blocked the build from succeeding:

```
ld: in /Users/rying/myapp/ios/Pods/AppCenterReactNativeShared/AppCenterReactNativeShared/AppCenterReactNativeShared.framework/AppCenterReactNativeShared(AppCenterReactNativeShared.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/rying/myapp/ios/Pods/AppCenterReactNativeShared/AppCenterReactNativeShared/AppCenterReactNativeShared.framework/AppCenterReactNativeShared' for architecture x86_64
```

This seems to be a problem of prebuilt framework which does not contain the correct build for x86-64 target (not a simulator).

This fix https://github.com/microsoft/appcenter-sdk-react-native/pull/896 may be relevant.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Init with RN 0.63.4
2. Install App Center SDK
3. `pod install`
4. Build for Mac Catalyst

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.0.2
2. Which OS version did you experience the issue on?
    - iOS 14
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - My Mac
4. What third party libraries are you using?
    - None
5. Run the following command and paste the output below: `react-native info`

```
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 91.70 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/mh/h5b3z2k57b37b17qxy8_347w0000gn/T/yarn--1614266130567-0.4213697991610377/node
    Yarn: 1.22.10 - /var/folders/mh/h5b3z2k57b37b17qxy8_347w0000gn/T/yarn--1614266130567-0.4213697991610377/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: 22.0.7026061
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.10.1

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

Not applicable

**Comment by DmitriyKirakosyan** [comment]
Hi @robertying

Thank you for getting in touch with us!

The PR you mentioned should be related indeed, however I was not able to build for mac catalyst with that changes.
I will investigate the problem and get back to you with an update.

**Comment by fbernaly** [comment]
I am getting the same bug, I cannot run in the device or archive

```
AppCenterAnalytics.framework/AppCenterAnalytics(MSACAnalytics.o), building for iOS, but linking in object file built for Mac Catalyst, for architecture arm64
```

is there any ETA for the fix?

**Comment by russelarms** [comment]
@fbernaly We're working on the fix: https://github.com/microsoft/appcenter-sdk-react-native/pull/902

**Comment by charmian01** [comment]
Hey!
We've included fixes in the latest SDK release for this. I'm closing the issue but please reopen if you run into this again.
