### ISSUE TITLE
support building React Native 0.64

### ISSUE THREAD

**Issue by gevorgsahakyann** [microsoft/appcenter-sdk-react-native#905]
### **Description**

Currently, there are 2 issues in AC with regard to this
* Usage of Android Gradle Plugin 4.1.0+ is not supported at the moment.
* Node version is incompatible with RN 0.64

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 4.0.2
  

<img width="877" alt="node" src="https://user-images.githubusercontent.com/45065751/111464276-fc41fa00-8739-11eb-8aff-836158701b3a.png">

**Comment by MatkovIvan** [comment]
Hi @gevorgsahakyann,

Thanks for getting in touch! However, as mentioned in issue template, we're using this repo for **SDK specific** issues only.
I see that you've already found [related feature request](https://github.com/microsoft/appcenter/issues/2144), so let's track this build service problem there.
