### ISSUE TITLE
distribute build not working 

### ISSUE THREAD

**Issue by morelgarisi** [microsoft/appcenter-sdk-react-native#914]
not able to distribute builds for users on android and ios

**Comment by DmitriyKirakosyan** [comment]
Hi @morelgarisi 

Thank you for getting in touch with us!

Please fill out the "Problem report" form as it is suggested when you create a new issue.

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
