### ISSUE TITLE
Trying to build a react Native code on iOS but get the error about 

### ISSUE THREAD

**Issue by apptologyindia** [microsoft/appcenter-sdk-react-native#916]
xcodebuild: error: Scheme <Project Name >  is not currently configured for the clean action.

##[error]Error: /usr/bin/xcodebuild failed with return code: 66

I can't see any other error in the logs. 

From reading a few articles, they said that we have to have test target to the scheme in the project which we already have 
Now what ?

**Comment by apptologyindia** [comment]
Attached are the detailed log files. 
[logs_11.zip](https://github.com/microsoft/appcenter-sdk-react-native/files/6327693/logs_11.zip)

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Please, fill out an issue template. To do that click `New issue` > `Problem report`.

Based on your logs I didn't find related error logs to App Center SDK.
Does this issue happen on an empty project, existing project, or in both cases? What version of react-native do you use?

Also, I see in the logs the next error:
```
2021-04-16T19:09:26.3459370Z failed to read project: DractaDoctor {
2021-04-16T19:09:26.3466480Z   error: Error: ENOENT: no such file or directory, open '/Users/runner/work/1/s/ios/DractaDoctor.xcodeproj/project.pbxproj'
```
Could you please make sure that this path exists?

**Comment by AnastasiaKubova** [comment]
We haven’t heard from you in a while so I’m closing this issue but feel free to reopen this issue if you have additional questions.
