### ISSUE TITLE
No known class method for selector 'setNetworkRequestsAllowed:'

### ISSUE THREAD

**Issue by rskapadiadev** [microsoft/appcenter-sdk-react-native#924]
Version:
---
AppCenter version: 4.2.0

System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 65.88 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
We had an issue on our CI releasing the new version to cocoapods.
It is now resolved and the version is published.

Sorry for the inconvenience.

**Comment by leofontes** [comment]
@AnastasiaKubova I'm getting this error right now, how can I ensure that I have the latest Cocoapod?

**Comment by AnastasiaKubova** [comment]
Please make sure that in your project you use the latest App Center SDK version ([4.2.0](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.2.0)) and try to perform: 
- `pod cache clean --all`
- `pod repo update`

**Comment by xgenem** [comment]
Couldn't resolve the issue ....

**Comment by xgenem** [comment]
`pod update`  did the trick for me

**Comment by AnastasiaKubova** [comment]
You also can try to remove content from this path `~/.cocoapods/repos/` and install pods again.

**Comment by sujithln** [comment]
> You also can try to remove content from this path `~/.cocoapods/repos/` and install pods again.

it was installing AppCenter (4.1.0), after removing the content of `~/.cocoapods/repos/` AppCenter (4.2.0) is installed to pod Thank you

**Comment by rskapadiadev** [comment]
@AnastasiaKubova Thank you
> i have installed AppCenter (4.2.0) 
```
pod deintegrate
pod install
```
