### ISSUE TITLE
React Native Android build failing on API level 31 and 30

### ISSUE THREAD

**Issue by sabun123** [microsoft/appcenter-sdk-react-native#928]
### **Description**

Building an Android version of a React Native app with API Level 31 fails with the following error below:

```JavaScript
> Task :app:compileUatReleaseJavaWithJavac FAILED
An exception has occurred in the compiler (1.8.0_302). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
```

If we drop it back down to Android API level 30, the App Center build pipeline fails with:
```JavaScript
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processUatReleaseResources'.
> Android resource linking failed
  /Users/runner/.gradle/caches/transforms-2/files-2.1/dda2b12273ab785c60ddb1545e6bd2a0/res/values/values.xml:2363:5-2390:25: AAPT: error: resource android:attr/lStar not found.
      
  error: failed linking references.
```

We cannot drop back to API Level 29 as the Google Play Store now requires the API Level to be a minimum of 30.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Have a React Native app running an Android build in App Center
2. Have the compileSdkVersion set to `31` in the file `android/build.gradle`
3. Have the targetSdkVersion set to `31` in the file `android/build.gradle`

### **Details**

1. Which version of the App Center SDK are you using?
    - `4.0.0`
2. Which OS version did you experience the issue on?
    - This is happening in App Center
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Does not apply
4. What third party libraries are you using?
    - Does not apply
5. Run the following command and paste the output below: `react-native info`

```JavaScript
$ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 73.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.5.1 - /var/folders/dn/r9ml18_14mbbyz63_0lz9clm0000gn/T/yarn--1631537427133-0.023348115010556558/node
    Yarn: 1.22.10 - /var/folders/dn/r9ml18_14mbbyz63_0lz9clm0000gn/T/yarn--1631537427133-0.023348115010556558/yarn
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7199119
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
✨  Done in 7.09s.
```

Final notes:
Building and running locally works perfectly fine. The issue happens solely in App Center.

**Comment by DmitriyKirakosyan** [comment]
Hi @sabun123 ,

Thanks for getting in touch with us!
This is not an SDK issue, please reach out to our support team using [Contact Support](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) button on the App Center portal.

**Comment by AlisonG2** [comment]
Is your problem resolved?

I'm going through the same difficulty, after doing some research I found that sdk31 needs jdk11 to be successful.
From what I saw in the appcenter logs, the version used is jdk8.

**Comment by AnastasiaKubova** [comment]
Hi, @AlisonG2 ! Thanks for getting in touch with us!
This is not an SDK issue. If you are facing the same problem you can try to open a [support ticket](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) on the App Center portal.
