### ISSUE TITLE
'AppCenterCrashes/MSACWrapperExceptionModel.h' file not found in 4.3.0

### ISSUE THREAD

**Issue by johnryan** [microsoft/appcenter-sdk-react-native#935]
### **Description**

After upgrading to 4.3.0 I've started getting this error  'AppCenterCrashes/MSACWrapperExceptionModel.h'

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. 
2.

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.3.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A

System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 574.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/johnryan/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /Users/johnryan/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.10.2

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us!
Did you try to:
- `pod cache clean --all`
- `pod repo update`

or remove content from this path `~/.cocoapods/repos/` and re-install pods?

**Comment by johnryan** [comment]
@AnastasiaKubova Looks like i had to rm my podfile.lock in order for AppCenter and AppCenterReactNativeShared to update. Thanks for the suggestions!
