### ISSUE TITLE
Error Not Found. Correlation ID: XXX

### ISSUE THREAD

**Issue by gunnartorfis** [microsoft/appcenter-sdk-react-native#939]
### **Description**
This is only happening on Android builds, not iOS. 
It was happening a few days ago and I fixed it by re-linking the GitHub repo and setting up our build settings again from scratch. It started happening again after a few successful builds. Here's the error message, inside the *Create distribution* step. 

##[error]"{\"message\":\"Not found. Correlation ID: 5075b4cd-633c-4053-982c-04b5c16ef1a3\",\"statusCode\":404,\"code\":\"Not Found\"}"

### **Details**

1. Which version of the App Center SDK are you using?
    - "appcenter": ^4.3.0
2. Which OS version did you experience the issue on?
    - Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - Build pipeline
4. What third party libraries are you using?
5. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 40.47 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.1.0 => 6.1.0 
    react: ^17.0.2 => 17.0.2 
    react-native: 0.66.2 => 0.66.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

Place output here

**Comment by DmitriyKirakosyan** [comment]
Hi @gunnartorfis ,

Thank  you for getting in touch with us!

This issue doesn't look like an SDK issue, it is related to the App Center Build engine. Please [contact support team](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) (appcenter.ms -> ? (question mark, top right corner) -> Contact support) and select `Build` in the dropdown list.
