### ISSUE TITLE
How to add appcenter to ios ? keeps failing, ios newbie.

### ISSUE THREAD

**Issue by abdullahIsa** [microsoft/appcenter-sdk-react-native#958]
Hello, I have recently been trying to add appcenter to ios, previously before adding appcenter i got it to run but after trying to add appcenter it keeps failing, I mostly work on android but due to boss new requirements I need to have it running on ios too, so please help out as I do not know much about how ios/Xcode configurations work.

Please note i am doing all this on a remote mac, thanks.

## **AppCenter-Config.plist**
I added this file but in the documentation, it's stated to do this also `Don't forget to add this file to the Xcode project (right-click the app in Xcode and click Add files to <AppName>...).`  may I know how to do this in Xcode? I have searched online and also went through the Xcode but I am really lost and don't know what to do.

![image](https://user-images.githubusercontent.com/49385380/151717552-aff573a1-c228-41f1-8e00-49acaabcc7c0.png)

## **AppDelegate.m**
![image](https://user-images.githubusercontent.com/49385380/151717446-081bc24e-b00b-4eed-967e-a18ac4ef1ad6.png)

![image](https://user-images.githubusercontent.com/49385380/151717458-4fe0c844-edf7-4359-ae5a-476c552d4183.png)

## **Terminal errors**

/Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:76:37: implicit conversion loses integer precision: 'MSACLogLevel' (aka 'enum MSACLogLevel') to 'int' [-Wshorten-64-to-32]

    resolve([NSNumber numberWithInt:[MSACAppCenter logLevel]]);
            ^~~~~~~~~

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:5: use of undeclared identifier 'MSACCustomProperties'

    MSACCustomProperties *customProperties = [MSACCustomProperties new];
            ~                       ^~~~~~~~~~~~~~~~~~~~~~~~

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:27: use of undeclared identifier 'customProperties'

    MSACCustomProperties *customProperties = [MSACCustomProperties new];
    ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:97:47: use of undeclared identifier 'MSACCustomProperties'

    MSACCustomProperties *customProperties = [MSACCustomProperties new];
                          ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:107:22: use of undeclared identifier 'customProperties'

                    [customProperties setString:value forKey:key];
                                              ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:110:22: use of undeclared identifier 'customProperties'

                    [customProperties setNumber:value forKey:key];
                     ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:114:22: use of undeclared identifier 'customProperties'

                    [customProperties setBool:[num boolValue] forKey:key];
                     ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:118:22: use of undeclared identifier 'customProperties'

                    [customProperties setDate:date forKey:key];
                     ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:121:22: use of undeclared identifier 'customProperties'

                    [customProperties clearPropertyForKey:key];
                     ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:20: no known class method for selector 'setCustomProperties:'

    [MSACAppCenter setCustomProperties:customProperties];
                     ^

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:40: use of undeclared identifier 'customProperties'

    [MSACAppCenter setCustomProperties:customProperties];
                   ^~~~~~~~~~~~~~~~~~~

❌  /Users/user210769/Desktop/app/esolved/iesmobile/node_modules/appcenter/ios/AppCenterReactNative/AppCenterReactNative.m:126:20: no known class method for selector 'setCustomProperties:'

    [MSACAppCenter setCustomProperties:customProperties];
                                       ^

▸ Compiling AppCenterReactNativeAnalytics.m
▸ Building library libReact-jsiexecutor.a
▸ Building library libReact-Core.a
    Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the iesmobile editor. (in target 'iesmobile' from project 'iesmobile')
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening iesmobile.xcworkspace.
info Run CLI with --verbose flag for more details.
AS021:iesmobile user210769$

**Comment by AnatolyPristensky** [comment]
Hello, @abdullahIsa!
Thanks for getting in touch with us!
Looks like this is a duplicate of #955.

Please, follow the steps described in guide [Get Started with React Native](https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native)
Please, make sure that you use the latest App Center SDK version ([4.4.3](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.4.3)) and try to perform:
- `pod cache clean --all`
- `pod repo update`

Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check if the issue is gone.

**Comment by abdullahIsa** [comment]
@AnatolyPristensky thanks very much, upgrading to 4.4.3 got it working.
