### ISSUE TITLE
Unable to run the iOS app with the latest version

### ISSUE THREAD

**Issue by DeebanT2S** [microsoft/appcenter-sdk-react-native#959]
### **Description**

I'm using this npm in my react native application. Recently, I have faced the iOS build failure in AppCenter due to lower version(4.1.0). So, I have increased the dependency version as 4.4.3 from 4.1.0 after that it's working fine. But, we are unable run the app locally with the latest version

**Most Recent Version** -> I can run the app locally but it's getting failed in app center
 "appcenter": "4.1.0",
 "appcenter-analytics": "4.1.0",
 "appcenter-crashes": "4.1.0",

**Updated Version** -> I can't run the app locally but it's getting success in app center
 "appcenter": "4.4.3",
 "appcenter-analytics": "4.4.3",
 "appcenter-crashes": "4.4.3",

Please do the needful thanks in advance

Please describe the issue you are facing using the SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Increase the version and update the pod then run the application

### **Details**

1. Which version of the App Center SDK are you using?
    - e.g. 4.4.3
2. Which OS version did you experience the issue on?
     iOS 11 Pro (OS 13.5)
4. What third party libraries are you using?
  "appcenter": "4.4.3",
 "appcenter-analytics": "4.4.3",
 "appcenter-crashes": "4.4.3",
5. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 271.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
1.11.2

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by AnatolyPristensky** [comment]
Hello, @DeebanT2S !
Thanks for getting in touch with us!
At first glance It looks like a duplicate of #955.

Please, make sure that you updating to the latest App Center SDK version (4.4.3) correctly and try to perform:

- pod cache clean --all
- pod repo update

Also, please make sure that Podfile.lock file is updated. Try to remove it, run pod install, and check if the issue is gone.
If these steps didn't help, please also share the error log or the particular error message you're getting.

**Comment by DeebanT2S** [comment]
@AnatolyPristensky Thanks for the update it's working fine for me
