### ISSUE TITLE
A problem occurred while extracting your app, for IOS

### ISSUE THREAD

**Issue by abdullahIsa** [microsoft/appcenter-sdk-react-native#962]
Hello, i am trying to create a new ios release for just testing but it always shows this error `A problem occurred while extracting your app`, app is running fine in simulator for both android/ios and i am able to upload build release for android but not ios.

Things i noticed, for android OS everything works fine even the analytics is being displayed but for ios OS its not, i am not sure what went wrong.

Things i have done, i converted the ios build from a .app to a .ipa as instructed here [How to build .ipa application for react-native-ios?](https://stackoverflow.com/questions/42110496/how-to-build-ipa-application-for-react-native-ios)

### Image of ios release build
![image](https://user-images.githubusercontent.com/49385380/152759844-f05936fd-6b53-48e4-ad76-98bff121c13f.png)

### Error:
![image](https://user-images.githubusercontent.com/49385380/152760443-5a541ad7-21b5-41e8-9400-8b900bbde988.png)

**Comment by AnatolyPristensky** [comment]
Hello @abdullahIsa,

Thanks for getting in touch with us!
This is not an SDK issue, please reach out to our support team using [Contact Support](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us) button on the App Center portal.
