### ISSUE TITLE
No known class method for selector 'startSession'

### ISSUE THREAD

**Issue by DennisOstertag** [microsoft/appcenter-sdk-react-native#963]
### **Description**

After installing and building the pods i face the build error  'No known class method for selector 'startSession'.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Setup Appcenter
2. Install latest version of react native
3. npm install
4. pod install
5. build

app/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m:69:18: error: no known class method for selector 'startSession'
  [MSACAnalytics startSession];
                 ^~~~~~~~~~~~
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/.../Library/Developer/Xcode/DerivedData/...-gaenhomviehdmpgpnwtlqygpckmz/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/appcenter-analytics.build/Objects-normal/x86_64/AppCenterReactNativeAnalytics.o /app/node_modules/appcenter-analytics/ios/AppCenterReactNativeAnalytics/AppCenterReactNativeAnalytics.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'appcenter-analytics' from project 'Pods')
(1 failure)

### **Details**

1. Which version of the App Center SDK are you using?
    - appcenter-analytics@^4.4.3
    - appcenter-crashes@^4.4.3
    - appcenter@4.4.3
2. Which OS version did you experience the issue on?
    - e.g. iOS
6. What device version did you see this error on?  Were you using an emulator or a physical device?
    - e.g. no device specific as it happens during build
7. What third party libraries are you using?
    - a lot but that should not cause a compile error in appcenter files
8. Run the following command and paste the output below: `react-native info`

System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 8.31 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.11.1 - /opt/nvm/versions/node/v16.11.1/bin/node
    Yarn: 1.22.17 - /opt/nvm/versions/node/v16.11.1/bin/yarn
    npm: 8.0.0 - /opt/nvm/versions/node/v16.11.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 16.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.67.1 => 0.67.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

9. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`
10.1.10.1

Note:
the same issue is also open at code push repo:
https://github.com/microsoft/react-native-code-push/issues/2225

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! The App Center SDK doesn't have `4.3.3` version. The latest App Center SDK version is [4.4.3](https://github.com/microsoft/appcenter-sdk-react-native/releases/tag/4.4.3).
You also can try to apply suggestions from these issues: #924 and #956

**Comment by DennisOstertag** [comment]
Hi, thanks for the quick reply. I made an error there. I've been using the latest version 4.4.3. I will edit the issue.

**Comment by AnastasiaKubova** [comment]
Did you try suggestions from these issues: https://github.com/microsoft/appcenter-sdk-react-native/issues/924 and https://github.com/microsoft/appcenter-sdk-react-native/issues/956 ?

**Comment by DennisOstertag** [comment]
i tried all the fixes suggested in the other issues:
pod cache clean --all
pod repo update
also i deleted the pods folder and installed again.

The issue does not appear with appcenter 4.3.0.

**Comment by AnastasiaKubova** [comment]
Also please make sure that your `podfile.lock` is updated. Please [see](https://github.com/microsoft/appcenter-sdk-react-native/issues/956#issuecomment-1022038257).

**Comment by DennisOstertag** [comment]
Somehow the references did not update in the Podfile.lock.
Even thought i did a `pod cache clean --all`, `repo update` and `pod install --clean-install`.
Removing the file and running install again fixed the references there.
Thanks for the help!
