### ISSUE TITLE
appcenter-link-scripts is using vulnerable version of minimist

### ISSUE THREAD

**Issue by peltax** [microsoft/appcenter-sdk-react-native#964]
Hello,

appcenter-link-scripts has dependency for minimist 1.2.5 which is vulnerable to prototype pollution. Please upgrade to 1.2.6.

https://github.com/advisories/GHSA-xvch-5gv4-984h

**Comment by DmitriyKirakosyan** [comment]
Hi @peltax , thank you for reaching out! This was fixed in #965.

**Comment by peltax** [comment]
nice, will updated package get published? Last one is from january.

**Comment by DmitriyKirakosyan** [comment]
Hi @peltax , we will release react-native sdk with this fix this month.
