### ISSUE TITLE
Error build in android and ios

### ISSUE THREAD

**Issue by Marcuspo** [microsoft/appcenter-sdk-react-native#967]
### **Description**

i'm try build in app, in my pc the build work normaly, but in appcenter, show error.

### **Repro Steps**

![image](https://user-images.githubusercontent.com/17353066/163099839-c846235c-16eb-421d-9a67-f33cd93a1c8d.png)

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.4.3
2. Which OS version did you experience the issue on?
    - Android 10
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - iPhone simulator and Android simulator inside appcenter
5. Run the following command and paste the output below: `react-native info`

System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
    Memory: 4.11 GB / 15.84 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: javac 18 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.2 => 0.65.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by DmitriyKirakosyan** [comment]
Hi @Marcuspo, thank you for creating a separate issue.
I already replied you on the another thread https://github.com/microsoft/appcenter-sdk-react-native/issues/797/#issuecomment-1097542972.

In your case, please contact our [support team](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us).
Closing this issue, as it is not related to the AppCenter SDK.

**Comment by AndersonVanzo** [comment]
hey, did you find out any solution to this? I'm facing the same problem here

**Comment by Marcuspo** [comment]
@AndersonVanzo Yeah, i resolved this problem in routes, not use absolute path.
