### ISSUE TITLE
Can't build Android app since AppCenter 4.4.4

### ISSUE THREAD

**Issue by TomCorvus** [microsoft/appcenter-sdk-react-native#976]
### **Description**

Hi 👋
Since I update AppCenter packages to 4.4.4 version, I have an error to build Android app.
No problem with 4.4.3.

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:4.4.4.
     Searched in the following locations:
       - file:/Users/user/.m2/repository/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/user/Documents/mobile/packages/appname/node_modules/react-native/android/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/user/Documents/mobile/packages/appname/node_modules/jsc-android/dist/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://dl.google.com/dl/android/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://repo.maven.apache.org/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://jcenter.bintray.com/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - https://www.jitpack.io/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
       - file:/Users/user/Documents/mobile/packages/appname/node_modules/expo-camera/android/maven/com/microsoft/appcenter/reactnative/appcenter-react-native/4.4.4/appcenter-react-native-4.4.4.pom
     Required by:
         project :app > project :appcenter
         project :app > project :appcenter-analytics
         project :app > project :appcenter-crashes

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Install and configure AppCenter packages
2. Try to build Android app (debug or release)

### **Details**

1. Which version of the App Center SDK are you using?
    - 4.4.4
2. Which OS version did you experience the issue on?
    - Android
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - All
4. What third party libraries are you using?

5. Run the following command and paste the output below: `react-native info`

```
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 241.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ~0.68.1 => 0.68.1 
```

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call (you will need to `import com.microsoft.appcenter.AppCenter;`). Include the logs here:

**Comment by ViktorsLV** [comment]
Having the same problem

**Comment by aleksandr-dorofeev** [comment]
We filed an item on our internal dashboard to check this case.
Will update this thread once get results.

**Comment by haveamission** [comment]
Same issue here. Tried running 4.4.4 and it failed. Downgraded to 4.4.3 and it worked.

**Comment by bicanezin** [comment]
I solved changing the `package.json`

just removing the ^

```
    "appcenter": "^4.4.3",
    "appcenter-analytics": "^4.4.3",
    "appcenter-cli": "^2.10.8",
    "appcenter-crashes": "^4.4.3",
```
To
```
   "appcenter": "4.4.3",
    "appcenter-analytics": "4.4.3",
    "appcenter-cli": "2.10.8",
    "appcenter-crashes": "4.4.3",
```

**Comment by ben-qiu** [comment]
Same issue, have to downgrade to 4.4.3

**Comment by TomCorvus** [comment]
Hi there,
@bicanezin That's true. To avoid version range.

**Comment by MrRio** [comment]
We're having the same problem, a downgrade to 4.4.3 fixes it for now.

**Comment by markrickert** [comment]
After attempting to update from 4.4.3 to 4.4.4, I got this same error when trying to build for android.

> Could not find com.microsoft.appcenter.reactnative:appcenter-react-native:4.4.4.

Seems to point to [this change](https://github.com/microsoft/appcenter-sdk-react-native/compare/4.4.3...4.4.4#diff-a5c514c02c558f00e36762945965775c4783307fa9c54fdef730e1a6557c495fL30) but there is no `appcenter-react-native:4.4.4` published in the maven repository: https://repo.maven.apache.org/maven2/com/microsoft/appcenter/reactnative/appcenter-react-native/ Just 4.4.3.

I'm going to stay on 4.4.3 until someone on the appcenter team publishes the correct files to maven.

**Comment by TomCorvus** [comment]
It seems to be working for me 👍

**Comment by aleksandr-dorofeev** [comment]
We updated the maven repository, which should have fixed the issue. I am closing this issue. Feel free to reopen it if you have questions.
