### ISSUE TITLE
I can't show crashed snaped code 

### ISSUE THREAD

**Issue by mohamedanwer123** [microsoft/appcenter-sdk-react-native#984]
I use app center crash and when it log the crash i can't know any part that occured crash .. i wanna show snapshoot of crashed code

**Comment by AnatolyPristensky** [comment]
Hello @mohamedanwer123, could you please share more information about your issue?
Please, use the issue template for that.

**Comment by mohamedanwer123** [comment]
@AnatolyPristensky 

i'm use app center diagonastics to detect crashes in my react native app by using appcenter-crashes package  and
when crash occurred the appcenter-crashes package log crash in app center in this form 

"com.facebook.react.modules.core.ExceptionsManagerModule.reportException ExceptionsManagerModule.java:75
java.lang.reflect.Method.invoke Method.java
com.facebook.react.bridge.JavaMethodWrapper.invoke JavaMethodWrapper.java:148
com.facebook.react.bridge.JavaModuleWrapper.invoke JavaModuleWrapper.java:147
com.facebook.react.bridge.queue.NativeRunnable.run NativeRunnable.java:-2
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage MessageQueueThreadHandler.java
android.os.Looper.loop Looper.java:236
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run MessageQueueThreadImpl.java:37
java.lang.Thread.run Thread.java:923"

this crash form not readable and i can't know what is the crash , i wanna crash logged like this 

[https://cdn.sanity.io/images/p842xl9j/production/e579dd4a100f2f3c57196cddc651f2c4fc3865fe-2250x656.png?w=675&h=197&fit=crop](url)

how i can do this ?

**Comment by AnatolyPristensky** [comment]
@mohamedanwer123, could you please share a [verbose](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native) logs from the application?

**Comment by AnatolyPristensky** [comment]
We haven't heard from you for a while, so I'm closing this issue. 
Please feel free to reopen it in case of new information.
