### ISSUE TITLE
Is there a way to get hold of the Session Id?

### ISSUE THREAD

**Issue by kareldeman** [microsoft/appcenter-sdk-react-native#994]
I would like to get hold of the Session Id so I can pass it into our B2C Sign Up or Sign In as a query parameter or even some of our API calls we make in the app. Reason is that I then can correlate the custom events in the app with the custom events I raise in B2C and our APIs (back-end).

**Comment by AnatolyPristensky** [comment]
Hello @kareldeman,
We are not planning to provide an API for retrieving a session id. I will keep it open to see how many votes this feature request can get.

Also related: https://github.com/microsoft/appcenter/issues/1838

**Comment by ajaymahale** [comment]
+1

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
